CREATE TABLE `portfolio_audit_tb` (
  `portfolio_audit_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `portfolio_id` INT(10) DEFAULT NULL,
  `advisor_id` INT(11) NOT NULL,
  `portfolio_name` VARCHAR(100) DEFAULT NULL,
  `benchmark` INT(11) DEFAULT NULL,
  `portfolio_style` INT(11) DEFAULT NULL,
  `std_dev` DECIMAL(5,2) DEFAULT NULL,
  `sharpe_ratio` INT(11) DEFAULT NULL,
  `exp_returns` DECIMAL(5,2) DEFAULT NULL,
  `alpha` DECIMAL(5,2) DEFAULT NULL,
  `beta` DECIMAL(5,2) DEFAULT NULL,
  `info_ratio` DECIMAL(5,2) DEFAULT NULL,
  `r_squared` TINYINT(4) DEFAULT NULL,
  `VaR` DECIMAL(12,2) DEFAULT NULL,
  `portfolio_90_day_returns` DECIMAL(5,2) DEFAULT NULL,
  `portfolio_1_year returns` DECIMAL(5,2) DEFAULT NULL,
  `benchmark_90_days_returns` DECIMAL(5,2) DEFAULT NULL,
  `benchmark_1_year_returns` DECIMAL(5,2) DEFAULT NULL,
  `no_of_customers_assigned` INT(11) DEFAULT NULL,
  `rebalance_required` TINYINT(1) DEFAULT NULL,
  `rebalance_reqd_date` DATETIME DEFAULT NULL,
  `last_updated` DATETIME DEFAULT NULL,
  `date_created` DATETIME DEFAULT NULL,
  `start_current_period` DATETIME DEFAULT NULL,
  `status` TINYINT(1) DEFAULT NULL,
  `portfolio_value` DECIMAL(12,2) DEFAULT NULL,
  `last_updateon` DATETIME DEFAULT NULL,
  `actvity_type` VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (`portfolio_audit_id`)
);