CREATE TABLE `MMF_JobSchedule_Details` (                                                                                                                                                                                                                                                                                                               
    `Id` INT(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                
    `JobType` VARCHAR(45) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                  
    `Status` VARCHAR(45) DEFAULT 'STAGED',                                                                                                                                                                                                                                                                                                               
    `ScheduledDate` DATETIME DEFAULT NULL,                                                                                                                                                                                                                                                                                                               
    `MMFTransferDate` DATETIME DEFAULT NULL,                                                                                                                                                                                                                                                                                                             
    `LastUpdatedOn` DATETIME DEFAULT NULL,                                                                                                                                                                                                                                                                                                               
    KEY `Id` (`Id`)                                                                                                                                                                                                                                                                                                                                      
);
