INSERT INTO state_tb(stateName,stateCode)values('Andhra Pradesh','AP');
INSERT INTO state_tb(stateName,stateCode)values('Arunachal Pradesh','AR');
INSERT INTO state_tb(stateName,stateCode)values('Assam','AS');
INSERT INTO state_tb(stateName,stateCode)values('Bihar','BR');
INSERT INTO state_tb(stateName,stateCode)values('Chhattisgarh','CT');
INSERT INTO state_tb(stateName,stateCode)values('Goa','GA');
INSERT INTO state_tb(stateName,stateCode)values('Gujarat','GJ');
INSERT INTO state_tb(stateName,stateCode)values('Haryana','HR');
INSERT INTO state_tb(stateName,stateCode)values('Himachal Pradesh','HP');
INSERT INTO state_tb(stateName,stateCode)values('Jammu and Kashmir','JK');
INSERT INTO state_tb(stateName,stateCode)values('Jharkhand','JH');
INSERT INTO state_tb(stateName,stateCode)values('Karnataka','KA');
INSERT INTO state_tb(stateName,stateCode)values('Kerala','KL');
INSERT INTO state_tb(stateName,stateCode)values('Madhya Pradesh','MP');
INSERT INTO state_tb(stateName,stateCode)values('Maharashtra','MHP');
INSERT INTO state_tb(stateName,stateCode)values('Manipur','MN');
INSERT INTO state_tb(stateName,stateCode)values('Meghalaya','ML');
INSERT INTO state_tb(stateName,stateCode)values('Mizoram','MZ');
INSERT INTO state_tb(stateName,stateCode)values('Nagaland','NL');
INSERT INTO state_tb(stateName,stateCode)values('Orissa','OR');
INSERT INTO state_tb(stateName,stateCode)values('Punjab','PB');
INSERT INTO state_tb(stateName,stateCode)values('Rajasthan','RJ');
INSERT INTO state_tb(stateName,stateCode)values('Sikkim','SK');
INSERT INTO state_tb(stateName,stateCode)values('Tamil Nadu','TN');
INSERT INTO state_tb(stateName,stateCode)values('Telangana','TG');
INSERT INTO state_tb(stateName,stateCode)values('Tripura','TR');
INSERT INTO state_tb(stateName,stateCode)values('Uttar Pradesh','UP');
INSERT INTO state_tb(stateName,stateCode)values('Uttarakhand','UT');
INSERT INTO state_tb(stateName,stateCode)values('West Bengal','WB');
