package com.gtl.mmf.entity;
// Generated 14 Mar, 2016 6:04:12 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * AdminNotificationTb generated by hbm2java
 */
public class AdminNotificationTb implements java.io.Serializable {

    private Integer id;
    private String notificationStatus;
    private Integer statusCode;
    private Date notificationDate;
    private boolean notifyAdmin;
    private boolean adminViewed;

    public AdminNotificationTb() {
    }

    public AdminNotificationTb(String notificationStatus, Integer statusCode, Date notificationDate, boolean notifyAdmin, boolean adminViewed) {
        this.notificationStatus = notificationStatus;
        this.statusCode = statusCode;
        this.notificationDate = notificationDate;
        this.notifyAdmin = notifyAdmin;
        this.adminViewed = adminViewed;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public boolean isNotifyAdmin() {
        return this.notifyAdmin;
    }

    public void setNotifyAdmin(boolean notifyAdmin) {
        this.notifyAdmin = notifyAdmin;
    }

    public boolean isAdminViewed() {
        return this.adminViewed;
    }

    public void setAdminViewed(boolean adminViewed) {
        this.adminViewed = adminViewed;
    }

    public String getNotificationStatus() {
        return this.notificationStatus;
    }

    public void setNotificationStatus(String notificationStatus) {
        this.notificationStatus = notificationStatus;
    }

    public Date getNotificationDate() {
        return this.notificationDate;
    }

    public void setNotificationDate(Date notificationDate) {
        this.notificationDate = notificationDate;
    }

    public Integer getStatusCode() {
        return statusCode;
    }

    public void setStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
    }

}
