package com.gtl.mmf.entity;
// Generated Jul 13, 2015 10:58:18 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Advisorbucketwisepayouts generated by hbm2java
 */
public class Advisorbucketwisepayouts  implements java.io.Serializable {


     private Integer id;
     private MasterAdvisorTb masterAdvisorTb;
     private Promodefinitions promodefinitions;
     private BigDecimal mgntfee;
     private BigDecimal perffee;
     private BigDecimal mfCommission;
     private BigDecimal pfCommission;
     private BigDecimal mfPayout;
     private BigDecimal pfPayout;
     private Date dateAdded;

    public Advisorbucketwisepayouts() {
    }

    public Advisorbucketwisepayouts(MasterAdvisorTb masterAdvisorTb, Promodefinitions promodefinitions, BigDecimal mgntfee, BigDecimal perffee, BigDecimal mfCommission, BigDecimal pfCommission, BigDecimal mfPayout, BigDecimal pfPayout, Date dateAdded) {
       this.masterAdvisorTb = masterAdvisorTb;
       this.promodefinitions = promodefinitions;
       this.mgntfee = mgntfee;
       this.perffee = perffee;
       this.mfCommission = mfCommission;
       this.pfCommission = pfCommission;
       this.mfPayout = mfPayout;
       this.pfPayout = pfPayout;
       this.dateAdded = dateAdded;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MasterAdvisorTb getMasterAdvisorTb() {
        return this.masterAdvisorTb;
    }
    
    public void setMasterAdvisorTb(MasterAdvisorTb masterAdvisorTb) {
        this.masterAdvisorTb = masterAdvisorTb;
    }
    public Promodefinitions getPromodefinitions() {
        return this.promodefinitions;
    }
    
    public void setPromodefinitions(Promodefinitions promodefinitions) {
        this.promodefinitions = promodefinitions;
    }
    public BigDecimal getMgntfee() {
        return this.mgntfee;
    }
    
    public void setMgntfee(BigDecimal mgntfee) {
        this.mgntfee = mgntfee;
    }
    public BigDecimal getPerffee() {
        return this.perffee;
    }
    
    public void setPerffee(BigDecimal perffee) {
        this.perffee = perffee;
    }
    public BigDecimal getMfCommission() {
        return this.mfCommission;
    }
    
    public void setMfCommission(BigDecimal mfCommission) {
        this.mfCommission = mfCommission;
    }
    public BigDecimal getPfCommission() {
        return this.pfCommission;
    }
    
    public void setPfCommission(BigDecimal pfCommission) {
        this.pfCommission = pfCommission;
    }
    public BigDecimal getMfPayout() {
        return this.mfPayout;
    }
    
    public void setMfPayout(BigDecimal mfPayout) {
        this.mfPayout = mfPayout;
    }
    public BigDecimal getPfPayout() {
        return this.pfPayout;
    }
    
    public void setPfPayout(BigDecimal pfPayout) {
        this.pfPayout = pfPayout;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }




}


