package com.gtl.mmf.entity;
// Generated Dec 22, 2014 4:17:26 PM by Hibernate Tools 3.2.1.GA



/**
 * BankSubTypeTb generated by hbm2java
 */
public class BankSubTypeTb  implements java.io.Serializable {


     private int id;
     private Integer key;
     private String bankSubType;

    public BankSubTypeTb() {
    }

	
    public BankSubTypeTb(int id) {
        this.id = id;
    }
    public BankSubTypeTb(int id, Integer key, String bankSubType) {
       this.id = id;
       this.key = key;
       this.bankSubType = bankSubType;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getKey() {
        return this.key;
    }
    
    public void setKey(Integer key) {
        this.key = key;
    }
    public String getBankSubType() {
        return this.bankSubType;
    }
    
    public void setBankSubType(String bankSubType) {
        this.bankSubType = bankSubType;
    }




}


