package com.gtl.mmf.entity;
// Generated Feb 22, 2014 2:44:21 PM by Hibernate Tools 3.2.1.GA

/**
 * BrockerTb generated by hbm2java
 */
public class BrockerTb implements java.io.Serializable {

    private Integer id;
    private String name;

    public BrockerTb() {
    }

    public BrockerTb(String name) {
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
