package com.gtl.mmf.entity;
// Generated 5 Sep, 2016 5:47:09 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * CashTxnForTheDay generated by hbm2java
 */
public class CashTxnForTheDay implements java.io.Serializable {

    private Integer idCashTxn;
    private int customerId;
    private int customerPortfolioId;
    private Date datetime;
    private String securityName;
    private String venueCode;
    private String venueScriptcode;
    private Float units;
    private Float cashFlow;

    public CashTxnForTheDay() {
    }

    public CashTxnForTheDay(int customerId, int customerPortfolioId, Date datetime) {
        this.customerId = customerId;
        this.customerPortfolioId = customerPortfolioId;
        this.datetime = datetime;
    }

    public CashTxnForTheDay(int customerId, int customerPortfolioId, Date datetime, String securityName, String venueCode, String venueScriptcode, Float units, Float cashFlow) {
        this.customerId = customerId;
        this.customerPortfolioId = customerPortfolioId;
        this.datetime = datetime;
        this.securityName = securityName;
        this.venueCode = venueCode;
        this.venueScriptcode = venueScriptcode;
        this.units = units;
        this.cashFlow = cashFlow;
    }

    public Integer getIdCashTxn() {
        return this.idCashTxn;
    }

    public void setIdCashTxn(Integer idCashTxn) {
        this.idCashTxn = idCashTxn;
    }

    public int getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public int getCustomerPortfolioId() {
        return this.customerPortfolioId;
    }

    public void setCustomerPortfolioId(int customerPortfolioId) {
        this.customerPortfolioId = customerPortfolioId;
    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public String getSecurityName() {
        return this.securityName;
    }

    public void setSecurityName(String securityName) {
        this.securityName = securityName;
    }

    public String getVenueCode() {
        return this.venueCode;
    }

    public void setVenueCode(String venueCode) {
        this.venueCode = venueCode;
    }

    public String getVenueScriptcode() {
        return this.venueScriptcode;
    }

    public void setVenueScriptcode(String venueScriptcode) {
        this.venueScriptcode = venueScriptcode;
    }

    public Float getUnits() {
        return this.units;
    }

    public void setUnits(Float units) {
        this.units = units;
    }

    public Float getCashFlow() {
        return this.cashFlow;
    }

    public void setCashFlow(Float cashFlow) {
        this.cashFlow = cashFlow;
    }

}
