package com.gtl.mmf.entity;
// Generated 10 Apr, 2014 2:17:59 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * CustomerQuestionResponseSetTb generated by hbm2java
 */
public class CustomerQuestionResponseSetTb implements java.io.Serializable {

    private Integer responseSetId;
    private QuestionoptionsmasterTb questionoptionsmasterTb;
    private QuestionmasterTb questionmasterTb;
    private CustomerAdvisorMappingTb customerAdvisorMappingTb;
    private Date responseSetDate;
    private int optionValue;

    public CustomerQuestionResponseSetTb() {
    }

    public CustomerQuestionResponseSetTb(QuestionoptionsmasterTb questionoptionsmasterTb, QuestionmasterTb questionmasterTb, CustomerAdvisorMappingTb customerAdvisorMappingTb, Date responseSetDate, int optionValue) {
        this.questionoptionsmasterTb = questionoptionsmasterTb;
        this.questionmasterTb = questionmasterTb;
        this.customerAdvisorMappingTb = customerAdvisorMappingTb;
        this.responseSetDate = responseSetDate;
        this.optionValue = optionValue;
    }

    public Integer getResponseSetId() {
        return this.responseSetId;
    }

    public void setResponseSetId(Integer responseSetId) {
        this.responseSetId = responseSetId;
    }

    public QuestionoptionsmasterTb getQuestionoptionsmasterTb() {
        return this.questionoptionsmasterTb;
    }

    public void setQuestionoptionsmasterTb(QuestionoptionsmasterTb questionoptionsmasterTb) {
        this.questionoptionsmasterTb = questionoptionsmasterTb;
    }

    public QuestionmasterTb getQuestionmasterTb() {
        return this.questionmasterTb;
    }

    public void setQuestionmasterTb(QuestionmasterTb questionmasterTb) {
        this.questionmasterTb = questionmasterTb;
    }

    public CustomerAdvisorMappingTb getCustomerAdvisorMappingTb() {
        return this.customerAdvisorMappingTb;
    }

    public void setCustomerAdvisorMappingTb(CustomerAdvisorMappingTb customerAdvisorMappingTb) {
        this.customerAdvisorMappingTb = customerAdvisorMappingTb;
    }

    public Date getResponseSetDate() {
        return this.responseSetDate;
    }

    public void setResponseSetDate(Date responseSetDate) {
        this.responseSetDate = responseSetDate;
    }

    public int getOptionValue() {
        return this.optionValue;
    }

    public void setOptionValue(int optionValue) {
        this.optionValue = optionValue;
    }

}
