package com.gtl.mmf.entity;
// Generated Jul 13, 2015 10:58:18 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerAdvisorMappingTb generated by hbm2java
 */
public class CustomerAdvisorMappingTb  implements java.io.Serializable {


     private Integer relationId;
     private MasterAdvisorTb masterAdvisorTb;
     private Promodefinitions promodefinitions;
     private MasterCustomerTb masterCustomerTb;
     private short relationStatus;
     private Date statusDate;
     private Double allocatedFunds;
     private Double pendingFees;
     private Date contractStart;
     private Date contractEnd;
     private Boolean mgmtFeeTypeVariable;
     private Short mgmtFeeFreq;
     private BigDecimal perfFeePercent;
     private BigDecimal perfFeeThreshold;
     private Integer perfFeeFreq;
     private Short commentFreq;
     private Short ratingOverall;
     private Short ratingSubQuality;
     private Short ratingSubFreq;
     private Short ratingSubResponse;
     private Boolean advisorRequest;
     private BigDecimal managementFeeVariable;
     private Integer managementFeeFixed;
     private Integer durationCount;
     private Integer durationFrequencyMonth;
     private Integer noRelationStatus;
     private String customerReview;
     private Integer coomentFreequency;
     private Integer reviewFreq;
     private Date rateAdvisorLastDate;
     private Date rateAdvisorDate;
     private Date mgmtFeeLastCalculated;
     private Date perfFeeLastCalculated;
     private BigDecimal mgmtFeeAmt;
     private BigDecimal perfFeeAmt;
     private Boolean rateAdvisorFlag;
     private Boolean advisorViewed;
     private Boolean investorViewed;
     private Boolean rateAdvisorViewed;
     private Boolean contractTerminateStatus;
     private Date contractTerminateDate;
     private Set performancefeecalculations = new HashSet(0);
     private Set customerPerformanceFeeTbs = new HashSet(0);
     private Set customerQuestionResponseSetTbs = new HashSet(0);
     private Set customerManagementFeeTbs = new HashSet(0);
     private Set customerRiskProfileTbs = new HashSet(0);
     private Set customerPortfolioTbs = new HashSet(0);

    public CustomerAdvisorMappingTb() {
    }

	
    public CustomerAdvisorMappingTb(MasterAdvisorTb masterAdvisorTb, MasterCustomerTb masterCustomerTb, short relationStatus, Date statusDate) {
        this.masterAdvisorTb = masterAdvisorTb;
        this.masterCustomerTb = masterCustomerTb;
        this.relationStatus = relationStatus;
        this.statusDate = statusDate;
    }
    public CustomerAdvisorMappingTb(MasterAdvisorTb masterAdvisorTb, Promodefinitions promodefinitions, MasterCustomerTb masterCustomerTb, short relationStatus, Date statusDate, Double allocatedFunds, Double pendingFees, Date contractStart, Date contractEnd, Boolean mgmtFeeTypeVariable, Short mgmtFeeFreq, BigDecimal perfFeePercent, BigDecimal perfFeeThreshold, Integer perfFeeFreq, Short commentFreq, Short ratingOverall, Short ratingSubQuality, Short ratingSubFreq, Short ratingSubResponse, Boolean advisorRequest, BigDecimal managementFeeVariable, Integer managementFeeFixed, Integer durationCount, Integer durationFrequencyMonth, Integer noRelationStatus, String customerReview, Integer coomentFreequency, Integer reviewFreq, Date rateAdvisorLastDate, Date rateAdvisorDate, Date mgmtFeeLastCalculated, Date perfFeeLastCalculated, BigDecimal mgmtFeeAmt, BigDecimal perfFeeAmt, Boolean rateAdvisorFlag, Boolean advisorViewed, Boolean investorViewed, Boolean rateAdvisorViewed, Boolean contractTerminateStatus, Date contractTerminateDate, Set performancefeecalculations, Set customerPerformanceFeeTbs, Set customerQuestionResponseSetTbs, Set customerManagementFeeTbs, Set customerRiskProfileTbs, Set customerPortfolioTbs) {
       this.masterAdvisorTb = masterAdvisorTb;
       this.promodefinitions = promodefinitions;
       this.masterCustomerTb = masterCustomerTb;
       this.relationStatus = relationStatus;
       this.statusDate = statusDate;
       this.allocatedFunds = allocatedFunds;
       this.pendingFees = pendingFees;
       this.contractStart = contractStart;
       this.contractEnd = contractEnd;
       this.mgmtFeeTypeVariable = mgmtFeeTypeVariable;
       this.mgmtFeeFreq = mgmtFeeFreq;
       this.perfFeePercent = perfFeePercent;
       this.perfFeeThreshold = perfFeeThreshold;
       this.perfFeeFreq = perfFeeFreq;
       this.commentFreq = commentFreq;
       this.ratingOverall = ratingOverall;
       this.ratingSubQuality = ratingSubQuality;
       this.ratingSubFreq = ratingSubFreq;
       this.ratingSubResponse = ratingSubResponse;
       this.advisorRequest = advisorRequest;
       this.managementFeeVariable = managementFeeVariable;
       this.managementFeeFixed = managementFeeFixed;
       this.durationCount = durationCount;
       this.durationFrequencyMonth = durationFrequencyMonth;
       this.noRelationStatus = noRelationStatus;
       this.customerReview = customerReview;
       this.coomentFreequency = coomentFreequency;
       this.reviewFreq = reviewFreq;
       this.rateAdvisorLastDate = rateAdvisorLastDate;
       this.rateAdvisorDate = rateAdvisorDate;
       this.mgmtFeeLastCalculated = mgmtFeeLastCalculated;
       this.perfFeeLastCalculated = perfFeeLastCalculated;
       this.mgmtFeeAmt = mgmtFeeAmt;
       this.perfFeeAmt = perfFeeAmt;
       this.rateAdvisorFlag = rateAdvisorFlag;
       this.advisorViewed = advisorViewed;
       this.investorViewed = investorViewed;
       this.rateAdvisorViewed = rateAdvisorViewed;
       this.contractTerminateStatus = contractTerminateStatus;
       this.contractTerminateDate = contractTerminateDate;
       this.performancefeecalculations = performancefeecalculations;
       this.customerPerformanceFeeTbs = customerPerformanceFeeTbs;
       this.customerQuestionResponseSetTbs = customerQuestionResponseSetTbs;
       this.customerManagementFeeTbs = customerManagementFeeTbs;
       this.customerRiskProfileTbs = customerRiskProfileTbs;
       this.customerPortfolioTbs = customerPortfolioTbs;
    }
   
    public Integer getRelationId() {
        return this.relationId;
    }
    
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }
    public MasterAdvisorTb getMasterAdvisorTb() {
        return this.masterAdvisorTb;
    }
    
    public void setMasterAdvisorTb(MasterAdvisorTb masterAdvisorTb) {
        this.masterAdvisorTb = masterAdvisorTb;
    }
    public Promodefinitions getPromodefinitions() {
        return this.promodefinitions;
    }
    
    public void setPromodefinitions(Promodefinitions promodefinitions) {
        this.promodefinitions = promodefinitions;
    }
    public MasterCustomerTb getMasterCustomerTb() {
        return this.masterCustomerTb;
    }
    
    public void setMasterCustomerTb(MasterCustomerTb masterCustomerTb) {
        this.masterCustomerTb = masterCustomerTb;
    }
    public short getRelationStatus() {
        return this.relationStatus;
    }
    
    public void setRelationStatus(short relationStatus) {
        this.relationStatus = relationStatus;
    }
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }
    public Double getAllocatedFunds() {
        return this.allocatedFunds;
    }
    
    public void setAllocatedFunds(Double allocatedFunds) {
        this.allocatedFunds = allocatedFunds;
    }
    public Double getPendingFees() {
        return this.pendingFees;
    }
    
    public void setPendingFees(Double pendingFees) {
        this.pendingFees = pendingFees;
    }
    public Date getContractStart() {
        return this.contractStart;
    }
    
    public void setContractStart(Date contractStart) {
        this.contractStart = contractStart;
    }
    public Date getContractEnd() {
        return this.contractEnd;
    }
    
    public void setContractEnd(Date contractEnd) {
        this.contractEnd = contractEnd;
    }
    public Boolean getMgmtFeeTypeVariable() {
        return this.mgmtFeeTypeVariable;
    }
    
    public void setMgmtFeeTypeVariable(Boolean mgmtFeeTypeVariable) {
        this.mgmtFeeTypeVariable = mgmtFeeTypeVariable;
    }
    public Short getMgmtFeeFreq() {
        return this.mgmtFeeFreq;
    }
    
    public void setMgmtFeeFreq(Short mgmtFeeFreq) {
        this.mgmtFeeFreq = mgmtFeeFreq;
    }
    public BigDecimal getPerfFeePercent() {
        return this.perfFeePercent;
    }
    
    public void setPerfFeePercent(BigDecimal perfFeePercent) {
        this.perfFeePercent = perfFeePercent;
    }
    public BigDecimal getPerfFeeThreshold() {
        return this.perfFeeThreshold;
    }
    
    public void setPerfFeeThreshold(BigDecimal perfFeeThreshold) {
        this.perfFeeThreshold = perfFeeThreshold;
    }
    public Integer getPerfFeeFreq() {
        return this.perfFeeFreq;
    }
    
    public void setPerfFeeFreq(Integer perfFeeFreq) {
        this.perfFeeFreq = perfFeeFreq;
    }
    public Short getCommentFreq() {
        return this.commentFreq;
    }
    
    public void setCommentFreq(Short commentFreq) {
        this.commentFreq = commentFreq;
    }
    public Short getRatingOverall() {
        return this.ratingOverall;
    }
    
    public void setRatingOverall(Short ratingOverall) {
        this.ratingOverall = ratingOverall;
    }
    public Short getRatingSubQuality() {
        return this.ratingSubQuality;
    }
    
    public void setRatingSubQuality(Short ratingSubQuality) {
        this.ratingSubQuality = ratingSubQuality;
    }
    public Short getRatingSubFreq() {
        return this.ratingSubFreq;
    }
    
    public void setRatingSubFreq(Short ratingSubFreq) {
        this.ratingSubFreq = ratingSubFreq;
    }
    public Short getRatingSubResponse() {
        return this.ratingSubResponse;
    }
    
    public void setRatingSubResponse(Short ratingSubResponse) {
        this.ratingSubResponse = ratingSubResponse;
    }
    public Boolean getAdvisorRequest() {
        return this.advisorRequest;
    }
    
    public void setAdvisorRequest(Boolean advisorRequest) {
        this.advisorRequest = advisorRequest;
    }
    public BigDecimal getManagementFeeVariable() {
        return this.managementFeeVariable;
    }
    
    public void setManagementFeeVariable(BigDecimal managementFeeVariable) {
        this.managementFeeVariable = managementFeeVariable;
    }
    public Integer getManagementFeeFixed() {
        return this.managementFeeFixed;
    }
    
    public void setManagementFeeFixed(Integer managementFeeFixed) {
        this.managementFeeFixed = managementFeeFixed;
    }
    public Integer getDurationCount() {
        return this.durationCount;
    }
    
    public void setDurationCount(Integer durationCount) {
        this.durationCount = durationCount;
    }
    public Integer getDurationFrequencyMonth() {
        return this.durationFrequencyMonth;
    }
    
    public void setDurationFrequencyMonth(Integer durationFrequencyMonth) {
        this.durationFrequencyMonth = durationFrequencyMonth;
    }
    public Integer getNoRelationStatus() {
        return this.noRelationStatus;
    }
    
    public void setNoRelationStatus(Integer noRelationStatus) {
        this.noRelationStatus = noRelationStatus;
    }
    public String getCustomerReview() {
        return this.customerReview;
    }
    
    public void setCustomerReview(String customerReview) {
        this.customerReview = customerReview;
    }
    public Integer getCoomentFreequency() {
        return this.coomentFreequency;
    }
    
    public void setCoomentFreequency(Integer coomentFreequency) {
        this.coomentFreequency = coomentFreequency;
    }
    public Integer getReviewFreq() {
        return this.reviewFreq;
    }
    
    public void setReviewFreq(Integer reviewFreq) {
        this.reviewFreq = reviewFreq;
    }
    public Date getRateAdvisorLastDate() {
        return this.rateAdvisorLastDate;
    }
    
    public void setRateAdvisorLastDate(Date rateAdvisorLastDate) {
        this.rateAdvisorLastDate = rateAdvisorLastDate;
    }
    public Date getRateAdvisorDate() {
        return this.rateAdvisorDate;
    }
    
    public void setRateAdvisorDate(Date rateAdvisorDate) {
        this.rateAdvisorDate = rateAdvisorDate;
    }
    public Date getMgmtFeeLastCalculated() {
        return this.mgmtFeeLastCalculated;
    }
    
    public void setMgmtFeeLastCalculated(Date mgmtFeeLastCalculated) {
        this.mgmtFeeLastCalculated = mgmtFeeLastCalculated;
    }
    public Date getPerfFeeLastCalculated() {
        return this.perfFeeLastCalculated;
    }
    
    public void setPerfFeeLastCalculated(Date perfFeeLastCalculated) {
        this.perfFeeLastCalculated = perfFeeLastCalculated;
    }
    public BigDecimal getMgmtFeeAmt() {
        return this.mgmtFeeAmt;
    }
    
    public void setMgmtFeeAmt(BigDecimal mgmtFeeAmt) {
        this.mgmtFeeAmt = mgmtFeeAmt;
    }
    public BigDecimal getPerfFeeAmt() {
        return this.perfFeeAmt;
    }
    
    public void setPerfFeeAmt(BigDecimal perfFeeAmt) {
        this.perfFeeAmt = perfFeeAmt;
    }
    public Boolean getRateAdvisorFlag() {
        return this.rateAdvisorFlag;
    }
    
    public void setRateAdvisorFlag(Boolean rateAdvisorFlag) {
        this.rateAdvisorFlag = rateAdvisorFlag;
    }
    public Boolean getAdvisorViewed() {
        return this.advisorViewed;
    }
    
    public void setAdvisorViewed(Boolean advisorViewed) {
        this.advisorViewed = advisorViewed;
    }
    public Boolean getInvestorViewed() {
        return this.investorViewed;
    }
    
    public void setInvestorViewed(Boolean investorViewed) {
        this.investorViewed = investorViewed;
    }
    public Boolean getRateAdvisorViewed() {
        return this.rateAdvisorViewed;
    }
    
    public void setRateAdvisorViewed(Boolean rateAdvisorViewed) {
        this.rateAdvisorViewed = rateAdvisorViewed;
    }

    public Boolean getContractTerminateStatus() {
        return contractTerminateStatus;
    }

    public void setContractTerminateStatus(Boolean contractTerminateStatus) {
        this.contractTerminateStatus = contractTerminateStatus;
    }

    public Date getContractTerminateDate() {
        return contractTerminateDate;
    }

    public void setContractTerminateDate(Date contractTerminateDate) {
        this.contractTerminateDate = contractTerminateDate;
    }
    
    public Set getPerformancefeecalculations() {
        return this.performancefeecalculations;
    }
    
    public void setPerformancefeecalculations(Set performancefeecalculations) {
        this.performancefeecalculations = performancefeecalculations;
    }
    public Set getCustomerPerformanceFeeTbs() {
        return this.customerPerformanceFeeTbs;
    }
    
    public void setCustomerPerformanceFeeTbs(Set customerPerformanceFeeTbs) {
        this.customerPerformanceFeeTbs = customerPerformanceFeeTbs;
    }
    public Set getCustomerQuestionResponseSetTbs() {
        return this.customerQuestionResponseSetTbs;
    }
    
    public void setCustomerQuestionResponseSetTbs(Set customerQuestionResponseSetTbs) {
        this.customerQuestionResponseSetTbs = customerQuestionResponseSetTbs;
    }
    public Set getCustomerManagementFeeTbs() {
        return this.customerManagementFeeTbs;
    }
    
    public void setCustomerManagementFeeTbs(Set customerManagementFeeTbs) {
        this.customerManagementFeeTbs = customerManagementFeeTbs;
    }
    public Set getCustomerRiskProfileTbs() {
        return this.customerRiskProfileTbs;
    }
    
    public void setCustomerRiskProfileTbs(Set customerRiskProfileTbs) {
        this.customerRiskProfileTbs = customerRiskProfileTbs;
    }
    public Set getCustomerPortfolioTbs() {
        return this.customerPortfolioTbs;
    }
    
    public void setCustomerPortfolioTbs(Set customerPortfolioTbs) {
        this.customerPortfolioTbs = customerPortfolioTbs;
    }




}


