package com.gtl.mmf.entity;
// Generated Jul 1, 2016 4:15:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CustomerRiskProfileResultTb generated by hbm2java
 */
public class CustomerRiskProfileResultTb implements java.io.Serializable {

	private Integer responseSetId;
	private String customerRegistrationId;
	private Date dateTime;
	private Integer riskScore;
	private Integer riskProfileGroupId;
	private Integer riskProfileRecommemdedPortfolioId;

	public CustomerRiskProfileResultTb() {
	}

	public CustomerRiskProfileResultTb(String customerRegistrationId,
			Date dateTime, Integer riskScore, Integer riskProfileGroupId,
			Integer riskProfileRecommemdedPortfolioId) {
		this.customerRegistrationId = customerRegistrationId;
		this.dateTime = dateTime;
		this.riskScore = riskScore;
		this.riskProfileGroupId = riskProfileGroupId;
		this.riskProfileRecommemdedPortfolioId = riskProfileRecommemdedPortfolioId;
	}

	public Integer getResponseSetId() {
		return this.responseSetId;
	}

	public void setResponseSetId(Integer responseSetId) {
		this.responseSetId = responseSetId;
	}

	public String getCustomerRegistrationId() {
		return this.customerRegistrationId;
	}

	public void setCustomerRegistrationId(String customerRegistrationId) {
		this.customerRegistrationId = customerRegistrationId;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Integer getRiskScore() {
		return this.riskScore;
	}

	public void setRiskScore(Integer riskScore) {
		this.riskScore = riskScore;
	}

	public Integer getRiskProfileGroupId() {
		return this.riskProfileGroupId;
	}

	public void setRiskProfileGroupId(Integer riskProfileGroupId) {
		this.riskProfileGroupId = riskProfileGroupId;
	}

	public Integer getRiskProfileRecommemdedPortfolioId() {
		return this.riskProfileRecommemdedPortfolioId;
	}

	public void setRiskProfileRecommemdedPortfolioId(
			Integer riskProfileRecommemdedPortfolioId) {
		this.riskProfileRecommemdedPortfolioId = riskProfileRecommemdedPortfolioId;
	}

}
