package com.gtl.mmf.entity;
// Generated 26 Jun, 2014 9:27:49 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * CustomerDailyCashBalanceTb generated by hbm2java
 */
public class CustomerDailyCashBalanceTb implements java.io.Serializable {

    private Integer id;
    private MasterCustomerTb masterCustomerTb;
    private CustomerPortfolioTb customerPortfolioTb;
    private PortfolioTb portfolioTb;
    private String omsLoginId;
    private BigDecimal ledgerbalanec;
    private Date tradedate;
    private Date lastupdatedon;

    public CustomerDailyCashBalanceTb() {
    }

    public CustomerDailyCashBalanceTb(MasterCustomerTb masterCustomerTb, CustomerPortfolioTb customerPortfolioTb, PortfolioTb portfolioTb) {
        this.masterCustomerTb = masterCustomerTb;
        this.customerPortfolioTb = customerPortfolioTb;
        this.portfolioTb = portfolioTb;
    }

    public CustomerDailyCashBalanceTb(MasterCustomerTb masterCustomerTb, CustomerPortfolioTb customerPortfolioTb, PortfolioTb portfolioTb, String omsLoginId, BigDecimal ledgerbalanec, Date tradedate, Date lastupdatedon) {
        this.masterCustomerTb = masterCustomerTb;
        this.customerPortfolioTb = customerPortfolioTb;
        this.portfolioTb = portfolioTb;
        this.omsLoginId = omsLoginId;
        this.ledgerbalanec = ledgerbalanec;
        this.tradedate = tradedate;
        this.lastupdatedon = lastupdatedon;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public MasterCustomerTb getMasterCustomerTb() {
        return this.masterCustomerTb;
    }

    public void setMasterCustomerTb(MasterCustomerTb masterCustomerTb) {
        this.masterCustomerTb = masterCustomerTb;
    }

    public CustomerPortfolioTb getCustomerPortfolioTb() {
        return this.customerPortfolioTb;
    }

    public void setCustomerPortfolioTb(CustomerPortfolioTb customerPortfolioTb) {
        this.customerPortfolioTb = customerPortfolioTb;
    }

    public PortfolioTb getPortfolioTb() {
        return this.portfolioTb;
    }

    public void setPortfolioTb(PortfolioTb portfolioTb) {
        this.portfolioTb = portfolioTb;
    }

    public String getOmsLoginId() {
        return this.omsLoginId;
    }

    public void setOmsLoginId(String omsLoginId) {
        this.omsLoginId = omsLoginId;
    }

    public BigDecimal getLedgerbalanec() {
        return this.ledgerbalanec;
    }

    public void setLedgerbalanec(BigDecimal ledgerbalanec) {
        this.ledgerbalanec = ledgerbalanec;
    }

    public Date getTradedate() {
        return this.tradedate;
    }

    public void setTradedate(Date tradedate) {
        this.tradedate = tradedate;
    }

    public Date getLastupdatedon() {
        return this.lastupdatedon;
    }

    public void setLastupdatedon(Date lastupdatedon) {
        this.lastupdatedon = lastupdatedon;
    }

}
