package com.gtl.mmf.entity;
// Generated 25 Aug, 2016 4:15:39 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * CustomerTransactionAcquisitionDetailsTb generated by hbm2java
 */
public class CustomerTransactionAcquisitionDetailsTb  implements java.io.Serializable {


     private Integer customerTransactionAcquisitionId;
     private int customerId;
     private int portfolioId;
     private int customerPortfolioId;
     private Long orderId;
     private String securityId;
     private String venueCode;
     private String venueScriptCode;
     private BigDecimal transactionUnit;
     private BigDecimal boughtOrSoldPrice;
     private BigDecimal acquisitionCost;
     private Date transactionDate;
     private String omsId;

    public CustomerTransactionAcquisitionDetailsTb() {
    }

	
    public CustomerTransactionAcquisitionDetailsTb(int customerId, int portfolioId, int customerPortfolioId, String securityId, BigDecimal transactionUnit, BigDecimal boughtOrSoldPrice, BigDecimal acquisitionCost, Date transactionDate, String omsId) {
        this.customerId = customerId;
        this.portfolioId = portfolioId;
        this.customerPortfolioId = customerPortfolioId;
        this.securityId = securityId;
        this.transactionUnit = transactionUnit;
        this.boughtOrSoldPrice = boughtOrSoldPrice;
        this.acquisitionCost = acquisitionCost;
        this.transactionDate = transactionDate;
        this.omsId = omsId;
    }
    public CustomerTransactionAcquisitionDetailsTb(int customerId, int portfolioId, int customerPortfolioId, Long orderId, String securityId, String venueCode, String venueScriptCode, BigDecimal transactionUnit, BigDecimal boughtOrSoldPrice, BigDecimal acquisitionCost, Date transactionDate, String omsId) {
       this.customerId = customerId;
       this.portfolioId = portfolioId;
       this.customerPortfolioId = customerPortfolioId;
       this.orderId = orderId;
       this.securityId = securityId;
       this.venueCode = venueCode;
       this.venueScriptCode = venueScriptCode;
       this.transactionUnit = transactionUnit;
       this.boughtOrSoldPrice = boughtOrSoldPrice;
       this.acquisitionCost = acquisitionCost;
       this.transactionDate = transactionDate;
       this.omsId = omsId;
    }
   
    public Integer getCustomerTransactionAcquisitionId() {
        return this.customerTransactionAcquisitionId;
    }
    
    public void setCustomerTransactionAcquisitionId(Integer customerTransactionAcquisitionId) {
        this.customerTransactionAcquisitionId = customerTransactionAcquisitionId;
    }
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    public int getPortfolioId() {
        return this.portfolioId;
    }
    
    public void setPortfolioId(int portfolioId) {
        this.portfolioId = portfolioId;
    }
    public int getCustomerPortfolioId() {
        return this.customerPortfolioId;
    }
    
    public void setCustomerPortfolioId(int customerPortfolioId) {
        this.customerPortfolioId = customerPortfolioId;
    }
    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
    public String getSecurityId() {
        return this.securityId;
    }
    
    public void setSecurityId(String securityId) {
        this.securityId = securityId;
    }
    public String getVenueCode() {
        return this.venueCode;
    }
    
    public void setVenueCode(String venueCode) {
        this.venueCode = venueCode;
    }
    public String getVenueScriptCode() {
        return this.venueScriptCode;
    }
    
    public void setVenueScriptCode(String venueScriptCode) {
        this.venueScriptCode = venueScriptCode;
    }
    public BigDecimal getTransactionUnit() {
        return this.transactionUnit;
    }
    
    public void setTransactionUnit(BigDecimal transactionUnit) {
        this.transactionUnit = transactionUnit;
    }
    public BigDecimal getBoughtOrSoldPrice() {
        return this.boughtOrSoldPrice;
    }
    
    public void setBoughtOrSoldPrice(BigDecimal boughtOrSoldPrice) {
        this.boughtOrSoldPrice = boughtOrSoldPrice;
    }
    public BigDecimal getAcquisitionCost() {
        return this.acquisitionCost;
    }
    
    public void setAcquisitionCost(BigDecimal acquisitionCost) {
        this.acquisitionCost = acquisitionCost;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public String getOmsId() {
        return this.omsId;
    }
    
    public void setOmsId(String omsId) {
        this.omsId = omsId;
    }




}


