package com.gtl.mmf.entity;
// Generated 5 Dec, 2015 1:20:59 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.type.FloatType;

/**
 * CustomerPortfolioSecuritiesTb generated by hbm2java
 */
public class CustomerPortfolioSecuritiesTb implements java.io.Serializable {

    private Integer customerPortfolioSecuritiesId;
    private CustomerPortfolioDetailsTb customerPortfolioDetailsTb;
    private PortfolioDetailsTb portfolioDetailsTb;
    private PortfolioSecuritiesTb portfolioSecuritiesTb;
    private MasterAssetTb masterAssetTb;
    private CustomerPortfolioTb customerPortfolioTb;
    private PortfolioTb portfolioTb;
    private String securityId;
    private Integer currentUnits;
    private Float currentPrice;
    private Float currentValue;
    private Float currentWeight;
    private BigDecimal exeUnits;
    private Float recommentedPrice;
    private Float avgAcquisitionPrice;
    private Float initialValue;
    private Float initialWeight;
    private Float requiredValue;
    private BigDecimal requiredUnits;
    private Boolean rebalanceRequired;
    private Date rebalanceReqdDate;
    private Float newAllocation;
    private String securityDescription;
    private Integer newToleranceNegativeRange;
    private Integer newTolerancePositiveRange;
    private String venueCode;
    private String venueScriptCode;
    private String securityCode;
    private Boolean status;
    private String instrumentType;
    private Date expirationDate;
    private BigDecimal strikePrice;
    private BigDecimal yesterDayUnitCount;
    private Float lastBoughtPrice;
    private Float averageRate;
    private BigDecimal blockCount;
    private Set customerPortfolioSecuritiesPerformanceTbs = new HashSet(0);

    public CustomerPortfolioSecuritiesTb() {
        lastBoughtPrice = FloatType.ZERO;
    }

    public CustomerPortfolioSecuritiesTb(CustomerPortfolioDetailsTb customerPortfolioDetailsTb, PortfolioDetailsTb portfolioDetailsTb, PortfolioSecuritiesTb portfolioSecuritiesTb, MasterAssetTb masterAssetTb, CustomerPortfolioTb customerPortfolioTb, PortfolioTb portfolioTb, String securityId) {
        this.customerPortfolioDetailsTb = customerPortfolioDetailsTb;
        this.portfolioDetailsTb = portfolioDetailsTb;
        this.portfolioSecuritiesTb = portfolioSecuritiesTb;
        this.masterAssetTb = masterAssetTb;
        this.customerPortfolioTb = customerPortfolioTb;
        this.portfolioTb = portfolioTb;
        this.securityId = securityId;
    }

    public CustomerPortfolioSecuritiesTb(CustomerPortfolioDetailsTb customerPortfolioDetailsTb, PortfolioDetailsTb portfolioDetailsTb, PortfolioSecuritiesTb portfolioSecuritiesTb, MasterAssetTb masterAssetTb, CustomerPortfolioTb customerPortfolioTb, PortfolioTb portfolioTb, String securityId, Integer currentUnits, Float currentPrice, Float currentValue, Float currentWeight, BigDecimal exeUnits, Float recommentedPrice, Float avgAcquisitionPrice, Float initialValue, Float initialWeight, Float requiredValue, BigDecimal requiredUnits, Boolean rebalanceRequired, Date rebalanceReqdDate, Float newAllocation, String securityDescription, Integer newToleranceNegativeRange, Integer newTolerancePositiveRange, String venueCode, String venueScriptCode, String securityCode, Boolean status, String instrumentType, Date expirationDate, BigDecimal strikePrice, BigDecimal yesterDayUnitCount, Float lastBoughtPrice, Float averageRate, BigDecimal blockCount, Set customerPortfolioSecuritiesPerformanceTbs) {
        this.customerPortfolioDetailsTb = customerPortfolioDetailsTb;
        this.portfolioDetailsTb = portfolioDetailsTb;
        this.portfolioSecuritiesTb = portfolioSecuritiesTb;
        this.masterAssetTb = masterAssetTb;
        this.customerPortfolioTb = customerPortfolioTb;
        this.portfolioTb = portfolioTb;
        this.securityId = securityId;
        this.currentUnits = currentUnits;
        this.currentPrice = currentPrice;
        this.currentValue = currentValue;
        this.currentWeight = currentWeight;
        this.exeUnits = exeUnits;
        this.recommentedPrice = recommentedPrice;
        this.avgAcquisitionPrice = avgAcquisitionPrice;
        this.initialValue = initialValue;
        this.initialWeight = initialWeight;
        this.requiredValue = requiredValue;
        this.requiredUnits = requiredUnits;
        this.rebalanceRequired = rebalanceRequired;
        this.rebalanceReqdDate = rebalanceReqdDate;
        this.newAllocation = newAllocation;
        this.securityDescription = securityDescription;
        this.newToleranceNegativeRange = newToleranceNegativeRange;
        this.newTolerancePositiveRange = newTolerancePositiveRange;
        this.venueCode = venueCode;
        this.venueScriptCode = venueScriptCode;
        this.securityCode = securityCode;
        this.status = status;
        this.instrumentType = instrumentType;
        this.expirationDate = expirationDate;
        this.strikePrice = strikePrice;
        this.yesterDayUnitCount = yesterDayUnitCount;
        this.lastBoughtPrice = lastBoughtPrice;
        this.averageRate = averageRate;
        this.blockCount = blockCount;
        this.customerPortfolioSecuritiesPerformanceTbs = customerPortfolioSecuritiesPerformanceTbs;
    }

    public Integer getCustomerPortfolioSecuritiesId() {
        return this.customerPortfolioSecuritiesId;
    }

    public void setCustomerPortfolioSecuritiesId(Integer customerPortfolioSecuritiesId) {
        this.customerPortfolioSecuritiesId = customerPortfolioSecuritiesId;
    }

    public CustomerPortfolioDetailsTb getCustomerPortfolioDetailsTb() {
        return this.customerPortfolioDetailsTb;
    }

    public void setCustomerPortfolioDetailsTb(CustomerPortfolioDetailsTb customerPortfolioDetailsTb) {
        this.customerPortfolioDetailsTb = customerPortfolioDetailsTb;
    }

    public PortfolioDetailsTb getPortfolioDetailsTb() {
        return this.portfolioDetailsTb;
    }

    public void setPortfolioDetailsTb(PortfolioDetailsTb portfolioDetailsTb) {
        this.portfolioDetailsTb = portfolioDetailsTb;
    }

    public PortfolioSecuritiesTb getPortfolioSecuritiesTb() {
        return this.portfolioSecuritiesTb;
    }

    public void setPortfolioSecuritiesTb(PortfolioSecuritiesTb portfolioSecuritiesTb) {
        this.portfolioSecuritiesTb = portfolioSecuritiesTb;
    }

    public MasterAssetTb getMasterAssetTb() {
        return this.masterAssetTb;
    }

    public void setMasterAssetTb(MasterAssetTb masterAssetTb) {
        this.masterAssetTb = masterAssetTb;
    }

    public CustomerPortfolioTb getCustomerPortfolioTb() {
        return this.customerPortfolioTb;
    }

    public void setCustomerPortfolioTb(CustomerPortfolioTb customerPortfolioTb) {
        this.customerPortfolioTb = customerPortfolioTb;
    }

    public PortfolioTb getPortfolioTb() {
        return this.portfolioTb;
    }

    public void setPortfolioTb(PortfolioTb portfolioTb) {
        this.portfolioTb = portfolioTb;
    }

    public String getSecurityId() {
        return this.securityId;
    }

    public void setSecurityId(String securityId) {
        this.securityId = securityId;
    }

    public Integer getCurrentUnits() {
        return this.currentUnits;
    }

    public void setCurrentUnits(Integer currentUnits) {
        this.currentUnits = currentUnits;
    }

    public Float getCurrentPrice() {
        return this.currentPrice;
    }

    public void setCurrentPrice(Float currentPrice) {
        this.currentPrice = currentPrice;
    }

    public Float getCurrentValue() {
        return this.currentValue;
    }

    public void setCurrentValue(Float currentValue) {
        this.currentValue = currentValue;
    }

    public Float getCurrentWeight() {
        return this.currentWeight;
    }

    public void setCurrentWeight(Float currentWeight) {
        this.currentWeight = currentWeight;
    }

    public BigDecimal getExeUnits() {
        return this.exeUnits;
    }

    public void setExeUnits(BigDecimal exeUnits) {
        this.exeUnits = exeUnits;
    }

    public Float getRecommentedPrice() {
        return this.recommentedPrice;
    }

    public void setRecommentedPrice(Float recommentedPrice) {
        this.recommentedPrice = recommentedPrice;
    }

    public Float getAvgAcquisitionPrice() {
        return this.avgAcquisitionPrice;
    }

    public void setAvgAcquisitionPrice(Float avgAcquisitionPrice) {
        this.avgAcquisitionPrice = avgAcquisitionPrice;
    }

    public Float getInitialValue() {
        return this.initialValue;
    }

    public void setInitialValue(Float initialValue) {
        this.initialValue = initialValue;
    }

    public Float getInitialWeight() {
        return this.initialWeight;
    }

    public void setInitialWeight(Float initialWeight) {
        this.initialWeight = initialWeight;
    }

    public Float getRequiredValue() {
        return this.requiredValue;
    }

    public void setRequiredValue(Float requiredValue) {
        this.requiredValue = requiredValue;
    }

    public BigDecimal getRequiredUnits() {
        return this.requiredUnits;
    }

    public void setRequiredUnits(BigDecimal requiredUnits) {
        this.requiredUnits = requiredUnits;
    }

    public Boolean getRebalanceRequired() {
        return this.rebalanceRequired;
    }

    public void setRebalanceRequired(Boolean rebalanceRequired) {
        this.rebalanceRequired = rebalanceRequired;
    }

    public Date getRebalanceReqdDate() {
        return this.rebalanceReqdDate;
    }

    public void setRebalanceReqdDate(Date rebalanceReqdDate) {
        this.rebalanceReqdDate = rebalanceReqdDate;
    }

    public Float getNewAllocation() {
        return this.newAllocation;
    }

    public void setNewAllocation(Float newAllocation) {
        this.newAllocation = newAllocation;
    }

    public String getSecurityDescription() {
        return this.securityDescription;
    }

    public void setSecurityDescription(String securityDescription) {
        this.securityDescription = securityDescription;
    }

    public Integer getNewToleranceNegativeRange() {
        return this.newToleranceNegativeRange;
    }

    public void setNewToleranceNegativeRange(Integer newToleranceNegativeRange) {
        this.newToleranceNegativeRange = newToleranceNegativeRange;
    }

    public Integer getNewTolerancePositiveRange() {
        return this.newTolerancePositiveRange;
    }

    public void setNewTolerancePositiveRange(Integer newTolerancePositiveRange) {
        this.newTolerancePositiveRange = newTolerancePositiveRange;
    }

    public String getVenueCode() {
        return this.venueCode;
    }

    public void setVenueCode(String venueCode) {
        this.venueCode = venueCode;
    }

    public String getVenueScriptCode() {
        return this.venueScriptCode;
    }

    public void setVenueScriptCode(String venueScriptCode) {
        this.venueScriptCode = venueScriptCode;
    }

    public String getSecurityCode() {
        return this.securityCode;
    }

    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getInstrumentType() {
        return this.instrumentType;
    }

    public void setInstrumentType(String instrumentType) {
        this.instrumentType = instrumentType;
    }

    public Date getExpirationDate() {
        return this.expirationDate;
    }

    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    public BigDecimal getStrikePrice() {
        return this.strikePrice;
    }

    public void setStrikePrice(BigDecimal strikePrice) {
        this.strikePrice = strikePrice;
    }

    public BigDecimal getYesterDayUnitCount() {
        return this.yesterDayUnitCount;
    }

    public void setYesterDayUnitCount(BigDecimal yesterDayUnitCount) {
        this.yesterDayUnitCount = yesterDayUnitCount;
    }

    public Float getLastBoughtPrice() {
        return lastBoughtPrice;
    }

    public void setLastBoughtPrice(Float lastBoughtPrice) {
        this.lastBoughtPrice = lastBoughtPrice;
    }

    public Float getAverageRate() {
        return this.averageRate;
    }

    public void setAverageRate(Float averageRate) {
        this.averageRate = averageRate;
    }

    public BigDecimal getBlockCount() {
        return blockCount;
    }

    public void setBlockCount(BigDecimal blockCount) {
        this.blockCount = blockCount;
    }

    public Set getCustomerPortfolioSecuritiesPerformanceTbs() {
        return this.customerPortfolioSecuritiesPerformanceTbs;
    }

    public void setCustomerPortfolioSecuritiesPerformanceTbs(Set customerPortfolioSecuritiesPerformanceTbs) {
        this.customerPortfolioSecuritiesPerformanceTbs = customerPortfolioSecuritiesPerformanceTbs;
    }

}
