package com.gtl.mmf.entity;
// Generated 5 Sep, 2016 5:47:09 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerPortfolioTb generated by hbm2java
 */
public class CustomerPortfolioTb implements java.io.Serializable {

    private Integer customerPortfolioId;
    private MasterAdvisorTb masterAdvisorTb;
    private MasterCustomerTb masterCustomerTb;
    private CustomerAdvisorMappingTb customerAdvisorMappingTb;
    private PortfolioTb portfolioTb;
    private String omsLoginId;
    private Float currentValue;
    private Float portfolio90DayReturns;
    private Float portfolio1YearReturns;
    private String adviserComment;
    private String customerComment;
    private Integer outperformance;
    private BigDecimal advisorPortfolioStartValue;
    private BigDecimal benchmarkStartValue;
    private BigDecimal advisorPortfolioReturnsFromStart;
    private BigDecimal benchmarkReturnsFromStart;
    private Boolean rebalanceRequired;
    private Date rebalanceReqdDate;
    private Date lastUpdated;
    private Boolean status;
    private Float portfolioValue;
    private Integer commentFreq;
    private Boolean noRebalanceStatus;
    private Float cashAmount;
    private Boolean portfolioModified;
    private Date lastExecutionUpdate;
    private boolean isFirstDayPerfmanceCalc;
    private Date portfolioAssigned;
    private Boolean rebalanceViewed;
    private Boolean portfolioChangeViewed;
    private BigDecimal benchmarkUnit;
    private Double allocatedFund;
    private String venueName;
    private Boolean cashFlowDflag;
    private BigDecimal cashFlow;
    private Float buyingPower;
    private Float recomendedCashBal;
    private Float blockedCash;
    private Float tempBlockedCash;
    private Float blockedCount;
    private Float tempBlockedCount;
    private String portfolioStatus;
    private Set customerPortfolioDetailsTbs = new HashSet(0);
    private Set customerPortfolioLogTbs = new HashSet(0);
    private Set customerPortfolioDetailsPerformanceTbs = new HashSet(0);
    private Set customerPortfolioPerformanceTbs = new HashSet(0);
    private Set addRedeemLogTbs = new HashSet(0);
    private Set customerPortfolioSecuritiesPerformanceTbs = new HashSet(0);
    private Set customerDailyCashBalanceTbs = new HashSet(0);
    private Set recomendedCustomerPortfolioSecuritiesTbs = new HashSet(0);
    private Set recomendedCustomerPortfolioPerformanceTbs = new HashSet(0);
    private Set customerPortfolioSecuritiesTbs = new HashSet(0);

    public CustomerPortfolioTb() {
    }

    public CustomerPortfolioTb(MasterAdvisorTb masterAdvisorTb, MasterCustomerTb masterCustomerTb, CustomerAdvisorMappingTb customerAdvisorMappingTb, PortfolioTb portfolioTb, boolean isFirstDayPerfmanceCalc) {
        this.masterAdvisorTb = masterAdvisorTb;
        this.masterCustomerTb = masterCustomerTb;
        this.customerAdvisorMappingTb = customerAdvisorMappingTb;
        this.portfolioTb = portfolioTb;
        this.isFirstDayPerfmanceCalc = isFirstDayPerfmanceCalc;
    }

    public CustomerPortfolioTb(MasterAdvisorTb masterAdvisorTb, MasterCustomerTb masterCustomerTb, CustomerAdvisorMappingTb customerAdvisorMappingTb, PortfolioTb portfolioTb, String omsLoginId, Float currentValue, Float portfolio90DayReturns, Float portfolio1YearReturns, String adviserComment, String customerComment, Integer outperformance, BigDecimal advisorPortfolioStartValue, BigDecimal benchmarkStartValue, BigDecimal advisorPortfolioReturnsFromStart, BigDecimal benchmarkReturnsFromStart, Boolean rebalanceRequired, Date rebalanceReqdDate, Date lastUpdated, Boolean status, Float portfolioValue, Integer commentFreq, Boolean noRebalanceStatus, Float cashAmount, Boolean portfolioModified, Date lastExecutionUpdate, boolean isFirstDayPerfmanceCalc, Date portfolioAssigned, Boolean rebalanceViewed, Boolean portfolioChangeViewed, BigDecimal benchmarkUnit, Double allocatedFund, String venueName, Boolean cashFlowDflag, BigDecimal cashFlow, Float buyingPower, Float recomendedCashBal, Float blockedCash, Float tempBlockedCash, Float blockedCount, Float tempBlockedCount, String portfolioStatus, Set customerPortfolioDetailsTbs, Set customerPortfolioLogTbs, Set customerPortfolioDetailsPerformanceTbs, Set customerPortfolioPerformanceTbs, Set addRedeemLogTbs, Set customerPortfolioSecuritiesPerformanceTbs, Set customerDailyCashBalanceTbs, Set recomendedCustomerPortfolioSecuritiesTbs, Set recomendedCustomerPortfolioPerformanceTbs, Set customerPortfolioSecuritiesTbs) {
        this.masterAdvisorTb = masterAdvisorTb;
        this.masterCustomerTb = masterCustomerTb;
        this.customerAdvisorMappingTb = customerAdvisorMappingTb;
        this.portfolioTb = portfolioTb;
        this.omsLoginId = omsLoginId;
        this.currentValue = currentValue;
        this.portfolio90DayReturns = portfolio90DayReturns;
        this.portfolio1YearReturns = portfolio1YearReturns;
        this.adviserComment = adviserComment;
        this.customerComment = customerComment;
        this.outperformance = outperformance;
        this.advisorPortfolioStartValue = advisorPortfolioStartValue;
        this.benchmarkStartValue = benchmarkStartValue;
        this.advisorPortfolioReturnsFromStart = advisorPortfolioReturnsFromStart;
        this.benchmarkReturnsFromStart = benchmarkReturnsFromStart;
        this.rebalanceRequired = rebalanceRequired;
        this.rebalanceReqdDate = rebalanceReqdDate;
        this.lastUpdated = lastUpdated;
        this.status = status;
        this.portfolioValue = portfolioValue;
        this.commentFreq = commentFreq;
        this.noRebalanceStatus = noRebalanceStatus;
        this.cashAmount = cashAmount;
        this.portfolioModified = portfolioModified;
        this.lastExecutionUpdate = lastExecutionUpdate;
        this.isFirstDayPerfmanceCalc = isFirstDayPerfmanceCalc;
        this.portfolioAssigned = portfolioAssigned;
        this.rebalanceViewed = rebalanceViewed;
        this.portfolioChangeViewed = portfolioChangeViewed;
        this.benchmarkUnit = benchmarkUnit;
        this.allocatedFund = allocatedFund;
        this.venueName = venueName;
        this.cashFlowDflag = cashFlowDflag;
        this.cashFlow = cashFlow;
        this.buyingPower = buyingPower;
        this.recomendedCashBal = recomendedCashBal;
        this.blockedCash = blockedCash;
        this.tempBlockedCash = tempBlockedCash;
        this.blockedCount = blockedCount;
        this.tempBlockedCount = tempBlockedCount;
        this.portfolioStatus = portfolioStatus;
        this.customerPortfolioDetailsTbs = customerPortfolioDetailsTbs;
        this.customerPortfolioLogTbs = customerPortfolioLogTbs;
        this.customerPortfolioDetailsPerformanceTbs = customerPortfolioDetailsPerformanceTbs;
        this.customerPortfolioPerformanceTbs = customerPortfolioPerformanceTbs;
        this.addRedeemLogTbs = addRedeemLogTbs;
        this.customerPortfolioSecuritiesPerformanceTbs = customerPortfolioSecuritiesPerformanceTbs;
        this.customerDailyCashBalanceTbs = customerDailyCashBalanceTbs;
        this.recomendedCustomerPortfolioSecuritiesTbs = recomendedCustomerPortfolioSecuritiesTbs;
        this.recomendedCustomerPortfolioPerformanceTbs = recomendedCustomerPortfolioPerformanceTbs;
        this.customerPortfolioSecuritiesTbs = customerPortfolioSecuritiesTbs;
    }

    public Integer getCustomerPortfolioId() {
        return this.customerPortfolioId;
    }

    public void setCustomerPortfolioId(Integer customerPortfolioId) {
        this.customerPortfolioId = customerPortfolioId;
    }

    public MasterAdvisorTb getMasterAdvisorTb() {
        return this.masterAdvisorTb;
    }

    public void setMasterAdvisorTb(MasterAdvisorTb masterAdvisorTb) {
        this.masterAdvisorTb = masterAdvisorTb;
    }

    public MasterCustomerTb getMasterCustomerTb() {
        return this.masterCustomerTb;
    }

    public void setMasterCustomerTb(MasterCustomerTb masterCustomerTb) {
        this.masterCustomerTb = masterCustomerTb;
    }

    public CustomerAdvisorMappingTb getCustomerAdvisorMappingTb() {
        return this.customerAdvisorMappingTb;
    }

    public void setCustomerAdvisorMappingTb(CustomerAdvisorMappingTb customerAdvisorMappingTb) {
        this.customerAdvisorMappingTb = customerAdvisorMappingTb;
    }

    public PortfolioTb getPortfolioTb() {
        return this.portfolioTb;
    }

    public void setPortfolioTb(PortfolioTb portfolioTb) {
        this.portfolioTb = portfolioTb;
    }

    public String getOmsLoginId() {
        return this.omsLoginId;
    }

    public void setOmsLoginId(String omsLoginId) {
        this.omsLoginId = omsLoginId;
    }

    public Float getCurrentValue() {
        return this.currentValue;
    }

    public void setCurrentValue(Float currentValue) {
        this.currentValue = currentValue;
    }

    public Float getPortfolio90DayReturns() {
        return this.portfolio90DayReturns;
    }

    public void setPortfolio90DayReturns(Float portfolio90DayReturns) {
        this.portfolio90DayReturns = portfolio90DayReturns;
    }

    public Float getPortfolio1YearReturns() {
        return this.portfolio1YearReturns;
    }

    public void setPortfolio1YearReturns(Float portfolio1YearReturns) {
        this.portfolio1YearReturns = portfolio1YearReturns;
    }

    public String getAdviserComment() {
        return this.adviserComment;
    }

    public void setAdviserComment(String adviserComment) {
        this.adviserComment = adviserComment;
    }

    public String getCustomerComment() {
        return this.customerComment;
    }

    public void setCustomerComment(String customerComment) {
        this.customerComment = customerComment;
    }

    public Integer getOutperformance() {
        return this.outperformance;
    }

    public void setOutperformance(Integer outperformance) {
        this.outperformance = outperformance;
    }

    public BigDecimal getAdvisorPortfolioStartValue() {
        return this.advisorPortfolioStartValue;
    }

    public void setAdvisorPortfolioStartValue(BigDecimal advisorPortfolioStartValue) {
        this.advisorPortfolioStartValue = advisorPortfolioStartValue;
    }

    public BigDecimal getBenchmarkStartValue() {
        return this.benchmarkStartValue;
    }

    public void setBenchmarkStartValue(BigDecimal benchmarkStartValue) {
        this.benchmarkStartValue = benchmarkStartValue;
    }

    public BigDecimal getAdvisorPortfolioReturnsFromStart() {
        return this.advisorPortfolioReturnsFromStart;
    }

    public void setAdvisorPortfolioReturnsFromStart(BigDecimal advisorPortfolioReturnsFromStart) {
        this.advisorPortfolioReturnsFromStart = advisorPortfolioReturnsFromStart;
    }

    public BigDecimal getBenchmarkReturnsFromStart() {
        return this.benchmarkReturnsFromStart;
    }

    public void setBenchmarkReturnsFromStart(BigDecimal benchmarkReturnsFromStart) {
        this.benchmarkReturnsFromStart = benchmarkReturnsFromStart;
    }

    public Boolean getRebalanceRequired() {
        return this.rebalanceRequired;
    }

    public void setRebalanceRequired(Boolean rebalanceRequired) {
        this.rebalanceRequired = rebalanceRequired;
    }

    public Date getRebalanceReqdDate() {
        return this.rebalanceReqdDate;
    }

    public void setRebalanceReqdDate(Date rebalanceReqdDate) {
        this.rebalanceReqdDate = rebalanceReqdDate;
    }

    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Float getPortfolioValue() {
        return this.portfolioValue;
    }

    public void setPortfolioValue(Float portfolioValue) {
        this.portfolioValue = portfolioValue;
    }

    public Integer getCommentFreq() {
        return this.commentFreq;
    }

    public void setCommentFreq(Integer commentFreq) {
        this.commentFreq = commentFreq;
    }

    public Boolean getNoRebalanceStatus() {
        return this.noRebalanceStatus;
    }

    public void setNoRebalanceStatus(Boolean noRebalanceStatus) {
        this.noRebalanceStatus = noRebalanceStatus;
    }

    public Float getCashAmount() {
        return this.cashAmount;
    }

    public void setCashAmount(Float cashAmount) {
        this.cashAmount = cashAmount;
    }

    public Boolean getPortfolioModified() {
        return this.portfolioModified;
    }

    public void setPortfolioModified(Boolean portfolioModified) {
        this.portfolioModified = portfolioModified;
    }

    public Date getLastExecutionUpdate() {
        return this.lastExecutionUpdate;
    }

    public void setLastExecutionUpdate(Date lastExecutionUpdate) {
        this.lastExecutionUpdate = lastExecutionUpdate;
    }

    public boolean isIsFirstDayPerfmanceCalc() {
        return this.isFirstDayPerfmanceCalc;
    }

    public void setIsFirstDayPerfmanceCalc(boolean isFirstDayPerfmanceCalc) {
        this.isFirstDayPerfmanceCalc = isFirstDayPerfmanceCalc;
    }

    public Date getPortfolioAssigned() {
        return this.portfolioAssigned;
    }

    public void setPortfolioAssigned(Date portfolioAssigned) {
        this.portfolioAssigned = portfolioAssigned;
    }

    public Boolean getRebalanceViewed() {
        return this.rebalanceViewed;
    }

    public void setRebalanceViewed(Boolean rebalanceViewed) {
        this.rebalanceViewed = rebalanceViewed;
    }

    public Boolean getPortfolioChangeViewed() {
        return this.portfolioChangeViewed;
    }

    public void setPortfolioChangeViewed(Boolean portfolioChangeViewed) {
        this.portfolioChangeViewed = portfolioChangeViewed;
    }

    public BigDecimal getBenchmarkUnit() {
        return this.benchmarkUnit;
    }

    public void setBenchmarkUnit(BigDecimal benchmarkUnit) {
        this.benchmarkUnit = benchmarkUnit;
    }

    public Double getAllocatedFund() {
        return this.allocatedFund;
    }

    public void setAllocatedFund(Double allocatedFund) {
        this.allocatedFund = allocatedFund;
    }

    public String getVenueName() {
        return this.venueName;
    }

    public void setVenueName(String venueName) {
        this.venueName = venueName;
    }

    public Boolean getCashFlowDflag() {
        return this.cashFlowDflag;
    }

    public void setCashFlowDflag(Boolean cashFlowDflag) {
        this.cashFlowDflag = cashFlowDflag;
    }

    public BigDecimal getCashFlow() {
        return this.cashFlow;
    }

    public void setCashFlow(BigDecimal cashFlow) {
        this.cashFlow = cashFlow;
    }

    public Float getBuyingPower() {
        return this.buyingPower;
    }

    public void setBuyingPower(Float buyingPower) {
        this.buyingPower = buyingPower;
    }

    public Float getRecomendedCashBal() {
        return this.recomendedCashBal;
    }

    public void setRecomendedCashBal(Float recomendedCashBal) {
        this.recomendedCashBal = recomendedCashBal;
    }

    public Float getBlockedCash() {
        return this.blockedCash;
    }

    public void setBlockedCash(Float blockedCash) {
        this.blockedCash = blockedCash;
    }

    public Float getTempBlockedCash() {
        return this.tempBlockedCash;
    }

    public void setTempBlockedCash(Float tempBlockedCash) {
        this.tempBlockedCash = tempBlockedCash;
    }

    public Set getCustomerPortfolioDetailsTbs() {
        return this.customerPortfolioDetailsTbs;
    }

    public void setCustomerPortfolioDetailsTbs(Set customerPortfolioDetailsTbs) {
        this.customerPortfolioDetailsTbs = customerPortfolioDetailsTbs;
    }

    public Set getCustomerPortfolioLogTbs() {
        return this.customerPortfolioLogTbs;
    }

    public void setCustomerPortfolioLogTbs(Set customerPortfolioLogTbs) {
        this.customerPortfolioLogTbs = customerPortfolioLogTbs;
    }

    public Set getCustomerPortfolioDetailsPerformanceTbs() {
        return this.customerPortfolioDetailsPerformanceTbs;
    }

    public void setCustomerPortfolioDetailsPerformanceTbs(Set customerPortfolioDetailsPerformanceTbs) {
        this.customerPortfolioDetailsPerformanceTbs = customerPortfolioDetailsPerformanceTbs;
    }

    public Set getCustomerPortfolioPerformanceTbs() {
        return this.customerPortfolioPerformanceTbs;
    }

    public void setCustomerPortfolioPerformanceTbs(Set customerPortfolioPerformanceTbs) {
        this.customerPortfolioPerformanceTbs = customerPortfolioPerformanceTbs;
    }

    public Set getAddRedeemLogTbs() {
        return this.addRedeemLogTbs;
    }

    public void setAddRedeemLogTbs(Set addRedeemLogTbs) {
        this.addRedeemLogTbs = addRedeemLogTbs;
    }

    public Set getCustomerPortfolioSecuritiesPerformanceTbs() {
        return this.customerPortfolioSecuritiesPerformanceTbs;
    }

    public void setCustomerPortfolioSecuritiesPerformanceTbs(Set customerPortfolioSecuritiesPerformanceTbs) {
        this.customerPortfolioSecuritiesPerformanceTbs = customerPortfolioSecuritiesPerformanceTbs;
    }

    public Set getCustomerDailyCashBalanceTbs() {
        return this.customerDailyCashBalanceTbs;
    }

    public void setCustomerDailyCashBalanceTbs(Set customerDailyCashBalanceTbs) {
        this.customerDailyCashBalanceTbs = customerDailyCashBalanceTbs;
    }

    public Set getRecomendedCustomerPortfolioSecuritiesTbs() {
        return this.recomendedCustomerPortfolioSecuritiesTbs;
    }

    public void setRecomendedCustomerPortfolioSecuritiesTbs(Set recomendedCustomerPortfolioSecuritiesTbs) {
        this.recomendedCustomerPortfolioSecuritiesTbs = recomendedCustomerPortfolioSecuritiesTbs;
    }

    public Set getRecomendedCustomerPortfolioPerformanceTbs() {
        return this.recomendedCustomerPortfolioPerformanceTbs;
    }

    public void setRecomendedCustomerPortfolioPerformanceTbs(Set recomendedCustomerPortfolioPerformanceTbs) {
        this.recomendedCustomerPortfolioPerformanceTbs = recomendedCustomerPortfolioPerformanceTbs;
    }

    public Set getCustomerPortfolioSecuritiesTbs() {
        return this.customerPortfolioSecuritiesTbs;
    }

    public void setCustomerPortfolioSecuritiesTbs(Set customerPortfolioSecuritiesTbs) {
        this.customerPortfolioSecuritiesTbs = customerPortfolioSecuritiesTbs;
    }

    public Float getBlockedCount() {
        return blockedCount;
    }

    public void setBlockedCount(Float blockedCount) {
        this.blockedCount = blockedCount;
    }

    public Float getTempBlockedCount() {
        return tempBlockedCount;
    }

    public void setTempBlockedCount(Float tempBlockedCount) {
        this.tempBlockedCount = tempBlockedCount;
    }

    public String getPortfolioStatus() {
        return portfolioStatus;
    }

    public void setPortfolioStatus(String portfolioStatus) {
        this.portfolioStatus = portfolioStatus;
    }

}
