package com.gtl.mmf.entity;

import java.util.Date;
import java.util.concurrent.atomic.AtomicLong;


// Generated Feb 20, 2014 10:41:01 AM by Hibernate Tools 3.2.1.GA

/**
 * AdminuserTb generated by hbm2java
 */

public class CustomerRiskScoreTb implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6421008516675497602L;
	private Integer risk_score_id;
    private long customer_id;
    private Integer risk_score;
    private Date date_of_rp;


    public CustomerRiskScoreTb() {
    }

    public CustomerRiskScoreTb(long customer_id, Integer risk_score, Date date_of_rp) {
        this.customer_id = customer_id;
        this.risk_score = risk_score;
        this.date_of_rp = date_of_rp;
    }

	public Integer getRisk_score_id() {
		return risk_score_id;
	}

	public void setRisk_score_id(Integer risk_score_id) {
		this.risk_score_id = risk_score_id;
	}

	public long getCustomer_id() {
		return customer_id;
	}

	public void setCustomer_id(long customer_id) {
		this.customer_id = customer_id;
	}

	public Integer getRisk_score() {
		return risk_score;
	}

	public void setRisk_score(Integer risk_score) {
		this.risk_score = risk_score;
	}

	public Date getDate_of_rp() {
		return date_of_rp;
	}

	public void setDate_of_rp(Date date_of_rp) {
		this.date_of_rp = date_of_rp;
	}

  
}
