package com.gtl.mmf.entity;
// Generated Jul 13, 2015 10:58:18 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * CustomerManagementFeeTb generated by hbm2java
 */
public class CustomerManagementFeeTb  implements java.io.Serializable {


     private Integer id;
     private CustomerAdvisorMappingTb customerAdvisorMappingTb;
     private int customerId;
     private Integer advisorId;
     private Date feeCalculateDate;
     private BigDecimal mgmtFee;
     private Short mgmtFeeFreq;
     private Date ecsPayDate;
     private Boolean ecsPaid;
     private String regId;
     private Boolean submittedEcs;
     private Boolean isQuarterEnd;
     private BigDecimal cashFlow;
     private Integer daysToQuarterEnd;
     private BigDecimal mgtFeeonCrntCf;
     private BigDecimal totalAllocatdFund;

    public CustomerManagementFeeTb() {
    }

	
    public CustomerManagementFeeTb(CustomerAdvisorMappingTb customerAdvisorMappingTb, int customerId, Date feeCalculateDate, Date ecsPayDate) {
        this.customerAdvisorMappingTb = customerAdvisorMappingTb;
        this.customerId = customerId;
        this.feeCalculateDate = feeCalculateDate;
        this.ecsPayDate = ecsPayDate;
    }
    public CustomerManagementFeeTb(CustomerAdvisorMappingTb customerAdvisorMappingTb, int customerId, Integer advisorId, Date feeCalculateDate, BigDecimal mgmtFee, Short mgmtFeeFreq, Date ecsPayDate, Boolean ecsPaid, String regId, Boolean submittedEcs, Boolean isQuarterEnd, BigDecimal cashFlow, Integer daysToQuarterEnd, BigDecimal mgtFeeonCrntCf, BigDecimal totalAllocatdFund) {
       this.customerAdvisorMappingTb = customerAdvisorMappingTb;
       this.customerId = customerId;
       this.advisorId = advisorId;
       this.feeCalculateDate = feeCalculateDate;
       this.mgmtFee = mgmtFee;
       this.mgmtFeeFreq = mgmtFeeFreq;
       this.ecsPayDate = ecsPayDate;
       this.ecsPaid = ecsPaid;
       this.regId = regId;
       this.submittedEcs = submittedEcs;
       this.isQuarterEnd = isQuarterEnd;
       this.cashFlow = cashFlow;
       this.daysToQuarterEnd = daysToQuarterEnd;
       this.mgtFeeonCrntCf = mgtFeeonCrntCf;
       this.totalAllocatdFund = totalAllocatdFund;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CustomerAdvisorMappingTb getCustomerAdvisorMappingTb() {
        return this.customerAdvisorMappingTb;
    }
    
    public void setCustomerAdvisorMappingTb(CustomerAdvisorMappingTb customerAdvisorMappingTb) {
        this.customerAdvisorMappingTb = customerAdvisorMappingTb;
    }
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    public Integer getAdvisorId() {
        return this.advisorId;
    }
    
    public void setAdvisorId(Integer advisorId) {
        this.advisorId = advisorId;
    }
    public Date getFeeCalculateDate() {
        return this.feeCalculateDate;
    }
    
    public void setFeeCalculateDate(Date feeCalculateDate) {
        this.feeCalculateDate = feeCalculateDate;
    }
    public BigDecimal getMgmtFee() {
        return this.mgmtFee;
    }
    
    public void setMgmtFee(BigDecimal mgmtFee) {
        this.mgmtFee = mgmtFee;
    }
    public Short getMgmtFeeFreq() {
        return this.mgmtFeeFreq;
    }
    
    public void setMgmtFeeFreq(Short mgmtFeeFreq) {
        this.mgmtFeeFreq = mgmtFeeFreq;
    }
    public Date getEcsPayDate() {
        return this.ecsPayDate;
    }
    
    public void setEcsPayDate(Date ecsPayDate) {
        this.ecsPayDate = ecsPayDate;
    }
    public Boolean getEcsPaid() {
        return this.ecsPaid;
    }
    
    public void setEcsPaid(Boolean ecsPaid) {
        this.ecsPaid = ecsPaid;
    }
    public String getRegId() {
        return this.regId;
    }
    
    public void setRegId(String regId) {
        this.regId = regId;
    }
    public Boolean getSubmittedEcs() {
        return this.submittedEcs;
    }
    
    public void setSubmittedEcs(Boolean submittedEcs) {
        this.submittedEcs = submittedEcs;
    }
    public Boolean getIsQuarterEnd() {
        return this.isQuarterEnd;
    }
    
    public void setIsQuarterEnd(Boolean isQuarterEnd) {
        this.isQuarterEnd = isQuarterEnd;
    }
    public BigDecimal getCashFlow() {
        return this.cashFlow;
    }
    
    public void setCashFlow(BigDecimal cashFlow) {
        this.cashFlow = cashFlow;
    }
    public Integer getDaysToQuarterEnd() {
        return this.daysToQuarterEnd;
    }
    
    public void setDaysToQuarterEnd(Integer daysToQuarterEnd) {
        this.daysToQuarterEnd = daysToQuarterEnd;
    }
    public BigDecimal getMgtFeeonCrntCf() {
        return this.mgtFeeonCrntCf;
    }
    
    public void setMgtFeeonCrntCf(BigDecimal mgtFeeonCrntCf) {
        this.mgtFeeonCrntCf = mgtFeeonCrntCf;
    }
    public BigDecimal getTotalAllocatdFund() {
        return this.totalAllocatdFund;
    }
    
    public void setTotalAllocatdFund(BigDecimal totalAllocatdFund) {
        this.totalAllocatdFund = totalAllocatdFund;
    }




}


