package com.gtl.mmf.entity;
// Generated 5 Dec, 2015 1:20:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * CustomerPortfolioSecuritiesPerformanceTb generated by hbm2java
 */
public class CustomerPortfolioSecuritiesPerformanceTb  implements java.io.Serializable {


     private Integer customerPortfolioSecuritiesPerformanceId;
     private CustomerPortfolioDetailsTb customerPortfolioDetailsTb;
     private CustomerPortfolioDetailsPerformanceTb customerPortfolioDetailsPerformanceTb;
     private MasterAssetTb masterAssetTb;
     private CustomerPortfolioTb customerPortfolioTb;
     private CustomerPortfolioSecuritiesTb customerPortfolioSecuritiesTb;
     private CustomerPortfolioPerformanceTb customerPortfolioPerformanceTb;
     private String securityCode;
     private Date datetime;
     private BigDecimal closingValue;
     private BigDecimal existingUnits;
     private BigDecimal closingPrice;
     private BigDecimal marketValue;
     private BigDecimal cashFlow;
     private BigDecimal marketValueAfterCashFlow;
     private BigDecimal subPeriodReturn;

    public CustomerPortfolioSecuritiesPerformanceTb() {
    }

	
    public CustomerPortfolioSecuritiesPerformanceTb(CustomerPortfolioDetailsTb customerPortfolioDetailsTb, CustomerPortfolioDetailsPerformanceTb customerPortfolioDetailsPerformanceTb, MasterAssetTb masterAssetTb, CustomerPortfolioTb customerPortfolioTb, CustomerPortfolioSecuritiesTb customerPortfolioSecuritiesTb, CustomerPortfolioPerformanceTb customerPortfolioPerformanceTb, String securityCode, Date datetime, BigDecimal closingValue, BigDecimal existingUnits, BigDecimal closingPrice) {
        this.customerPortfolioDetailsTb = customerPortfolioDetailsTb;
        this.customerPortfolioDetailsPerformanceTb = customerPortfolioDetailsPerformanceTb;
        this.masterAssetTb = masterAssetTb;
        this.customerPortfolioTb = customerPortfolioTb;
        this.customerPortfolioSecuritiesTb = customerPortfolioSecuritiesTb;
        this.customerPortfolioPerformanceTb = customerPortfolioPerformanceTb;
        this.securityCode = securityCode;
        this.datetime = datetime;
        this.closingValue = closingValue;
        this.existingUnits = existingUnits;
        this.closingPrice = closingPrice;
    }
    public CustomerPortfolioSecuritiesPerformanceTb(CustomerPortfolioDetailsTb customerPortfolioDetailsTb, CustomerPortfolioDetailsPerformanceTb customerPortfolioDetailsPerformanceTb, MasterAssetTb masterAssetTb, CustomerPortfolioTb customerPortfolioTb, CustomerPortfolioSecuritiesTb customerPortfolioSecuritiesTb, CustomerPortfolioPerformanceTb customerPortfolioPerformanceTb, String securityCode, Date datetime, BigDecimal closingValue, BigDecimal existingUnits, BigDecimal closingPrice, BigDecimal marketValue, BigDecimal cashFlow, BigDecimal marketValueAfterCashFlow, BigDecimal subPeriodReturn) {
       this.customerPortfolioDetailsTb = customerPortfolioDetailsTb;
       this.customerPortfolioDetailsPerformanceTb = customerPortfolioDetailsPerformanceTb;
       this.masterAssetTb = masterAssetTb;
       this.customerPortfolioTb = customerPortfolioTb;
       this.customerPortfolioSecuritiesTb = customerPortfolioSecuritiesTb;
       this.customerPortfolioPerformanceTb = customerPortfolioPerformanceTb;
       this.securityCode = securityCode;
       this.datetime = datetime;
       this.closingValue = closingValue;
       this.existingUnits = existingUnits;
       this.closingPrice = closingPrice;
       this.marketValue = marketValue;
       this.cashFlow = cashFlow;
       this.marketValueAfterCashFlow = marketValueAfterCashFlow;
       this.subPeriodReturn = subPeriodReturn;
    }
   
    public Integer getCustomerPortfolioSecuritiesPerformanceId() {
        return this.customerPortfolioSecuritiesPerformanceId;
    }
    
    public void setCustomerPortfolioSecuritiesPerformanceId(Integer customerPortfolioSecuritiesPerformanceId) {
        this.customerPortfolioSecuritiesPerformanceId = customerPortfolioSecuritiesPerformanceId;
    }
    public CustomerPortfolioDetailsTb getCustomerPortfolioDetailsTb() {
        return this.customerPortfolioDetailsTb;
    }
    
    public void setCustomerPortfolioDetailsTb(CustomerPortfolioDetailsTb customerPortfolioDetailsTb) {
        this.customerPortfolioDetailsTb = customerPortfolioDetailsTb;
    }
    public CustomerPortfolioDetailsPerformanceTb getCustomerPortfolioDetailsPerformanceTb() {
        return this.customerPortfolioDetailsPerformanceTb;
    }
    
    public void setCustomerPortfolioDetailsPerformanceTb(CustomerPortfolioDetailsPerformanceTb customerPortfolioDetailsPerformanceTb) {
        this.customerPortfolioDetailsPerformanceTb = customerPortfolioDetailsPerformanceTb;
    }
    public MasterAssetTb getMasterAssetTb() {
        return this.masterAssetTb;
    }
    
    public void setMasterAssetTb(MasterAssetTb masterAssetTb) {
        this.masterAssetTb = masterAssetTb;
    }
    public CustomerPortfolioTb getCustomerPortfolioTb() {
        return this.customerPortfolioTb;
    }
    
    public void setCustomerPortfolioTb(CustomerPortfolioTb customerPortfolioTb) {
        this.customerPortfolioTb = customerPortfolioTb;
    }
    public CustomerPortfolioSecuritiesTb getCustomerPortfolioSecuritiesTb() {
        return this.customerPortfolioSecuritiesTb;
    }
    
    public void setCustomerPortfolioSecuritiesTb(CustomerPortfolioSecuritiesTb customerPortfolioSecuritiesTb) {
        this.customerPortfolioSecuritiesTb = customerPortfolioSecuritiesTb;
    }
    public CustomerPortfolioPerformanceTb getCustomerPortfolioPerformanceTb() {
        return this.customerPortfolioPerformanceTb;
    }
    
    public void setCustomerPortfolioPerformanceTb(CustomerPortfolioPerformanceTb customerPortfolioPerformanceTb) {
        this.customerPortfolioPerformanceTb = customerPortfolioPerformanceTb;
    }
    public String getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public BigDecimal getClosingValue() {
        return this.closingValue;
    }
    
    public void setClosingValue(BigDecimal closingValue) {
        this.closingValue = closingValue;
    }
    public BigDecimal getExistingUnits() {
        return this.existingUnits;
    }
    
    public void setExistingUnits(BigDecimal existingUnits) {
        this.existingUnits = existingUnits;
    }
    public BigDecimal getClosingPrice() {
        return this.closingPrice;
    }
    
    public void setClosingPrice(BigDecimal closingPrice) {
        this.closingPrice = closingPrice;
    }
    public BigDecimal getMarketValue() {
        return this.marketValue;
    }
    
    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }
    public BigDecimal getCashFlow() {
        return this.cashFlow;
    }
    
    public void setCashFlow(BigDecimal cashFlow) {
        this.cashFlow = cashFlow;
    }
    public BigDecimal getMarketValueAfterCashFlow() {
        return this.marketValueAfterCashFlow;
    }
    
    public void setMarketValueAfterCashFlow(BigDecimal marketValueAfterCashFlow) {
        this.marketValueAfterCashFlow = marketValueAfterCashFlow;
    }
    public BigDecimal getSubPeriodReturn() {
        return this.subPeriodReturn;
    }
    
    public void setSubPeriodReturn(BigDecimal subPeriodReturn) {
        this.subPeriodReturn = subPeriodReturn;
    }




}


