package com.gtl.mmf.entity;
// Generated Jul 1, 2016 3:55:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CustomerRiskProfileResponseSetTb generated by hbm2java
 */
public class CustomerRiskProfileResponseSetTb implements java.io.Serializable {

	private Integer responseId;
	private Integer responseSetId;
	private String customerRegistrationId;
	private Integer questionId;
	private Integer answerId;
	private Date dateTime;

	public CustomerRiskProfileResponseSetTb() {
	}

	public CustomerRiskProfileResponseSetTb(Integer responseSetId,
			String customerRegistrationId, Integer questionId,
			Integer answerId, Date dateTime) {
		this.responseSetId = responseSetId;
		this.customerRegistrationId = customerRegistrationId;
		this.questionId = questionId;
		this.answerId = answerId;
		this.dateTime = dateTime;
	}

	public Integer getResponseId() {
		return this.responseId;
	}

	public void setResponseId(Integer responseId) {
		this.responseId = responseId;
	}

	public Integer getResponseSetId() {
		return this.responseSetId;
	}

	public void setResponseSetId(Integer responseSetId) {
		this.responseSetId = responseSetId;
	}

	public String getCustomerRegistrationId() {
		return this.customerRegistrationId;
	}

	public void setCustomerRegistrationId(String customerRegistrationId) {
		this.customerRegistrationId = customerRegistrationId;
	}

	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	public Integer getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
