package com.gtl.mmf.entity;
// Generated 18 Jul, 2014 3:17:57 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * CustomerPortfolioAuditTb generated by hbm2java
 */
public class CustomerPortfolioAuditTb implements java.io.Serializable {

    private Integer customerPortfolioAuditId;
    private Integer customerPortfolioId;
    private Integer relationId;
    private Integer customerId;
    private String omsLoginId;
    private Integer advisorId;
    private Integer portfolioId;
    private Float currentValue;
    private Float portfolio90DayReturns;
    private Float portfolio1YearReturns;
    private String adviserComment;
    private String customerComment;
    private Integer outperformance;
    private BigDecimal advisorPortfolioStartValue;
    private BigDecimal benchmarkStartValue;
    private Float advisorPortfolioReturnsFromStart;
    private Float benchmarkReturnsFromStart;
    private Boolean rebalanceRequired;
    private Date rebalanceReqdDate;
    private Date lastUpdated;
    private Boolean status;
    private Float portfolioValue;
    private Integer commentFreq;
    private Boolean noRebalanceStatus;
    private Float cashAmount;
    private Boolean portfolioModified;
    private Date lastExecutionUpdate;
    private boolean isFirstDayPerfmanceCalc;
    private Date lastUpdateOn;
    private String activityType;

    public CustomerPortfolioAuditTb() {
    }

    public CustomerPortfolioAuditTb(boolean isFirstDayPerfmanceCalc, String activityType) {
        this.isFirstDayPerfmanceCalc = isFirstDayPerfmanceCalc;
        this.activityType = activityType;
    }

    public CustomerPortfolioAuditTb(Integer customerPortfolioId, Integer relationId, Integer customerId, String omsLoginId, Integer advisorId, Integer portfolioId, Float currentValue, Float portfolio90DayReturns, Float portfolio1YearReturns, String adviserComment, String customerComment, Integer outperformance, BigDecimal advisorPortfolioStartValue, BigDecimal benchmarkStartValue, Float advisorPortfolioReturnsFromStart, Float benchmarkReturnsFromStart, Boolean rebalanceRequired, Date rebalanceReqdDate, Date lastUpdated, Boolean status, Float portfolioValue, Integer commentFreq, Boolean noRebalanceStatus, Float cashAmount, Boolean portfolioModified, Date lastExecutionUpdate, boolean isFirstDayPerfmanceCalc, Date lastUpdateOn, String activityType) {
        this.customerPortfolioId = customerPortfolioId;
        this.relationId = relationId;
        this.customerId = customerId;
        this.omsLoginId = omsLoginId;
        this.advisorId = advisorId;
        this.portfolioId = portfolioId;
        this.currentValue = currentValue;
        this.portfolio90DayReturns = portfolio90DayReturns;
        this.portfolio1YearReturns = portfolio1YearReturns;
        this.adviserComment = adviserComment;
        this.customerComment = customerComment;
        this.outperformance = outperformance;
        this.advisorPortfolioStartValue = advisorPortfolioStartValue;
        this.benchmarkStartValue = benchmarkStartValue;
        this.advisorPortfolioReturnsFromStart = advisorPortfolioReturnsFromStart;
        this.benchmarkReturnsFromStart = benchmarkReturnsFromStart;
        this.rebalanceRequired = rebalanceRequired;
        this.rebalanceReqdDate = rebalanceReqdDate;
        this.lastUpdated = lastUpdated;
        this.status = status;
        this.portfolioValue = portfolioValue;
        this.commentFreq = commentFreq;
        this.noRebalanceStatus = noRebalanceStatus;
        this.cashAmount = cashAmount;
        this.portfolioModified = portfolioModified;
        this.lastExecutionUpdate = lastExecutionUpdate;
        this.isFirstDayPerfmanceCalc = isFirstDayPerfmanceCalc;
        this.lastUpdateOn = lastUpdateOn;
        this.activityType = activityType;
    }

    public Integer getCustomerPortfolioAuditId() {
        return this.customerPortfolioAuditId;
    }

    public void setCustomerPortfolioAuditId(Integer customerPortfolioAuditId) {
        this.customerPortfolioAuditId = customerPortfolioAuditId;
    }

    public Integer getCustomerPortfolioId() {
        return this.customerPortfolioId;
    }

    public void setCustomerPortfolioId(Integer customerPortfolioId) {
        this.customerPortfolioId = customerPortfolioId;
    }

    public Integer getRelationId() {
        return this.relationId;
    }

    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public String getOmsLoginId() {
        return this.omsLoginId;
    }

    public void setOmsLoginId(String omsLoginId) {
        this.omsLoginId = omsLoginId;
    }

    public Integer getAdvisorId() {
        return this.advisorId;
    }

    public void setAdvisorId(Integer advisorId) {
        this.advisorId = advisorId;
    }

    public Integer getPortfolioId() {
        return this.portfolioId;
    }

    public void setPortfolioId(Integer portfolioId) {
        this.portfolioId = portfolioId;
    }

    public Float getCurrentValue() {
        return this.currentValue;
    }

    public void setCurrentValue(Float currentValue) {
        this.currentValue = currentValue;
    }

    public Float getPortfolio90DayReturns() {
        return this.portfolio90DayReturns;
    }

    public void setPortfolio90DayReturns(Float portfolio90DayReturns) {
        this.portfolio90DayReturns = portfolio90DayReturns;
    }

    public Float getPortfolio1YearReturns() {
        return this.portfolio1YearReturns;
    }

    public void setPortfolio1YearReturns(Float portfolio1YearReturns) {
        this.portfolio1YearReturns = portfolio1YearReturns;
    }

    public String getAdviserComment() {
        return this.adviserComment;
    }

    public void setAdviserComment(String adviserComment) {
        this.adviserComment = adviserComment;
    }

    public String getCustomerComment() {
        return this.customerComment;
    }

    public void setCustomerComment(String customerComment) {
        this.customerComment = customerComment;
    }

    public Integer getOutperformance() {
        return this.outperformance;
    }

    public void setOutperformance(Integer outperformance) {
        this.outperformance = outperformance;
    }

    public BigDecimal getAdvisorPortfolioStartValue() {
        return this.advisorPortfolioStartValue;
    }

    public void setAdvisorPortfolioStartValue(BigDecimal advisorPortfolioStartValue) {
        this.advisorPortfolioStartValue = advisorPortfolioStartValue;
    }

    public BigDecimal getBenchmarkStartValue() {
        return this.benchmarkStartValue;
    }

    public void setBenchmarkStartValue(BigDecimal benchmarkStartValue) {
        this.benchmarkStartValue = benchmarkStartValue;
    }

    public Float getAdvisorPortfolioReturnsFromStart() {
        return this.advisorPortfolioReturnsFromStart;
    }

    public void setAdvisorPortfolioReturnsFromStart(Float advisorPortfolioReturnsFromStart) {
        this.advisorPortfolioReturnsFromStart = advisorPortfolioReturnsFromStart;
    }

    public Float getBenchmarkReturnsFromStart() {
        return this.benchmarkReturnsFromStart;
    }

    public void setBenchmarkReturnsFromStart(Float benchmarkReturnsFromStart) {
        this.benchmarkReturnsFromStart = benchmarkReturnsFromStart;
    }

    public Boolean getRebalanceRequired() {
        return this.rebalanceRequired;
    }

    public void setRebalanceRequired(Boolean rebalanceRequired) {
        this.rebalanceRequired = rebalanceRequired;
    }

    public Date getRebalanceReqdDate() {
        return this.rebalanceReqdDate;
    }

    public void setRebalanceReqdDate(Date rebalanceReqdDate) {
        this.rebalanceReqdDate = rebalanceReqdDate;
    }

    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Float getPortfolioValue() {
        return this.portfolioValue;
    }

    public void setPortfolioValue(Float portfolioValue) {
        this.portfolioValue = portfolioValue;
    }

    public Integer getCommentFreq() {
        return this.commentFreq;
    }

    public void setCommentFreq(Integer commentFreq) {
        this.commentFreq = commentFreq;
    }

    public Boolean getNoRebalanceStatus() {
        return this.noRebalanceStatus;
    }

    public void setNoRebalanceStatus(Boolean noRebalanceStatus) {
        this.noRebalanceStatus = noRebalanceStatus;
    }

    public Float getCashAmount() {
        return this.cashAmount;
    }

    public void setCashAmount(Float cashAmount) {
        this.cashAmount = cashAmount;
    }

    public Boolean getPortfolioModified() {
        return this.portfolioModified;
    }

    public void setPortfolioModified(Boolean portfolioModified) {
        this.portfolioModified = portfolioModified;
    }

    public Date getLastExecutionUpdate() {
        return this.lastExecutionUpdate;
    }

    public void setLastExecutionUpdate(Date lastExecutionUpdate) {
        this.lastExecutionUpdate = lastExecutionUpdate;
    }

    public boolean isIsFirstDayPerfmanceCalc() {
        return this.isFirstDayPerfmanceCalc;
    }

    public void setIsFirstDayPerfmanceCalc(boolean isFirstDayPerfmanceCalc) {
        this.isFirstDayPerfmanceCalc = isFirstDayPerfmanceCalc;
    }

    public Date getLastUpdateOn() {
        return this.lastUpdateOn;
    }

    public void setLastUpdateOn(Date lastUpdateOn) {
        this.lastUpdateOn = lastUpdateOn;
    }

    public String getActivityType() {
        return this.activityType;
    }

    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }

}
