package com.gtl.mmf.entity;
// Generated Dec 22, 2014 4:17:26 PM by Hibernate Tools 3.2.1.GA



/**
 * DemataccountTb generated by hbm2java
 */
public class DemataccountTb  implements java.io.Serializable {


     private int id;
     private Integer key;
     private String dematAccount;

    public DemataccountTb() {
    }

	
    public DemataccountTb(int id) {
        this.id = id;
    }
    public DemataccountTb(int id, Integer key, String dematAccount) {
       this.id = id;
       this.key = key;
       this.dematAccount = dematAccount;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getKey() {
        return this.key;
    }
    
    public void setKey(Integer key) {
        this.key = key;
    }
    public String getDematAccount() {
        return this.dematAccount;
    }
    
    public void setDematAccount(String dematAccount) {
        this.dematAccount = dematAccount;
    }




}


