package com.gtl.mmf.entity;
// Generated Dec 22, 2014 4:17:26 PM by Hibernate Tools 3.2.1.GA



/**
 * DpidsTb generated by hbm2java
 */
public class DpidsTb  implements java.io.Serializable {


     private int id;
     private Integer key;
     private String dpid;

    public DpidsTb() {
    }

	
    public DpidsTb(int id) {
        this.id = id;
    }
    public DpidsTb(int id, Integer key, String dpid) {
       this.id = id;
       this.key = key;
       this.dpid = dpid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getKey() {
        return this.key;
    }
    
    public void setKey(Integer key) {
        this.key = key;
    }
    public String getDpid() {
        return this.dpid;
    }
    
    public void setDpid(String dpid) {
        this.dpid = dpid;
    }




}


