package com.gtl.mmf.entity;
// Generated Jul 16, 2015 12:27:52 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * EcsDebtPaymentFileContentTb generated by hbm2java
 */
public class EcsDebtPaymentFileContentTb implements java.io.Serializable {

    private Integer id;
    private String regId;
    private BigDecimal debtAmount;
    private String status;
    private String failureReason;
    private Date dueDate;
    private Date fileUploadDate;
    private Date lastUpdated;
    private Boolean mfee;
    private Boolean pfee;
    private Date feeCalculatedate;
    private Integer debitRequestNumber;

    public EcsDebtPaymentFileContentTb() {
    }

    public EcsDebtPaymentFileContentTb(String regId, Date dueDate, Date fileUploadDate, Date lastUpdated) {
        this.regId = regId;
        this.dueDate = dueDate;
        this.fileUploadDate = fileUploadDate;
        this.lastUpdated = lastUpdated;
    }

    public EcsDebtPaymentFileContentTb(String regId, BigDecimal debtAmount, String status, String failureReason, Date dueDate, Date fileUploadDate, Date lastUpdated, Boolean mfee, Boolean pfee, Date feeCalculatedate, Integer debitRequestNumber) {
        this.regId = regId;
        this.debtAmount = debtAmount;
        this.status = status;
        this.failureReason = failureReason;
        this.dueDate = dueDate;
        this.fileUploadDate = fileUploadDate;
        this.lastUpdated = lastUpdated;
        this.mfee = mfee;
        this.pfee = pfee;
        this.feeCalculatedate = feeCalculatedate;
        this.debitRequestNumber = debitRequestNumber;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRegId() {
        return this.regId;
    }

    public void setRegId(String regId) {
        this.regId = regId;
    }

    public BigDecimal getDebtAmount() {
        return this.debtAmount;
    }

    public void setDebtAmount(BigDecimal debtAmount) {
        this.debtAmount = debtAmount;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getFailureReason() {
        return this.failureReason;
    }

    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    public Date getDueDate() {
        return this.dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public Date getFileUploadDate() {
        return this.fileUploadDate;
    }

    public void setFileUploadDate(Date fileUploadDate) {
        this.fileUploadDate = fileUploadDate;
    }

    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public Boolean getMfee() {
        return this.mfee;
    }

    public void setMfee(Boolean mfee) {
        this.mfee = mfee;
    }

    public Boolean getPfee() {
        return this.pfee;
    }

    public void setPfee(Boolean pfee) {
        this.pfee = pfee;
    }

    public Date getFeeCalculatedate() {
        return this.feeCalculatedate;
    }

    public void setFeeCalculatedate(Date feeCalculatedate) {
        this.feeCalculatedate = feeCalculatedate;
    }

    public Integer getDebitRequestNumber() {
        return debitRequestNumber;
    }

    public void setDebitRequestNumber(Integer debitRequestNumber) {
        this.debitRequestNumber = debitRequestNumber;
    }

}
