package com.gtl.mmf.entity;
// Generated 22 Feb, 2016 11:43:50 AM by Hibernate Tools 3.6.0



/**
 * EcsTransmittalSheetTb generated by hbm2java
 */
public class EcsTransmittalSheetTb  implements java.io.Serializable {


     private Integer id;
     private String registrationId;
     private String serialNo;
     private String lotno;
     private String debitType;
     private String amount;
     private String frequency;
     private String startDate;
     private String endDate;
     private String acHolderName;
     private String bankName;
     private String acType;
     private String acno;
     private String micr;
     private String ifsc;
     private Boolean ecsSend;
     private Boolean verified;
     private Boolean rejected;
     private String remark;

    public EcsTransmittalSheetTb() {
    }

    public EcsTransmittalSheetTb(String registrationId, String serialNo, String lotno, String debitType, String amount, String frequency, String startDate, String endDate, String acHolderName, String bankName, String acType, String acno, String micr, String ifsc, Boolean ecsSend, Boolean verified, Boolean rejected, String remark) {
       this.registrationId = registrationId;
       this.serialNo = serialNo;
       this.lotno = lotno;
       this.debitType = debitType;
       this.amount = amount;
       this.frequency = frequency;
       this.startDate = startDate;
       this.endDate = endDate;
       this.acHolderName = acHolderName;
       this.bankName = bankName;
       this.acType = acType;
       this.acno = acno;
       this.micr = micr;
       this.ifsc = ifsc;
       this.ecsSend = ecsSend;
       this.verified = verified;
       this.rejected = rejected;
       this.remark = remark;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }
    public String getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }
    public String getLotno() {
        return this.lotno;
    }
    
    public void setLotno(String lotno) {
        this.lotno = lotno;
    }
    public String getDebitType() {
        return this.debitType;
    }
    
    public void setDebitType(String debitType) {
        this.debitType = debitType;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
    public String getAcHolderName() {
        return this.acHolderName;
    }
    
    public void setAcHolderName(String acHolderName) {
        this.acHolderName = acHolderName;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }
    public String getAcType() {
        return this.acType;
    }
    
    public void setAcType(String acType) {
        this.acType = acType;
    }
    public String getAcno() {
        return this.acno;
    }
    
    public void setAcno(String acno) {
        this.acno = acno;
    }
    public String getMicr() {
        return this.micr;
    }
    
    public void setMicr(String micr) {
        this.micr = micr;
    }
    public String getIfsc() {
        return this.ifsc;
    }
    
    public void setIfsc(String ifsc) {
        this.ifsc = ifsc;
    }
    public Boolean getEcsSend() {
        return this.ecsSend;
    }
    
    public void setEcsSend(Boolean ecsSend) {
        this.ecsSend = ecsSend;
    }
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    public Boolean isRejected() {
        return rejected;
    }

    public void setRejected(Boolean rejected) {
        this.rejected = rejected;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}


