package com.gtl.mmf.entity;
// Generated 23 Feb, 2016 4:14:13 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ExchangeHolidayTb generated by hbm2java
 */
public class ExchangeHolidayTb  implements java.io.Serializable {


     private Integer id;
     private Date hdate;
     private String hevent;

    public ExchangeHolidayTb() {
    }

	
    public ExchangeHolidayTb(Date hdate, String hevent) {
        this.hdate = hdate;
        this.hevent = hevent;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public Date getHdate() {
        return this.hdate;
    }
    
    public void setHdate(Date hdate) {
        this.hdate = hdate;
    }
    
    public String getHevent() {
        return this.hevent;
    }
    
    public void setHevent(String hevent) {
        this.hevent = hevent;
    }

}


