package com.gtl.mmf.entity;
// Generated Jul 15, 2016 5:29:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * FpFinancialAssetGrowthAssumptionTb generated by hbm2java
 */
public class FpFinancialAssetGrowthAssumptionTb implements java.io.Serializable {

	private Integer financialAssetId;
	private String financialAssetName;
	private Float growthRate;

	public FpFinancialAssetGrowthAssumptionTb() {
	}

	public FpFinancialAssetGrowthAssumptionTb(String financialAssetName,
			Float growthRate) {
		this.financialAssetName = financialAssetName;
		this.growthRate = growthRate;
	}

	public Integer getFinancialAssetId() {
		return this.financialAssetId;
	}

	public void setFinancialAssetId(Integer financialAssetId) {
		this.financialAssetId = financialAssetId;
	}

	public String getFinancialAssetName() {
		return this.financialAssetName;
	}

	public void setFinancialAssetName(String financialAssetName) {
		this.financialAssetName = financialAssetName;
	}

	public Float getGrowthRate() {
		return this.growthRate;
	}

	public void setGrowthRate(Float growthRate) {
		this.growthRate = growthRate;
	}

}
