package com.gtl.mmf.entity;
// Generated Jul 15, 2016 5:29:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * FpLoanRelatedAssumptionsTb generated by hbm2java
 */
public class FpLoanRelatedAssumptionsTb implements java.io.Serializable {

	private Integer id;
	private Integer assumptionId;
	private String customerId;
	private Integer loanAssumptionId;
	private String loanTypeDescription;
	private Integer loanDuration;
	private Float interestRate;
	private Float downPaymentPercent;

	public FpLoanRelatedAssumptionsTb() {
	}

	public FpLoanRelatedAssumptionsTb(Integer assumptionId, String customerId,
			Integer loanAssumptionId, String loanTypeDescription,
			Integer loanDuration, Float interestRate, Float downPaymentPercent) {
		this.assumptionId = assumptionId;
		this.customerId = customerId;
		this.loanAssumptionId = loanAssumptionId;
		this.loanTypeDescription = loanTypeDescription;
		this.loanDuration = loanDuration;
		this.interestRate = interestRate;
		this.downPaymentPercent = downPaymentPercent;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAssumptionId() {
		return this.assumptionId;
	}

	public void setAssumptionId(Integer assumptionId) {
		this.assumptionId = assumptionId;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public Integer getLoanAssumptionId() {
		return this.loanAssumptionId;
	}

	public void setLoanAssumptionId(Integer loanAssumptionId) {
		this.loanAssumptionId = loanAssumptionId;
	}

	public String getLoanTypeDescription() {
		return this.loanTypeDescription;
	}

	public void setLoanTypeDescription(String loanTypeDescription) {
		this.loanTypeDescription = loanTypeDescription;
	}

	public Integer getLoanDuration() {
		return this.loanDuration;
	}

	public void setLoanDuration(Integer loanDuration) {
		this.loanDuration = loanDuration;
	}

	public Float getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(Float interestRate) {
		this.interestRate = interestRate;
	}

	public Float getDownPaymentPercent() {
		return this.downPaymentPercent;
	}

	public void setDownPaymentPercent(Float downPaymentPercent) {
		this.downPaymentPercent = downPaymentPercent;
	}

}
