package com.gtl.mmf.entity;
// Generated Jul 15, 2016 5:29:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * FpMappingGoalsidToLoansidTb generated by hbm2java
 */
public class FpMappingGoalsidToLoansidTb implements java.io.Serializable {

	private Integer mappingId;
	private Integer lifeGoalsId;
	private String lifeGoalsDescription;
	private Integer loansId;
	private String loansDescription;

	public FpMappingGoalsidToLoansidTb() {
	}

	public FpMappingGoalsidToLoansidTb(Integer lifeGoalsId,
			String lifeGoalsDescription, Integer loansId,
			String loansDescription) {
		this.lifeGoalsId = lifeGoalsId;
		this.lifeGoalsDescription = lifeGoalsDescription;
		this.loansId = loansId;
		this.loansDescription = loansDescription;
	}

	public Integer getMappingId() {
		return this.mappingId;
	}

	public void setMappingId(Integer mappingId) {
		this.mappingId = mappingId;
	}

	public Integer getLifeGoalsId() {
		return this.lifeGoalsId;
	}

	public void setLifeGoalsId(Integer lifeGoalsId) {
		this.lifeGoalsId = lifeGoalsId;
	}

	public String getLifeGoalsDescription() {
		return this.lifeGoalsDescription;
	}

	public void setLifeGoalsDescription(String lifeGoalsDescription) {
		this.lifeGoalsDescription = lifeGoalsDescription;
	}

	public Integer getLoansId() {
		return this.loansId;
	}

	public void setLoansId(Integer loansId) {
		this.loansId = loansId;
	}

	public String getLoansDescription() {
		return this.loansDescription;
	}

	public void setLoansDescription(String loansDescription) {
		this.loansDescription = loansDescription;
	}

}
