package com.gtl.mmf.entity;
// Generated Jul 15, 2016 5:29:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FpMasterUserInputDetailsTb generated by hbm2java
 */
public class FpMasterUserInputDetailsTb implements java.io.Serializable {

	private Integer userDetialsId;
	private String customerId;
	private Date dateTime;
	private Integer selfAge;
	private String gender;
	private Integer selfMonthlyTakeHomeSalary;
	private String marritalStatus;
	private Integer spouseAge;
	private Integer spouseMonthlyTakeHomeSalary;
	private Integer totalMonthlySalary;
	private Integer monthlySavings;
	private Float savingsRate;
	private Integer totalCurrentFinancialAssets;
	private Integer expectedRiskScoreId;

	public FpMasterUserInputDetailsTb() {
	}

	public FpMasterUserInputDetailsTb(String customerId, Date dateTime,
			Integer selfAge, String gender, Integer selfMonthlyTakeHomeSalary,
			String marritalStatus, Integer spouseAge,
			Integer spouseMonthlyTakeHomeSalary, Integer totalMonthlySalary,
			Integer monthlySavings, Float savingsRate,
			Integer totalCurrentFinancialAssets, Integer expectedRiskScoreId) {
		this.customerId = customerId;
		this.dateTime = dateTime;
		this.selfAge = selfAge;
		this.gender = gender;
		this.selfMonthlyTakeHomeSalary = selfMonthlyTakeHomeSalary;
		this.marritalStatus = marritalStatus;
		this.spouseAge = spouseAge;
		this.spouseMonthlyTakeHomeSalary = spouseMonthlyTakeHomeSalary;
		this.totalMonthlySalary = totalMonthlySalary;
		this.monthlySavings = monthlySavings;
		this.savingsRate = savingsRate;
		this.totalCurrentFinancialAssets = totalCurrentFinancialAssets;
		this.expectedRiskScoreId = expectedRiskScoreId;
	}

	public Integer getUserDetialsId() {
		return this.userDetialsId;
	}

	public void setUserDetialsId(Integer userDetialsId) {
		this.userDetialsId = userDetialsId;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Integer getSelfAge() {
		return this.selfAge;
	}

	public void setSelfAge(Integer selfAge) {
		this.selfAge = selfAge;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Integer getSelfMonthlyTakeHomeSalary() {
		return this.selfMonthlyTakeHomeSalary;
	}

	public void setSelfMonthlyTakeHomeSalary(Integer selfMonthlyTakeHomeSalary) {
		this.selfMonthlyTakeHomeSalary = selfMonthlyTakeHomeSalary;
	}

	public String getMarritalStatus() {
		return this.marritalStatus;
	}

	public void setMarritalStatus(String marritalStatus) {
		this.marritalStatus = marritalStatus;
	}

	public Integer getSpouseAge() {
		return this.spouseAge;
	}

	public void setSpouseAge(Integer spouseAge) {
		this.spouseAge = spouseAge;
	}

	public Integer getSpouseMonthlyTakeHomeSalary() {
		return this.spouseMonthlyTakeHomeSalary;
	}

	public void setSpouseMonthlyTakeHomeSalary(
			Integer spouseMonthlyTakeHomeSalary) {
		this.spouseMonthlyTakeHomeSalary = spouseMonthlyTakeHomeSalary;
	}

	public Integer getTotalMonthlySalary() {
		return this.totalMonthlySalary;
	}

	public void setTotalMonthlySalary(Integer totalMonthlySalary) {
		this.totalMonthlySalary = totalMonthlySalary;
	}

	public Integer getMonthlySavings() {
		return this.monthlySavings;
	}

	public void setMonthlySavings(Integer monthlySavings) {
		this.monthlySavings = monthlySavings;
	}

	public Float getSavingsRate() {
		return this.savingsRate;
	}

	public void setSavingsRate(Float savingsRate) {
		this.savingsRate = savingsRate;
	}

	public Integer getTotalCurrentFinancialAssets() {
		return this.totalCurrentFinancialAssets;
	}

	public void setTotalCurrentFinancialAssets(
			Integer totalCurrentFinancialAssets) {
		this.totalCurrentFinancialAssets = totalCurrentFinancialAssets;
	}

	public Integer getExpectedRiskScoreId() {
		return this.expectedRiskScoreId;
	}

	public void setExpectedRiskScoreId(Integer expectedRiskScoreId) {
		this.expectedRiskScoreId = expectedRiskScoreId;
	}

}
