package com.gtl.mmf.entity;
// Generated Jul 19, 2016 12:35:12 AM by Hibernate Tools 3.4.0.CR1

/**
 * FpMiscAssumptionsTb generated by hbm2java
 */
public class FpMiscAssumptionsTb implements java.io.Serializable {

	private Integer id;
	private Integer assumptionId;
	private String customerId;
	private Integer retirementAge;
	private Integer lifeExpectancy;
	private Float amountInvestedToMmf;
	private Float rateOfGrowthOfFd;
	private Float longTermInflationExpectation;
	private Float postRetirementRecurringExpense;

	public FpMiscAssumptionsTb() {
	}

	public FpMiscAssumptionsTb(Integer assumptionId, String customerId,
			Integer retirementAge, Integer lifeExpectancy,
			Float amountInvestedToMmf, Float rateOfGrowthOfFd,
			Float longTermInflationExpectation,
			Float postRetirementRecurringExpense) {
		this.assumptionId = assumptionId;
		this.customerId = customerId;
		this.retirementAge = retirementAge;
		this.lifeExpectancy = lifeExpectancy;
		this.amountInvestedToMmf = amountInvestedToMmf;
		this.rateOfGrowthOfFd = rateOfGrowthOfFd;
		this.longTermInflationExpectation = longTermInflationExpectation;
		this.postRetirementRecurringExpense = postRetirementRecurringExpense;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAssumptionId() {
		return this.assumptionId;
	}

	public void setAssumptionId(Integer assumptionId) {
		this.assumptionId = assumptionId;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public Integer getRetirementAge() {
		return this.retirementAge;
	}

	public void setRetirementAge(Integer retirementAge) {
		this.retirementAge = retirementAge;
	}

	public Integer getLifeExpectancy() {
		return this.lifeExpectancy;
	}

	public void setLifeExpectancy(Integer lifeExpectancy) {
		this.lifeExpectancy = lifeExpectancy;
	}

	public Float getAmountInvestedToMmf() {
		return this.amountInvestedToMmf;
	}

	public void setAmountInvestedToMmf(Float amountInvestedToMmf) {
		this.amountInvestedToMmf = amountInvestedToMmf;
	}

	public Float getRateOfGrowthOfFd() {
		return this.rateOfGrowthOfFd;
	}

	public void setRateOfGrowthOfFd(Float rateOfGrowthOfFd) {
		this.rateOfGrowthOfFd = rateOfGrowthOfFd;
	}

	public Float getLongTermInflationExpectation() {
		return this.longTermInflationExpectation;
	}

	public void setLongTermInflationExpectation(
			Float longTermInflationExpectation) {
		this.longTermInflationExpectation = longTermInflationExpectation;
	}

	public Float getPostRetirementRecurringExpense() {
		return this.postRetirementRecurringExpense;
	}

	public void setPostRetirementRecurringExpense(
			Float postRetirementRecurringExpense) {
		this.postRetirementRecurringExpense = postRetirementRecurringExpense;
	}

}
