package com.gtl.mmf.entity;
// Generated Jul 15, 2016 5:29:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * FpOutstandingloansUserInputsTb generated by hbm2java
 */
public class FpOutstandingloansUserInputsTb implements java.io.Serializable {

	private Integer id;
	private String customerId;
	private String loanDescription;
	private Integer loanAmount;
	private Integer monthlyEmiAmount;
	private Integer finalYear;

	public FpOutstandingloansUserInputsTb() {
	}

	public FpOutstandingloansUserInputsTb(String customerId,
			String loanDescription, Integer loanAmount,
			Integer monthlyEmiAmount, Integer finalYear) {
		this.customerId = customerId;
		this.loanDescription = loanDescription;
		this.loanAmount = loanAmount;
		this.monthlyEmiAmount = monthlyEmiAmount;
		this.finalYear = finalYear;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getLoanDescription() {
		return this.loanDescription;
	}

	public void setLoanDescription(String loanDescription) {
		this.loanDescription = loanDescription;
	}

	public Integer getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(Integer loanAmount) {
		this.loanAmount = loanAmount;
	}

	public Integer getMonthlyEmiAmount() {
		return this.monthlyEmiAmount;
	}

	public void setMonthlyEmiAmount(Integer monthlyEmiAmount) {
		this.monthlyEmiAmount = monthlyEmiAmount;
	}

	public Integer getFinalYear() {
		return this.finalYear;
	}

	public void setFinalYear(Integer finalYear) {
		this.finalYear = finalYear;
	}

}
