package com.gtl.mmf.entity;
// Generated 28 Apr, 2016 2:16:42 PM by Hibernate Tools 3.6.0

/**
 * IfcMicrMappingTb generated by hbm2java
 */
public class IfcMicrMappingTb implements java.io.Serializable {

    private Integer id;
    private String bank;
    private String ifsc;
    private String micr;
    private String branch;
    private String address;
    private String contact;
    private String city;
    private String district;
    private String state;

    public IfcMicrMappingTb() {
    }

    public IfcMicrMappingTb(String bank, String ifsc, String micr, String branch, String address, String contact, String city, String district, String state) {
        this.bank = bank;
        this.ifsc = ifsc;
        this.micr = micr;
        this.branch = branch;
        this.address = address;
        this.contact = contact;
        this.city = city;
        this.district = district;
        this.state = state;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIfsc() {
        return this.ifsc;
    }

    public void setIfsc(String ifsc) {
        this.ifsc = ifsc;
    }

    public String getMicr() {
        return this.micr;
    }

    public void setMicr(String micr) {
        this.micr = micr;
    }

    public String getBank() {
        return bank;
    }

    public void setBank(String bank) {
        this.bank = bank;
    }

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }
    
}
