package com.gtl.mmf.entity;
// Generated Dec 22, 2014 4:17:26 PM by Hibernate Tools 3.2.1.GA



/**
 * IncomerangeTb generated by hbm2java
 */
public class IncomerangeTb  implements java.io.Serializable {


     private int id;
     private Integer key;
     private String incomerange;

    public IncomerangeTb() {
    }

	
    public IncomerangeTb(int id) {
        this.id = id;
    }
    public IncomerangeTb(int id, Integer key, String incomerange) {
       this.id = id;
       this.key = key;
       this.incomerange = incomerange;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getKey() {
        return this.key;
    }
    
    public void setKey(Integer key) {
        this.key = key;
    }
    public String getIncomerange() {
        return this.incomerange;
    }
    
    public void setIncomerange(String incomerange) {
        this.incomerange = incomerange;
    }




}


