package com.gtl.mmf.entity;
// Generated Oct 22, 2014 3:04:46 PM by Hibernate Tools 3.6.0

/**
 * IndexNseTb generated by hbm2java
 */
public class IndexNseTb implements java.io.Serializable {

    private Integer id;
    private String symbol;
    private String isin;

    public IndexNseTb() {
    }

    public IndexNseTb(String symbol, String isin) {
        this.symbol = symbol;
        this.isin = isin;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSymbol() {
        return this.symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getIsin() {
        return isin;
    }

    public void setIsin(String isin) {
        this.isin = isin;
    }

}
