package com.gtl.mmf.entity;
// Generated Jul 2, 2015 11:31:50 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * InvestorNomineeDetailsTb generated by hbm2java
 */
public class InvestorNomineeDetailsTb implements java.io.Serializable {

    private Integer nomineeDetailsId;
    private String registrationId;
    private String nameNominee;
    private String relationshipApplicant;
    private Date dobNominee;
    private String addressNominee;
    private String placeNominee;
    private String pincodeNominee;
    private String stateNominee;
    private String countryNominee;
    private String telOfficeNominee;
    private String telResidenceNominee;
    private String faxNominee;
    private String mobileNominee;
    private String emailNominee;
    private String panNomine;
    private Boolean nomineeMinor;
    private Date dobNomineeMinor;
    private String nameGuardianNominee;
    private String addressNomineeMinor;
    private String placeNomineeMinor;
    private String pincodeNomineeMinor;
    private String stateNomineeMinor;
    private String countryNomineeMinor;
    private String telOfficeNomineeMinor;
    private String telResidenceNomineeMinor;
    private String faxNomineeMinor;
    private String mobileNomineeMinor;
    private String emailNomineeMinor;
    private String relationshipGuardianMinor;
    private String nomineeProof;
    private String nomineeAadhar;
    private String minorProof;
    private String minorPan;
    private String minorAadhar;

    public InvestorNomineeDetailsTb() {
    }

    public InvestorNomineeDetailsTb(String registrationId, String nameNominee) {
        this.registrationId = registrationId;
        this.nameNominee = nameNominee;
    }

    public InvestorNomineeDetailsTb(String registrationId, String nameNominee, String relationshipApplicant, Date dobNominee, String addressNominee, String placeNominee, String pincodeNominee, String stateNominee, String countryNominee, String telOfficeNominee, String telResidenceNominee, String faxNominee, String mobileNominee, String emailNominee, String panNomine, Boolean nomineeMinor, Date dobNomineeMinor, String nameGuardianNominee, String addressNomineeMinor, String placeNomineeMinor, String pincodeNomineeMinor, String stateNomineeMinor, String countryNomineeMinor, String telOfficeNomineeMinor, String telResidenceNomineeMinor, String faxNomineeMinor, String mobileNomineeMinor, String emailNomineeMinor, String relationshipGuardianMinor, String nomineeProof, String nomineeAadhar, String minorProof, String minorPan, String minorAadhar) {
        this.registrationId = registrationId;
        this.nameNominee = nameNominee;
        this.relationshipApplicant = relationshipApplicant;
        this.dobNominee = dobNominee;
        this.addressNominee = addressNominee;
        this.placeNominee = placeNominee;
        this.pincodeNominee = pincodeNominee;
        this.stateNominee = stateNominee;
        this.countryNominee = countryNominee;
        this.telOfficeNominee = telOfficeNominee;
        this.telResidenceNominee = telResidenceNominee;
        this.faxNominee = faxNominee;
        this.mobileNominee = mobileNominee;
        this.emailNominee = emailNominee;
        this.panNomine = panNomine;
        this.nomineeMinor = nomineeMinor;
        this.dobNomineeMinor = dobNomineeMinor;
        this.nameGuardianNominee = nameGuardianNominee;
        this.addressNomineeMinor = addressNomineeMinor;
        this.placeNomineeMinor = placeNomineeMinor;
        this.pincodeNomineeMinor = pincodeNomineeMinor;
        this.stateNomineeMinor = stateNomineeMinor;
        this.countryNomineeMinor = countryNomineeMinor;
        this.telOfficeNomineeMinor = telOfficeNomineeMinor;
        this.telResidenceNomineeMinor = telResidenceNomineeMinor;
        this.faxNomineeMinor = faxNomineeMinor;
        this.mobileNomineeMinor = mobileNomineeMinor;
        this.emailNomineeMinor = emailNomineeMinor;
        this.relationshipGuardianMinor = relationshipGuardianMinor;
        this.nomineeProof = nomineeProof;
        this.nomineeAadhar = nomineeAadhar;
        this.minorProof = minorProof;
        this.minorPan = minorPan;
        this.minorAadhar = minorAadhar;
    }

    public Integer getNomineeDetailsId() {
        return this.nomineeDetailsId;
    }

    public void setNomineeDetailsId(Integer nomineeDetailsId) {
        this.nomineeDetailsId = nomineeDetailsId;
    }

    public String getRegistrationId() {
        return this.registrationId;
    }

    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }

    public String getNameNominee() {
        return this.nameNominee;
    }

    public void setNameNominee(String nameNominee) {
        this.nameNominee = nameNominee;
    }

    public String getRelationshipApplicant() {
        return this.relationshipApplicant;
    }

    public void setRelationshipApplicant(String relationshipApplicant) {
        this.relationshipApplicant = relationshipApplicant;
    }

    public Date getDobNominee() {
        return this.dobNominee;
    }

    public void setDobNominee(Date dobNominee) {
        this.dobNominee = dobNominee;
    }

    public String getAddressNominee() {
        return this.addressNominee;
    }

    public void setAddressNominee(String addressNominee) {
        this.addressNominee = addressNominee;
    }

    public String getPlaceNominee() {
        return this.placeNominee;
    }

    public void setPlaceNominee(String placeNominee) {
        this.placeNominee = placeNominee;
    }

    public String getPincodeNominee() {
        return this.pincodeNominee;
    }

    public void setPincodeNominee(String pincodeNominee) {
        this.pincodeNominee = pincodeNominee;
    }

    public String getStateNominee() {
        return this.stateNominee;
    }

    public void setStateNominee(String stateNominee) {
        this.stateNominee = stateNominee;
    }

    public String getCountryNominee() {
        return this.countryNominee;
    }

    public void setCountryNominee(String countryNominee) {
        this.countryNominee = countryNominee;
    }

    public String getTelOfficeNominee() {
        return this.telOfficeNominee;
    }

    public void setTelOfficeNominee(String telOfficeNominee) {
        this.telOfficeNominee = telOfficeNominee;
    }

    public String getTelResidenceNominee() {
        return this.telResidenceNominee;
    }

    public void setTelResidenceNominee(String telResidenceNominee) {
        this.telResidenceNominee = telResidenceNominee;
    }

    public String getFaxNominee() {
        return this.faxNominee;
    }

    public void setFaxNominee(String faxNominee) {
        this.faxNominee = faxNominee;
    }

    public String getMobileNominee() {
        return this.mobileNominee;
    }

    public void setMobileNominee(String mobileNominee) {
        this.mobileNominee = mobileNominee;
    }

    public String getEmailNominee() {
        return this.emailNominee;
    }

    public void setEmailNominee(String emailNominee) {
        this.emailNominee = emailNominee;
    }

    public String getPanNomine() {
        return this.panNomine;
    }

    public void setPanNomine(String panNomine) {
        this.panNomine = panNomine;
    }

    public Boolean getNomineeMinor() {
        return this.nomineeMinor;
    }

    public void setNomineeMinor(Boolean nomineeMinor) {
        this.nomineeMinor = nomineeMinor;
    }

    public Date getDobNomineeMinor() {
        return this.dobNomineeMinor;
    }

    public void setDobNomineeMinor(Date dobNomineeMinor) {
        this.dobNomineeMinor = dobNomineeMinor;
    }

    public String getNameGuardianNominee() {
        return this.nameGuardianNominee;
    }

    public void setNameGuardianNominee(String nameGuardianNominee) {
        this.nameGuardianNominee = nameGuardianNominee;
    }

    public String getAddressNomineeMinor() {
        return this.addressNomineeMinor;
    }

    public void setAddressNomineeMinor(String addressNomineeMinor) {
        this.addressNomineeMinor = addressNomineeMinor;
    }

    public String getPlaceNomineeMinor() {
        return this.placeNomineeMinor;
    }

    public void setPlaceNomineeMinor(String placeNomineeMinor) {
        this.placeNomineeMinor = placeNomineeMinor;
    }

    public String getPincodeNomineeMinor() {
        return this.pincodeNomineeMinor;
    }

    public void setPincodeNomineeMinor(String pincodeNomineeMinor) {
        this.pincodeNomineeMinor = pincodeNomineeMinor;
    }

    public String getStateNomineeMinor() {
        return this.stateNomineeMinor;
    }

    public void setStateNomineeMinor(String stateNomineeMinor) {
        this.stateNomineeMinor = stateNomineeMinor;
    }

    public String getCountryNomineeMinor() {
        return this.countryNomineeMinor;
    }

    public void setCountryNomineeMinor(String countryNomineeMinor) {
        this.countryNomineeMinor = countryNomineeMinor;
    }

    public String getTelOfficeNomineeMinor() {
        return this.telOfficeNomineeMinor;
    }

    public void setTelOfficeNomineeMinor(String telOfficeNomineeMinor) {
        this.telOfficeNomineeMinor = telOfficeNomineeMinor;
    }

    public String getTelResidenceNomineeMinor() {
        return this.telResidenceNomineeMinor;
    }

    public void setTelResidenceNomineeMinor(String telResidenceNomineeMinor) {
        this.telResidenceNomineeMinor = telResidenceNomineeMinor;
    }

    public String getFaxNomineeMinor() {
        return this.faxNomineeMinor;
    }

    public void setFaxNomineeMinor(String faxNomineeMinor) {
        this.faxNomineeMinor = faxNomineeMinor;
    }

    public String getMobileNomineeMinor() {
        return this.mobileNomineeMinor;
    }

    public void setMobileNomineeMinor(String mobileNomineeMinor) {
        this.mobileNomineeMinor = mobileNomineeMinor;
    }

    public String getEmailNomineeMinor() {
        return this.emailNomineeMinor;
    }

    public void setEmailNomineeMinor(String emailNomineeMinor) {
        this.emailNomineeMinor = emailNomineeMinor;
    }

    public String getRelationshipGuardianMinor() {
        return this.relationshipGuardianMinor;
    }

    public void setRelationshipGuardianMinor(String relationshipGuardianMinor) {
        this.relationshipGuardianMinor = relationshipGuardianMinor;
    }

    public String getNomineeProof() {
        return nomineeProof;
    }

    public void setNomineeProof(String nomineeProof) {
        this.nomineeProof = nomineeProof;
    }

    public String getNomineeAadhar() {
        return nomineeAadhar;
    }

    public void setNomineeAadhar(String nomineeAadhar) {
        this.nomineeAadhar = nomineeAadhar;
    }

    public String getMinorProof() {
        return minorProof;
    }

    public void setMinorProof(String minorProof) {
        this.minorProof = minorProof;
    }

    public String getMinorPan() {
        return minorPan;
    }

    public void setMinorPan(String minorPan) {
        this.minorPan = minorPan;
    }

    public String getMinorAadhar() {
        return minorAadhar;
    }

    public void setMinorAadhar(String minorAadhar) {
        this.minorAadhar = minorAadhar;
    }

    
}
