package com.gtl.mmf.entity;
// Generated 21 Sep, 2015 6:02:51 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * KitAllocationTb generated by hbm2java
 */
public class KitAllocationTb  implements java.io.Serializable {


     private Integer id;
     private Integer fromValue;
     private Integer toValue;
     private Date allocationDate;
     private String kitStatus;

    public KitAllocationTb() {
    }

    public KitAllocationTb(Integer fromValue, Integer toValue, Date allocationDate, String kitStatus) {
       this.fromValue = fromValue;
       this.toValue = toValue;
       this.allocationDate = allocationDate;
       this.kitStatus = kitStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getFromValue() {
        return this.fromValue;
    }
    
    public void setFromValue(Integer fromValue) {
        this.fromValue = fromValue;
    }
    public Integer getToValue() {
        return this.toValue;
    }
    
    public void setToValue(Integer toValue) {
        this.toValue = toValue;
    }
    public Date getAllocationDate() {
        return this.allocationDate;
    }
    
    public void setAllocationDate(Date allocationDate) {
        this.allocationDate = allocationDate;
    }
    public String getKitStatus() {
        return this.kitStatus;
    }
    
    public void setKitStatus(String kitStatus) {
        this.kitStatus = kitStatus;
    }
    
}


