package com.gtl.mmf.entity;
// Generated Oct 16, 2014 2:18:16 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * MasterSecurityClassificationTb generated by hbm2java
 */
public class MasterSecurityClassificationTb  implements java.io.Serializable {


     private Integer id;
     private String amc;
     private String codeNo;
     private String schemeName;
     private String schemeType;
     private String schemeCategory;
     private String schemeNavName;
     private String schemeMinimumAmount;
     private Date launchDate;
     private Date closureDDate;
     private String closedFlag;
     private String schemeLoad;
     private String isinDivReinvestment;
     private String isinDivPayout;
     private String isinGrowth;
     private String mmfClassification;

    public MasterSecurityClassificationTb() {
    }

    public MasterSecurityClassificationTb(String amc, String codeNo, String schemeName, String schemeType, String schemeCategory, String schemeNavName, String schemeMinimumAmount, Date launchDate, Date closureDDate, String closedFlag, String schemeLoad, String isinDivReinvestment, String isinDivPayout, String isinGrowth, String mmfClassification) {
       this.amc = amc;
       this.codeNo = codeNo;
       this.schemeName = schemeName;
       this.schemeType = schemeType;
       this.schemeCategory = schemeCategory;
       this.schemeNavName = schemeNavName;
       this.schemeMinimumAmount = schemeMinimumAmount;
       this.launchDate = launchDate;
       this.closureDDate = closureDDate;
       this.closedFlag = closedFlag;
       this.schemeLoad = schemeLoad;
       this.isinDivReinvestment = isinDivReinvestment;
       this.isinDivPayout = isinDivPayout;
       this.isinGrowth = isinGrowth;
       this.mmfClassification = mmfClassification;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAmc() {
        return this.amc;
    }
    
    public void setAmc(String amc) {
        this.amc = amc;
    }
    public String getCodeNo() {
        return this.codeNo;
    }
    
    public void setCodeNo(String codeNo) {
        this.codeNo = codeNo;
    }
    public String getSchemeName() {
        return this.schemeName;
    }
    
    public void setSchemeName(String schemeName) {
        this.schemeName = schemeName;
    }
    public String getSchemeType() {
        return this.schemeType;
    }
    
    public void setSchemeType(String schemeType) {
        this.schemeType = schemeType;
    }
    public String getSchemeCategory() {
        return this.schemeCategory;
    }
    
    public void setSchemeCategory(String schemeCategory) {
        this.schemeCategory = schemeCategory;
    }
    public String getSchemeNavName() {
        return this.schemeNavName;
    }
    
    public void setSchemeNavName(String schemeNavName) {
        this.schemeNavName = schemeNavName;
    }
    public String getSchemeMinimumAmount() {
        return this.schemeMinimumAmount;
    }
    
    public void setSchemeMinimumAmount(String schemeMinimumAmount) {
        this.schemeMinimumAmount = schemeMinimumAmount;
    }
    public Date getLaunchDate() {
        return this.launchDate;
    }
    
    public void setLaunchDate(Date launchDate) {
        this.launchDate = launchDate;
    }
    public Date getClosureDDate() {
        return this.closureDDate;
    }
    
    public void setClosureDDate(Date closureDDate) {
        this.closureDDate = closureDDate;
    }
    public String getClosedFlag() {
        return this.closedFlag;
    }
    
    public void setClosedFlag(String closedFlag) {
        this.closedFlag = closedFlag;
    }
    public String getSchemeLoad() {
        return this.schemeLoad;
    }
    
    public void setSchemeLoad(String schemeLoad) {
        this.schemeLoad = schemeLoad;
    }
    public String getIsinDivReinvestment() {
        return this.isinDivReinvestment;
    }
    
    public void setIsinDivReinvestment(String isinDivReinvestment) {
        this.isinDivReinvestment = isinDivReinvestment;
    }
    public String getIsinDivPayout() {
        return this.isinDivPayout;
    }
    
    public void setIsinDivPayout(String isinDivPayout) {
        this.isinDivPayout = isinDivPayout;
    }
    public String getIsinGrowth() {
        return this.isinGrowth;
    }
    
    public void setIsinGrowth(String isinGrowth) {
        this.isinGrowth = isinGrowth;
    }
    public String getMmfClassification() {
        return this.mmfClassification;
    }
    
    public void setMmfClassification(String mmfClassification) {
        this.mmfClassification = mmfClassification;
    }




}


