package com.gtl.mmf.entity;
// Generated 2 May, 2016 5:49:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MasterPortfolioStyleTb generated by hbm2java
 */
public class MasterPortfolioStyleTb  implements java.io.Serializable {


     private Integer portfolioStyleId;
     private String portfolioStyle;
     private String portfolioStyleType;
     private Integer minScore;
     private Integer maxScore;
     private Set masterPortfolioTypeTbs = new HashSet(0);

    public MasterPortfolioStyleTb() {
    }

    public MasterPortfolioStyleTb(String portfolioStyle, String portfolioStyleType, Integer minScore, Integer maxScore, Set masterPortfolioTypeTbs) {
       this.portfolioStyle = portfolioStyle;
       this.portfolioStyleType = portfolioStyleType;
       this.minScore = minScore;
       this.maxScore = maxScore;
       this.masterPortfolioTypeTbs = masterPortfolioTypeTbs;
    }
   
    public Integer getPortfolioStyleId() {
        return this.portfolioStyleId;
    }
    
    public void setPortfolioStyleId(Integer portfolioStyleId) {
        this.portfolioStyleId = portfolioStyleId;
    }
    public String getPortfolioStyle() {
        return this.portfolioStyle;
    }
    
    public void setPortfolioStyle(String portfolioStyle) {
        this.portfolioStyle = portfolioStyle;
    }
    public String getPortfolioStyleType() {
        return this.portfolioStyleType;
    }
    
    public void setPortfolioStyleType(String portfolioStyleType) {
        this.portfolioStyleType = portfolioStyleType;
    }
    public Integer getMinScore() {
        return this.minScore;
    }
    
    public void setMinScore(Integer minScore) {
        this.minScore = minScore;
    }
    public Integer getMaxScore() {
        return this.maxScore;
    }
    
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }
    public Set getMasterPortfolioTypeTbs() {
        return this.masterPortfolioTypeTbs;
    }
    
    public void setMasterPortfolioTypeTbs(Set masterPortfolioTypeTbs) {
        this.masterPortfolioTypeTbs = masterPortfolioTypeTbs;
    }




}


