package com.gtl.mmf.entity;
// Generated Jun 19, 2015 1:54:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MasterAdvisorQualificationTb generated by hbm2java
 */
public class MasterAdvisorQualificationTb  implements java.io.Serializable {


     private Integer advId;
     private MasterApplicantTb masterApplicantTb;
     private String registrationId;
     private String primaryQualificationDegree;
     private String primaryQualificationInstitute;
     private String primaryQualificationYear;
     private String primaryQualificationId;
     private String secondaryQualificationDegree;
     private String secondaryQualificationInstitute;
     private String secondaryQualificationYear;
     private String secondaryQualificationId;
     private String tertiaryQualificationDegree;
     private String tertiaryQualificationInstitute;
     private String tertiaryQualificationYear;
     private String tertiaryQualificationId;
     private Date validitySebiCertificate;
     private String sebiCertificatePath;
     
     private String advPicPath;
     private String oneLineDesc;
     private String aboutMe;
     private String myInvestmentStrategy;

    public MasterAdvisorQualificationTb() {
    }

	
    public MasterAdvisorQualificationTb(MasterApplicantTb masterApplicantTb, String registrationId) {
        this.masterApplicantTb = masterApplicantTb;
        this.registrationId = registrationId;
    }
    public MasterAdvisorQualificationTb(MasterApplicantTb masterApplicantTb, String registrationId, String primaryQualificationDegree, String primaryQualificationInstitute, String primaryQualificationYear, String primaryQualificationId, String secondaryQualificationDegree, String secondaryQualificationInstitute, String secondaryQualificationYear, String secondaryQualificationId, String tertiaryQualificationDegree, String tertiaryQualificationInstitute, String tertiaryQualificationYear, String tertiaryQualificationId, Date validitySebiCertificate, String sebiCertificatePath ,String advPicPath, String oneLineDesc, String aboutMe, String myInvestmentStrategy) {
       this.masterApplicantTb = masterApplicantTb;
       this.registrationId = registrationId;
       this.primaryQualificationDegree = primaryQualificationDegree;
       this.primaryQualificationInstitute = primaryQualificationInstitute;
       this.primaryQualificationYear = primaryQualificationYear;
       this.primaryQualificationId = primaryQualificationId;
       this.secondaryQualificationDegree = secondaryQualificationDegree;
       this.secondaryQualificationInstitute = secondaryQualificationInstitute;
       this.secondaryQualificationYear = secondaryQualificationYear;
       this.secondaryQualificationId = secondaryQualificationId;
       this.tertiaryQualificationDegree = tertiaryQualificationDegree;
       this.tertiaryQualificationInstitute = tertiaryQualificationInstitute;
       this.tertiaryQualificationYear = tertiaryQualificationYear;
       this.tertiaryQualificationId = tertiaryQualificationId;
       this.validitySebiCertificate = validitySebiCertificate;
       this.sebiCertificatePath = sebiCertificatePath;
       this.advPicPath = advPicPath ;
       this.oneLineDesc = oneLineDesc ;
       this.aboutMe = aboutMe ;
       this.myInvestmentStrategy = myInvestmentStrategy ;
    }
   
    public Integer getAdvId() {
        return this.advId;
    }
    
    public void setAdvId(Integer advId) {
        this.advId = advId;
    }
    public MasterApplicantTb getMasterApplicantTb() {
        return this.masterApplicantTb;
    }
    
    public void setMasterApplicantTb(MasterApplicantTb masterApplicantTb) {
        this.masterApplicantTb = masterApplicantTb;
    }
    public String getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }
    public String getPrimaryQualificationDegree() {
        return this.primaryQualificationDegree;
    }
    
    public void setPrimaryQualificationDegree(String primaryQualificationDegree) {
        this.primaryQualificationDegree = primaryQualificationDegree;
    }
    public String getPrimaryQualificationInstitute() {
        return this.primaryQualificationInstitute;
    }
    
    public void setPrimaryQualificationInstitute(String primaryQualificationInstitute) {
        this.primaryQualificationInstitute = primaryQualificationInstitute;
    }
    public String getPrimaryQualificationYear() {
        return this.primaryQualificationYear;
    }
    
    public void setPrimaryQualificationYear(String primaryQualificationYear) {
        this.primaryQualificationYear = primaryQualificationYear;
    }
    public String getPrimaryQualificationId() {
        return this.primaryQualificationId;
    }
    
    public void setPrimaryQualificationId(String primaryQualificationId) {
        this.primaryQualificationId = primaryQualificationId;
    }
    public String getSecondaryQualificationDegree() {
        return this.secondaryQualificationDegree;
    }
    
    public void setSecondaryQualificationDegree(String secondaryQualificationDegree) {
        this.secondaryQualificationDegree = secondaryQualificationDegree;
    }
    public String getSecondaryQualificationInstitute() {
        return this.secondaryQualificationInstitute;
    }
    
    public void setSecondaryQualificationInstitute(String secondaryQualificationInstitute) {
        this.secondaryQualificationInstitute = secondaryQualificationInstitute;
    }
    public String getSecondaryQualificationYear() {
        return this.secondaryQualificationYear;
    }
    
    public void setSecondaryQualificationYear(String secondaryQualificationYear) {
        this.secondaryQualificationYear = secondaryQualificationYear;
    }
    public String getSecondaryQualificationId() {
        return this.secondaryQualificationId;
    }
    
    public void setSecondaryQualificationId(String secondaryQualificationId) {
        this.secondaryQualificationId = secondaryQualificationId;
    }
    public String getTertiaryQualificationDegree() {
        return this.tertiaryQualificationDegree;
    }
    
    public void setTertiaryQualificationDegree(String tertiaryQualificationDegree) {
        this.tertiaryQualificationDegree = tertiaryQualificationDegree;
    }
    public String getTertiaryQualificationInstitute() {
        return this.tertiaryQualificationInstitute;
    }
    
    public void setTertiaryQualificationInstitute(String tertiaryQualificationInstitute) {
        this.tertiaryQualificationInstitute = tertiaryQualificationInstitute;
    }
    public String getTertiaryQualificationYear() {
        return this.tertiaryQualificationYear;
    }
    
    public void setTertiaryQualificationYear(String tertiaryQualificationYear) {
        this.tertiaryQualificationYear = tertiaryQualificationYear;
    }
    public String getTertiaryQualificationId() {
        return this.tertiaryQualificationId;
    }
    
    public void setTertiaryQualificationId(String tertiaryQualificationId) {
        this.tertiaryQualificationId = tertiaryQualificationId;
    }
    public Date getValiditySebiCertificate() {
        return this.validitySebiCertificate;
    }
    
    public void setValiditySebiCertificate(Date validitySebiCertificate) {
        this.validitySebiCertificate = validitySebiCertificate;
    }
    public String getSebiCertificatePath() {
        return this.sebiCertificatePath;
    }
    
    public void setSebiCertificatePath(String sebiCertificatePath) {
        this.sebiCertificatePath = sebiCertificatePath;
    }


	public String getAdvPicPath() {
		return advPicPath;
	}


	public void setAdvPicPath(String advPicPath) {
		this.advPicPath = advPicPath;
	}


	public String getOneLineDesc() {
		return oneLineDesc;
	}


	public void setOneLineDesc(String oneLineDesc) {
		this.oneLineDesc = oneLineDesc;
	}


	public String getAboutMe() {
		return aboutMe;
	}


	public void setAboutMe(String aboutMe) {
		this.aboutMe = aboutMe;
	}


	public String getMyInvestmentStrategy() {
		return myInvestmentStrategy;
	}


	public void setMyInvestmentStrategy(String myInvestmentStrategy) {
		this.myInvestmentStrategy = myInvestmentStrategy;
	}




}


