package com.gtl.mmf.entity;
// Generated Jun 26, 2015 2:26:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MasterAdvisorTb generated by hbm2java
 */
public class MasterAdvisorTb  implements java.io.Serializable {


     private Integer advisorId;
     private MasterAdvisorQualificationTb masterAdvisorQualificationTb;
     private MasterApplicantTb masterApplicantTb;
     private String registrationId;
     private String email;
     private Short status;
     private Date statusDate;
     private String firstName;
     private String middleName;
     private String lastName;
     private String panNo;
     private String homeAddress1;
     private String homeAddress2;
     private String homeAddressCity;
     private String homeAddressPincode;
     private String homeAddressCountry;
     private String homeTelephone;
     private String mobile;
     private String workOrganization;
     private String jobTitle;
     private String workAddress1;
     private String workAddress2;
     private String workAddressCity;
     private String workAddressPincode;
     private String workAddressCountry;
     private String workTelephone;
     private String ifscCode;
     private String bankAccountNo;
     private String bankBalance;
     private String password;
     private String linkedinUser;
     private String linkedinPassword;
     private String linkedinMemberId;
     private String sebiCertificationNo;
     private String documentStatus;
     private Integer initLogin;
     private Boolean loggedIn;
     private String bankName;
     private String brokerAccountNo;
     private Double amount;
     private String workMobile;
     private Date dob;
     private boolean isActiveUser;
     private Boolean onlineDetailsubmites;
     private Boolean sebiCertificateValidated;
     private Boolean verificationCompleted;
     private Boolean accountActivated;
     private Boolean onlineDetailsSubmitted;
     private Boolean sebiCertificateValidated_1;
     private Boolean verificationCcompleted;
     private Boolean accountActivated_1;
     private Set customerAdvisorMappingTbs = new HashSet(0);
     private Set portfolioTbs = new HashSet(0);
     private Set advisorDetailsTbs = new HashSet(0);
     private Set customerPortfolioTbs = new HashSet(0);

    public MasterAdvisorTb() {
    }

	
    public MasterAdvisorTb(MasterAdvisorQualificationTb masterAdvisorQualificationTb, MasterApplicantTb masterApplicantTb, String registrationId, boolean isActiveUser) {
        this.masterAdvisorQualificationTb = masterAdvisorQualificationTb;
        this.masterApplicantTb = masterApplicantTb;
        this.registrationId = registrationId;
        this.isActiveUser = isActiveUser;
    }
    public MasterAdvisorTb(MasterAdvisorQualificationTb masterAdvisorQualificationTb, MasterApplicantTb masterApplicantTb, String registrationId, String email, Short status, Date statusDate, String firstName, String middleName, String lastName, String panNo, String homeAddress1, String homeAddress2, String homeAddressCity, String homeAddressPincode, String homeAddressCountry, String homeTelephone, String mobile, String workOrganization, String jobTitle, String workAddress1, String workAddress2, String workAddressCity, String workAddressPincode, String workAddressCountry, String workTelephone, String ifscCode, String bankAccountNo, String bankBalance, String password, String linkedinUser, String linkedinPassword, String linkedinMemberId, String sebiCertificationNo, String documentStatus, Integer initLogin, Boolean loggedIn, String bankName, String brokerAccountNo, Double amount, String workMobile, Date dob, boolean isActiveUser, Boolean onlineDetailsubmites, Boolean sebiCertificateValidated, Boolean verificationCompleted, Boolean accountActivated, Boolean onlineDetailsSubmitted, Boolean sebiCertificateValidated_1, Boolean verificationCcompleted, Boolean accountActivated_1, Set customerAdvisorMappingTbs, Set portfolioTbs, Set advisorDetailsTbs, Set customerPortfolioTbs) {
       this.masterAdvisorQualificationTb = masterAdvisorQualificationTb;
       this.masterApplicantTb = masterApplicantTb;
       this.registrationId = registrationId;
       this.email = email;
       this.status = status;
       this.statusDate = statusDate;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.panNo = panNo;
       this.homeAddress1 = homeAddress1;
       this.homeAddress2 = homeAddress2;
       this.homeAddressCity = homeAddressCity;
       this.homeAddressPincode = homeAddressPincode;
       this.homeAddressCountry = homeAddressCountry;
       this.homeTelephone = homeTelephone;
       this.mobile = mobile;
       this.workOrganization = workOrganization;
       this.jobTitle = jobTitle;
       this.workAddress1 = workAddress1;
       this.workAddress2 = workAddress2;
       this.workAddressCity = workAddressCity;
       this.workAddressPincode = workAddressPincode;
       this.workAddressCountry = workAddressCountry;
       this.workTelephone = workTelephone;
       this.ifscCode = ifscCode;
       this.bankAccountNo = bankAccountNo;
       this.bankBalance = bankBalance;
       this.password = password;
       this.linkedinUser = linkedinUser;
       this.linkedinPassword = linkedinPassword;
       this.linkedinMemberId = linkedinMemberId;
       this.sebiCertificationNo = sebiCertificationNo;
       this.documentStatus = documentStatus;
       this.initLogin = initLogin;
       this.loggedIn = loggedIn;
       this.bankName = bankName;
       this.brokerAccountNo = brokerAccountNo;
       this.amount = amount;
       this.workMobile = workMobile;
       this.dob = dob;
       this.isActiveUser = isActiveUser;
       this.onlineDetailsubmites = onlineDetailsubmites;
       this.sebiCertificateValidated = sebiCertificateValidated;
       this.verificationCompleted = verificationCompleted;
       this.accountActivated = accountActivated;
       this.onlineDetailsSubmitted = onlineDetailsSubmitted;
       this.sebiCertificateValidated_1 = sebiCertificateValidated_1;
       this.verificationCcompleted = verificationCcompleted;
       this.accountActivated_1 = accountActivated_1;
       this.customerAdvisorMappingTbs = customerAdvisorMappingTbs;
       this.portfolioTbs = portfolioTbs;
       this.advisorDetailsTbs = advisorDetailsTbs;
       this.customerPortfolioTbs = customerPortfolioTbs;
    }
   
    public Integer getAdvisorId() {
        return this.advisorId;
    }
    
    public void setAdvisorId(Integer advisorId) {
        this.advisorId = advisorId;
    }
    public MasterAdvisorQualificationTb getMasterAdvisorQualificationTb() {
        return this.masterAdvisorQualificationTb;
    }
    
    public void setMasterAdvisorQualificationTb(MasterAdvisorQualificationTb masterAdvisorQualificationTb) {
        this.masterAdvisorQualificationTb = masterAdvisorQualificationTb;
    }
    public MasterApplicantTb getMasterApplicantTb() {
        return this.masterApplicantTb;
    }
    
    public void setMasterApplicantTb(MasterApplicantTb masterApplicantTb) {
        this.masterApplicantTb = masterApplicantTb;
    }
    public String getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPanNo() {
        return this.panNo;
    }
    
    public void setPanNo(String panNo) {
        this.panNo = panNo;
    }
    public String getHomeAddress1() {
        return this.homeAddress1;
    }
    
    public void setHomeAddress1(String homeAddress1) {
        this.homeAddress1 = homeAddress1;
    }
    public String getHomeAddress2() {
        return this.homeAddress2;
    }
    
    public void setHomeAddress2(String homeAddress2) {
        this.homeAddress2 = homeAddress2;
    }
    public String getHomeAddressCity() {
        return this.homeAddressCity;
    }
    
    public void setHomeAddressCity(String homeAddressCity) {
        this.homeAddressCity = homeAddressCity;
    }
    public String getHomeAddressPincode() {
        return this.homeAddressPincode;
    }
    
    public void setHomeAddressPincode(String homeAddressPincode) {
        this.homeAddressPincode = homeAddressPincode;
    }
    public String getHomeAddressCountry() {
        return this.homeAddressCountry;
    }
    
    public void setHomeAddressCountry(String homeAddressCountry) {
        this.homeAddressCountry = homeAddressCountry;
    }
    public String getHomeTelephone() {
        return this.homeTelephone;
    }
    
    public void setHomeTelephone(String homeTelephone) {
        this.homeTelephone = homeTelephone;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getWorkOrganization() {
        return this.workOrganization;
    }
    
    public void setWorkOrganization(String workOrganization) {
        this.workOrganization = workOrganization;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getWorkAddress1() {
        return this.workAddress1;
    }
    
    public void setWorkAddress1(String workAddress1) {
        this.workAddress1 = workAddress1;
    }
    public String getWorkAddress2() {
        return this.workAddress2;
    }
    
    public void setWorkAddress2(String workAddress2) {
        this.workAddress2 = workAddress2;
    }
    public String getWorkAddressCity() {
        return this.workAddressCity;
    }
    
    public void setWorkAddressCity(String workAddressCity) {
        this.workAddressCity = workAddressCity;
    }
    public String getWorkAddressPincode() {
        return this.workAddressPincode;
    }
    
    public void setWorkAddressPincode(String workAddressPincode) {
        this.workAddressPincode = workAddressPincode;
    }
    public String getWorkAddressCountry() {
        return this.workAddressCountry;
    }
    
    public void setWorkAddressCountry(String workAddressCountry) {
        this.workAddressCountry = workAddressCountry;
    }
    public String getWorkTelephone() {
        return this.workTelephone;
    }
    
    public void setWorkTelephone(String workTelephone) {
        this.workTelephone = workTelephone;
    }
    public String getIfscCode() {
        return this.ifscCode;
    }
    
    public void setIfscCode(String ifscCode) {
        this.ifscCode = ifscCode;
    }
    public String getBankAccountNo() {
        return this.bankAccountNo;
    }
    
    public void setBankAccountNo(String bankAccountNo) {
        this.bankAccountNo = bankAccountNo;
    }
    public String getBankBalance() {
        return this.bankBalance;
    }
    
    public void setBankBalance(String bankBalance) {
        this.bankBalance = bankBalance;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLinkedinUser() {
        return this.linkedinUser;
    }
    
    public void setLinkedinUser(String linkedinUser) {
        this.linkedinUser = linkedinUser;
    }
    public String getLinkedinPassword() {
        return this.linkedinPassword;
    }
    
    public void setLinkedinPassword(String linkedinPassword) {
        this.linkedinPassword = linkedinPassword;
    }
    public String getLinkedinMemberId() {
        return this.linkedinMemberId;
    }
    
    public void setLinkedinMemberId(String linkedinMemberId) {
        this.linkedinMemberId = linkedinMemberId;
    }
    public String getSebiCertificationNo() {
        return this.sebiCertificationNo;
    }
    
    public void setSebiCertificationNo(String sebiCertificationNo) {
        this.sebiCertificationNo = sebiCertificationNo;
    }
    public String getDocumentStatus() {
        return this.documentStatus;
    }
    
    public void setDocumentStatus(String documentStatus) {
        this.documentStatus = documentStatus;
    }
    public Integer getInitLogin() {
        return this.initLogin;
    }
    
    public void setInitLogin(Integer initLogin) {
        this.initLogin = initLogin;
    }
    public Boolean getLoggedIn() {
        return this.loggedIn;
    }
    
    public void setLoggedIn(Boolean loggedIn) {
        this.loggedIn = loggedIn;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }
    public String getBrokerAccountNo() {
        return this.brokerAccountNo;
    }
    
    public void setBrokerAccountNo(String brokerAccountNo) {
        this.brokerAccountNo = brokerAccountNo;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getWorkMobile() {
        return this.workMobile;
    }
    
    public void setWorkMobile(String workMobile) {
        this.workMobile = workMobile;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public boolean isIsActiveUser() {
        return this.isActiveUser;
    }
    
    public void setIsActiveUser(boolean isActiveUser) {
        this.isActiveUser = isActiveUser;
    }
    public Boolean getOnlineDetailsubmites() {
        return this.onlineDetailsubmites;
    }
    
    public void setOnlineDetailsubmites(Boolean onlineDetailsubmites) {
        this.onlineDetailsubmites = onlineDetailsubmites;
    }
    public Boolean getSebiCertificateValidated() {
        return this.sebiCertificateValidated;
    }
    
    public void setSebiCertificateValidated(Boolean sebiCertificateValidated) {
        this.sebiCertificateValidated = sebiCertificateValidated;
    }
    public Boolean getVerificationCompleted() {
        return this.verificationCompleted;
    }
    
    public void setVerificationCompleted(Boolean verificationCompleted) {
        this.verificationCompleted = verificationCompleted;
    }
    public Boolean getAccountActivated() {
        return this.accountActivated;
    }
    
    public void setAccountActivated(Boolean accountActivated) {
        this.accountActivated = accountActivated;
    }
    public Boolean getOnlineDetailsSubmitted() {
        return this.onlineDetailsSubmitted;
    }
    
    public void setOnlineDetailsSubmitted(Boolean onlineDetailsSubmitted) {
        this.onlineDetailsSubmitted = onlineDetailsSubmitted;
    }
    public Boolean getSebiCertificateValidated_1() {
        return this.sebiCertificateValidated_1;
    }
    
    public void setSebiCertificateValidated_1(Boolean sebiCertificateValidated_1) {
        this.sebiCertificateValidated_1 = sebiCertificateValidated_1;
    }
    public Boolean getVerificationCcompleted() {
        return this.verificationCcompleted;
    }
    
    public void setVerificationCcompleted(Boolean verificationCcompleted) {
        this.verificationCcompleted = verificationCcompleted;
    }
    public Boolean getAccountActivated_1() {
        return this.accountActivated_1;
    }
    
    public void setAccountActivated_1(Boolean accountActivated_1) {
        this.accountActivated_1 = accountActivated_1;
    }
    public Set getCustomerAdvisorMappingTbs() {
        return this.customerAdvisorMappingTbs;
    }
    
    public void setCustomerAdvisorMappingTbs(Set customerAdvisorMappingTbs) {
        this.customerAdvisorMappingTbs = customerAdvisorMappingTbs;
    }
    public Set getPortfolioTbs() {
        return this.portfolioTbs;
    }
    
    public void setPortfolioTbs(Set portfolioTbs) {
        this.portfolioTbs = portfolioTbs;
    }
    public Set getAdvisorDetailsTbs() {
        return this.advisorDetailsTbs;
    }
    
    public void setAdvisorDetailsTbs(Set advisorDetailsTbs) {
        this.advisorDetailsTbs = advisorDetailsTbs;
    }
    public Set getCustomerPortfolioTbs() {
        return this.customerPortfolioTbs;
    }
    
    public void setCustomerPortfolioTbs(Set customerPortfolioTbs) {
        this.customerPortfolioTbs = customerPortfolioTbs;
    }




}


