package com.gtl.mmf.entity;
// Generated 2 May, 2016 5:49:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MasterPortfolioSizeTb generated by hbm2java
 */
public class MasterPortfolioSizeTb  implements java.io.Serializable {


     private Integer portfolioSizeId;
     private String portfolioSize;
     private Integer minAum;
     private Integer maxAum;
     private Set masterPortfolioTypeTbs = new HashSet(0);

    public MasterPortfolioSizeTb() {
    }

    public MasterPortfolioSizeTb(String portfolioSize, Integer minAum, Integer maxAum, Set masterPortfolioTypeTbs) {
       this.portfolioSize = portfolioSize;
       this.minAum = minAum;
       this.maxAum = maxAum;
       this.masterPortfolioTypeTbs = masterPortfolioTypeTbs;
    }
   
    public Integer getPortfolioSizeId() {
        return this.portfolioSizeId;
    }
    
    public void setPortfolioSizeId(Integer portfolioSizeId) {
        this.portfolioSizeId = portfolioSizeId;
    }
    public String getPortfolioSize() {
        return this.portfolioSize;
    }
    
    public void setPortfolioSize(String portfolioSize) {
        this.portfolioSize = portfolioSize;
    }
    public Integer getMinAum() {
        return this.minAum;
    }
    
    public void setMinAum(Integer minAum) {
        this.minAum = minAum;
    }
    public Integer getMaxAum() {
        return this.maxAum;
    }
    
    public void setMaxAum(Integer maxAum) {
        this.maxAum = maxAum;
    }
    public Set getMasterPortfolioTypeTbs() {
        return this.masterPortfolioTypeTbs;
    }
    
    public void setMasterPortfolioTypeTbs(Set masterPortfolioTypeTbs) {
        this.masterPortfolioTypeTbs = masterPortfolioTypeTbs;
    }




}


