package com.gtl.mmf.entity;
// Generated 3 May, 2016 4:34:43 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * MasterPortfolioTypeTb generated by hbm2java
 */
public class MasterPortfolioTypeTb implements java.io.Serializable {

    private Integer id;
    private MasterPortfolioSizeTb masterPortfolioSizeTb;
    private MasterPortfolioStyleTb masterPortfolioStyleTb;
    private Integer cash;
    private Integer gold;
    private Integer debt;
    private Integer equitiesIndex;
    private Integer equitiesBluechip;
    private Integer equitiesMidcap;
    private Integer equitiesSmallCap;
    private Integer fando;
    private Integer international;
    private Integer commodities;
    private Integer mutualFunds;
    private Integer rangeMinEquity;
    private Integer rangeMinCash;
    private Integer rangeMinGold;
    private Integer rangeMinDebt;
    private Integer rangeMinInternational;
    private Integer rangeMinFo;
    private Integer rangeMinMutualFunds;
    private Integer rangeMaxEquity;
    private Integer rangeMaxCash;
    private Integer rangeMaxGold;
    private Integer rangeMaxDebt;
    private Integer rangeMaxFo;
    private Integer rangeMaxInternational;
    private Integer rangeMaxMutualFunds;
    private Integer equityDiverisied;
    private Integer rangeMinEquityDiverisied;
    private Integer rangeMaxEquityDiverisied;
    private Integer midcap;
    private Integer rangeMinMicap;
    private Integer rangeMaxMidcap;
    private Integer balanced;
    private Integer rangeMinBalanced;
    private Integer rangeMaxBalanced;
    private Integer debtLiquid;
    private Integer rangeMinDebtLiquid;
    private Integer rangeMaxDebtLiquid;
    private Integer tax_planning;
    private Integer min_tax_planning;
    private Integer max_tax_planning;
    private Set portfolioTbs = new HashSet(0);
    private Set customerRiskProfileTbsForPortfolioStyle = new HashSet(0);
    private Set customerRiskProfileTbsForInitialPortfolioStyle = new HashSet(0);

    public MasterPortfolioTypeTb() {
    }

    public MasterPortfolioTypeTb(MasterPortfolioSizeTb masterPortfolioSizeTb, MasterPortfolioStyleTb masterPortfolioStyleTb, Integer cash, Integer gold, Integer debt, Integer equitiesIndex, Integer equitiesBluechip, Integer equitiesMidcap, Integer equitiesSmallCap, Integer fando, Integer international, Integer commodities, Integer mutualFunds, Integer rangeMinEquity, Integer rangeMinCash, Integer rangeMinGold, Integer rangeMinDebt, Integer rangeMinInternational, Integer rangeMinFo, Integer rangeMinMutualFunds, Integer rangeMaxEquity, Integer rangeMaxCash, Integer rangeMaxGold, Integer rangeMaxDebt, Integer rangeMaxFo, Integer rangeMaxInternational, Integer rangeMaxMutualFunds, Integer equityDiverisied, Integer rangeMinEquityDiverisied, Integer rangeMaxEquityDiverisied, Integer midcap, Integer rangeMinMicap, Integer rangeMaxMidcap, Integer balanced, Integer rangeMinBalanced, Integer rangeMaxBalanced, Integer debtLiquid, Integer rangeMinDebtLiquid, Integer rangeMaxDebtLiquid,Integer tax_planning, Integer Min_tax_planning,Integer max_tax_planning, Set portfolioTbs, Set customerRiskProfileTbsForPortfolioStyle, Set customerRiskProfileTbsForInitialPortfolioStyle) {
        this.masterPortfolioSizeTb = masterPortfolioSizeTb;
        this.masterPortfolioStyleTb = masterPortfolioStyleTb;
        this.cash = cash;
        this.gold = gold;
        this.debt = debt;
        this.equitiesIndex = equitiesIndex;
        this.equitiesBluechip = equitiesBluechip;
        this.equitiesMidcap = equitiesMidcap;
        this.equitiesSmallCap = equitiesSmallCap;
        this.fando = fando;
        this.international = international;
        this.commodities = commodities;
        this.mutualFunds = mutualFunds;
        this.rangeMinEquity = rangeMinEquity;
        this.rangeMinCash = rangeMinCash;
        this.rangeMinGold = rangeMinGold;
        this.rangeMinDebt = rangeMinDebt;
        this.rangeMinInternational = rangeMinInternational;
        this.rangeMinFo = rangeMinFo;
        this.rangeMinMutualFunds = rangeMinMutualFunds;
        this.rangeMaxEquity = rangeMaxEquity;
        this.rangeMaxCash = rangeMaxCash;
        this.rangeMaxGold = rangeMaxGold;
        this.rangeMaxDebt = rangeMaxDebt;
        this.rangeMaxFo = rangeMaxFo;
        this.rangeMaxInternational = rangeMaxInternational;
        this.rangeMaxMutualFunds = rangeMaxMutualFunds;
        this.equityDiverisied = equityDiverisied;
        this.rangeMinEquityDiverisied = rangeMinEquityDiverisied;
        this.rangeMaxEquityDiverisied = rangeMaxEquityDiverisied;
        this.midcap = midcap;
        this.rangeMinMicap = rangeMinMicap;
        this.rangeMaxMidcap = rangeMaxMidcap;
        this.balanced = balanced;
        this.rangeMinBalanced = rangeMinBalanced;
        this.rangeMaxBalanced = rangeMaxBalanced;
        this.debtLiquid = debtLiquid;
        this.rangeMinDebtLiquid = rangeMinDebtLiquid;
        this.rangeMaxDebtLiquid = rangeMaxDebtLiquid;
        this.tax_planning = tax_planning;
        this.min_tax_planning = min_tax_planning;
        this.max_tax_planning = max_tax_planning;
        this.portfolioTbs = portfolioTbs;
        this.customerRiskProfileTbsForPortfolioStyle = customerRiskProfileTbsForPortfolioStyle;
        this.customerRiskProfileTbsForInitialPortfolioStyle = customerRiskProfileTbsForInitialPortfolioStyle;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public MasterPortfolioSizeTb getMasterPortfolioSizeTb() {
        return this.masterPortfolioSizeTb;
    }

    public void setMasterPortfolioSizeTb(MasterPortfolioSizeTb masterPortfolioSizeTb) {
        this.masterPortfolioSizeTb = masterPortfolioSizeTb;
    }

    public MasterPortfolioStyleTb getMasterPortfolioStyleTb() {
        return this.masterPortfolioStyleTb;
    }

    public void setMasterPortfolioStyleTb(MasterPortfolioStyleTb masterPortfolioStyleTb) {
        this.masterPortfolioStyleTb = masterPortfolioStyleTb;
    }

    public Integer getCash() {
        return this.cash;
    }

    public void setCash(Integer cash) {
        this.cash = cash;
    }

    public Integer getGold() {
        return this.gold;
    }

    public void setGold(Integer gold) {
        this.gold = gold;
    }

    public Integer getDebt() {
        return this.debt;
    }

    public void setDebt(Integer debt) {
        this.debt = debt;
    }

    public Integer getEquitiesIndex() {
        return this.equitiesIndex;
    }

    public void setEquitiesIndex(Integer equitiesIndex) {
        this.equitiesIndex = equitiesIndex;
    }

    public Integer getEquitiesBluechip() {
        return this.equitiesBluechip;
    }

    public void setEquitiesBluechip(Integer equitiesBluechip) {
        this.equitiesBluechip = equitiesBluechip;
    }

    public Integer getEquitiesMidcap() {
        return this.equitiesMidcap;
    }

    public void setEquitiesMidcap(Integer equitiesMidcap) {
        this.equitiesMidcap = equitiesMidcap;
    }

    public Integer getEquitiesSmallCap() {
        return this.equitiesSmallCap;
    }

    public void setEquitiesSmallCap(Integer equitiesSmallCap) {
        this.equitiesSmallCap = equitiesSmallCap;
    }

    public Integer getFando() {
        return this.fando;
    }

    public void setFando(Integer fando) {
        this.fando = fando;
    }

    public Integer getInternational() {
        return this.international;
    }

    public void setInternational(Integer international) {
        this.international = international;
    }

    public Integer getCommodities() {
        return this.commodities;
    }

    public void setCommodities(Integer commodities) {
        this.commodities = commodities;
    }

    public Integer getMutualFunds() {
        return this.mutualFunds;
    }

    public void setMutualFunds(Integer mutualFunds) {
        this.mutualFunds = mutualFunds;
    }

    public Integer getRangeMinEquity() {
        return this.rangeMinEquity;
    }

    public void setRangeMinEquity(Integer rangeMinEquity) {
        this.rangeMinEquity = rangeMinEquity;
    }

    public Integer getRangeMinCash() {
        return this.rangeMinCash;
    }

    public void setRangeMinCash(Integer rangeMinCash) {
        this.rangeMinCash = rangeMinCash;
    }

    public Integer getRangeMinGold() {
        return this.rangeMinGold;
    }

    public void setRangeMinGold(Integer rangeMinGold) {
        this.rangeMinGold = rangeMinGold;
    }

    public Integer getRangeMinDebt() {
        return this.rangeMinDebt;
    }

    public void setRangeMinDebt(Integer rangeMinDebt) {
        this.rangeMinDebt = rangeMinDebt;
    }

    public Integer getRangeMinInternational() {
        return this.rangeMinInternational;
    }

    public void setRangeMinInternational(Integer rangeMinInternational) {
        this.rangeMinInternational = rangeMinInternational;
    }

    public Integer getRangeMinFo() {
        return this.rangeMinFo;
    }

    public void setRangeMinFo(Integer rangeMinFo) {
        this.rangeMinFo = rangeMinFo;
    }

    public Integer getRangeMinMutualFunds() {
        return this.rangeMinMutualFunds;
    }

    public void setRangeMinMutualFunds(Integer rangeMinMutualFunds) {
        this.rangeMinMutualFunds = rangeMinMutualFunds;
    }

    public Integer getRangeMaxEquity() {
        return this.rangeMaxEquity;
    }

    public void setRangeMaxEquity(Integer rangeMaxEquity) {
        this.rangeMaxEquity = rangeMaxEquity;
    }

    public Integer getRangeMaxCash() {
        return this.rangeMaxCash;
    }

    public void setRangeMaxCash(Integer rangeMaxCash) {
        this.rangeMaxCash = rangeMaxCash;
    }

    public Integer getRangeMaxGold() {
        return this.rangeMaxGold;
    }

    public void setRangeMaxGold(Integer rangeMaxGold) {
        this.rangeMaxGold = rangeMaxGold;
    }

    public Integer getRangeMaxDebt() {
        return this.rangeMaxDebt;
    }

    public void setRangeMaxDebt(Integer rangeMaxDebt) {
        this.rangeMaxDebt = rangeMaxDebt;
    }

    public Integer getRangeMaxFo() {
        return this.rangeMaxFo;
    }

    public void setRangeMaxFo(Integer rangeMaxFo) {
        this.rangeMaxFo = rangeMaxFo;
    }

    public Integer getRangeMaxInternational() {
        return this.rangeMaxInternational;
    }

    public void setRangeMaxInternational(Integer rangeMaxInternational) {
        this.rangeMaxInternational = rangeMaxInternational;
    }

    public Integer getRangeMaxMutualFunds() {
        return this.rangeMaxMutualFunds;
    }

    public void setRangeMaxMutualFunds(Integer rangeMaxMutualFunds) {
        this.rangeMaxMutualFunds = rangeMaxMutualFunds;
    }

    public Integer getEquityDiverisied() {
        return this.equityDiverisied;
    }

    public void setEquityDiverisied(Integer equityDiverisied) {
        this.equityDiverisied = equityDiverisied;
    }

    public Integer getRangeMinEquityDiverisied() {
        return this.rangeMinEquityDiverisied;
    }

    public void setRangeMinEquityDiverisied(Integer rangeMinEquityDiverisied) {
        this.rangeMinEquityDiverisied = rangeMinEquityDiverisied;
    }

    public Integer getRangeMaxEquityDiverisied() {
        return this.rangeMaxEquityDiverisied;
    }

    public void setRangeMaxEquityDiverisied(Integer rangeMaxEquityDiverisied) {
        this.rangeMaxEquityDiverisied = rangeMaxEquityDiverisied;
    }

    public Integer getMidcap() {
        return this.midcap;
    }

    public void setMidcap(Integer midcap) {
        this.midcap = midcap;
    }

    public Integer getRangeMinMicap() {
        return this.rangeMinMicap;
    }

    public void setRangeMinMicap(Integer rangeMinMicap) {
        this.rangeMinMicap = rangeMinMicap;
    }

    public Integer getRangeMaxMidcap() {
        return this.rangeMaxMidcap;
    }

    public void setRangeMaxMidcap(Integer rangeMaxMidcap) {
        this.rangeMaxMidcap = rangeMaxMidcap;
    }

    public Integer getBalanced() {
        return this.balanced;
    }

    public void setBalanced(Integer balanced) {
        this.balanced = balanced;
    }

    public Integer getRangeMinBalanced() {
        return this.rangeMinBalanced;
    }

    public void setRangeMinBalanced(Integer rangeMinBalanced) {
        this.rangeMinBalanced = rangeMinBalanced;
    }

    public Integer getRangeMaxBalanced() {
        return this.rangeMaxBalanced;
    }

    public void setRangeMaxBalanced(Integer rangeMaxBalanced) {
        this.rangeMaxBalanced = rangeMaxBalanced;
    }

    public Integer getDebtLiquid() {
        return debtLiquid;
    }

    public void setDebtLiquid(Integer debtLiquid) {
        this.debtLiquid = debtLiquid;
    }

    public Integer getRangeMinDebtLiquid() {
        return rangeMinDebtLiquid;
    }

    public void setRangeMinDebtLiquid(Integer rangeMinDebtLiquid) {
        this.rangeMinDebtLiquid = rangeMinDebtLiquid;
    }

    public Integer getRangeMaxDebtLiquid() {
        return rangeMaxDebtLiquid;
    }

    public void setRangeMaxDebtLiquid(Integer rangeMaxDebtLiquid) {
        this.rangeMaxDebtLiquid = rangeMaxDebtLiquid;
    }

    public Set getPortfolioTbs() {
        return this.portfolioTbs;
    }

    public void setPortfolioTbs(Set portfolioTbs) {
        this.portfolioTbs = portfolioTbs;
    }

    public Set getCustomerRiskProfileTbsForPortfolioStyle() {
        return this.customerRiskProfileTbsForPortfolioStyle;
    }

    public void setCustomerRiskProfileTbsForPortfolioStyle(Set customerRiskProfileTbsForPortfolioStyle) {
        this.customerRiskProfileTbsForPortfolioStyle = customerRiskProfileTbsForPortfolioStyle;
    }

    public Set getCustomerRiskProfileTbsForInitialPortfolioStyle() {
        return this.customerRiskProfileTbsForInitialPortfolioStyle;
    }

    public void setCustomerRiskProfileTbsForInitialPortfolioStyle(Set customerRiskProfileTbsForInitialPortfolioStyle) {
        this.customerRiskProfileTbsForInitialPortfolioStyle = customerRiskProfileTbsForInitialPortfolioStyle;
    }

    public Integer getTax_planning() {
        return tax_planning;
    }

    public void setTax_planning(Integer tax_planning) {
        this.tax_planning = tax_planning;
    }

    public Integer getMin_tax_planning() {
        return min_tax_planning;
    }

    public void setMin_tax_planning(Integer min_tax_planning) {
        this.min_tax_planning = min_tax_planning;
    }

    public Integer getMax_tax_planning() {
        return max_tax_planning;
    }

    public void setMax_tax_planning(Integer max_tax_planning) {
        this.max_tax_planning = max_tax_planning;
    }
    

}
