package com.gtl.mmf.entity;
// Generated Oct 22, 2014 10:14:07 AM by Hibernate Tools 3.6.0

/**
 * MidcapBseTb generated by hbm2java
 */
public class MidcapBseTb implements java.io.Serializable {

    private Integer id;
    private String scripCode;
    private String companyName;
    private String isin;

    public MidcapBseTb() {
    }

    public MidcapBseTb(String scripCode, String companyName, String isin) {
        this.scripCode = scripCode;
        this.companyName = companyName;
        this.isin = isin;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getScripCode() {
        return this.scripCode;
    }

    public void setScripCode(String scripCode) {
        this.scripCode = scripCode;
    }

    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getIsin() {
        return isin;
    }

    public void setIsin(String isin) {
        this.isin = isin;
    }

}
