package com.gtl.mmf.entity;
// Generated 23 Sep, 2014 11:11:13 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * MmfDailyTxnSummaryTb generated by hbm2java
 */
public class MmfDailyTxnSummaryTb  implements java.io.Serializable {


     private Integer id;
     private Date trndate;
     private String tradecode;
     private String orderno;
     private String product;
     private String venueScriptCode;
     private String security;
     private String instrument;
     private String contract;
     private String buysell;
     private BigDecimal quantity;
     private BigDecimal price;
     private BigDecimal units;
     private BigDecimal volume;
     private BigDecimal brokerage;
     private BigDecimal othercharges;
     private String channel;
     private String euser;
     private Date lastupdatedon;

    public MmfDailyTxnSummaryTb() {
    }

    public MmfDailyTxnSummaryTb(Date trndate, String tradecode, String orderno, String product, String venueScriptCode, String security, String instrument, String contract, String buysell, BigDecimal quantity, BigDecimal price, BigDecimal units, BigDecimal volume, BigDecimal brokerage, BigDecimal othercharges, String channel, String euser, Date lastupdatedon) {
       this.trndate = trndate;
       this.tradecode = tradecode;
       this.orderno = orderno;
       this.product = product;
       this.venueScriptCode = venueScriptCode;
       this.security = security;
       this.instrument = instrument;
       this.contract = contract;
       this.buysell = buysell;
       this.quantity = quantity;
       this.price = price;
       this.units = units;
       this.volume = volume;
       this.brokerage = brokerage;
       this.othercharges = othercharges;
       this.channel = channel;
       this.euser = euser;
       this.lastupdatedon = lastupdatedon;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTrndate() {
        return this.trndate;
    }
    
    public void setTrndate(Date trndate) {
        this.trndate = trndate;
    }
    public String getTradecode() {
        return this.tradecode;
    }
    
    public void setTradecode(String tradecode) {
        this.tradecode = tradecode;
    }
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public String getVenueScriptCode() {
        return this.venueScriptCode;
    }
    
    public void setVenueScriptCode(String venueScriptCode) {
        this.venueScriptCode = venueScriptCode;
    }
    public String getSecurity() {
        return this.security;
    }
    
    public void setSecurity(String security) {
        this.security = security;
    }
    public String getInstrument() {
        return this.instrument;
    }
    
    public void setInstrument(String instrument) {
        this.instrument = instrument;
    }
    public String getContract() {
        return this.contract;
    }
    
    public void setContract(String contract) {
        this.contract = contract;
    }
    public String getBuysell() {
        return this.buysell;
    }
    
    public void setBuysell(String buysell) {
        this.buysell = buysell;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public BigDecimal getUnits() {
        return this.units;
    }
    
    public void setUnits(BigDecimal units) {
        this.units = units;
    }
    public BigDecimal getVolume() {
        return this.volume;
    }
    
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }
    public BigDecimal getBrokerage() {
        return this.brokerage;
    }
    
    public void setBrokerage(BigDecimal brokerage) {
        this.brokerage = brokerage;
    }
    public BigDecimal getOthercharges() {
        return this.othercharges;
    }
    
    public void setOthercharges(BigDecimal othercharges) {
        this.othercharges = othercharges;
    }
    public String getChannel() {
        return this.channel;
    }
    
    public void setChannel(String channel) {
        this.channel = channel;
    }
    public String getEuser() {
        return this.euser;
    }
    
    public void setEuser(String euser) {
        this.euser = euser;
    }
    public Date getLastupdatedon() {
        return this.lastupdatedon;
    }
    
    public void setLastupdatedon(Date lastupdatedon) {
        this.lastupdatedon = lastupdatedon;
    }




}


