package com.gtl.mmf.entity;
// Generated 17 Dec, 2015 2:48:48 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * MmfRetPortfolioSplitup generated by hbm2java
 */
public class MmfRetPortfolioSplitup  implements java.io.Serializable {


     private int id;
     private Integer clientid;
     private String isin;
     private BigDecimal dpHolding;
     private BigDecimal nsePool;
     private BigDecimal bsePool;
     private BigDecimal nseUnAc;
     private BigDecimal bseUnAc;
     private BigDecimal nsePend;
     private BigDecimal bsePend;
     private BigDecimal nseFinalQty;
     private BigDecimal bseFinalQty;
     private BigDecimal avgRate;
     private String nseSymbol;
     private String nseSeries;
     private String bseSymbol;
     private String bseSeries;
     private String bsecode;
     private String tradeCode;
     private String itClient;
     private String location;
     private int financeStock;
     private BigDecimal financeAvgCost;
     private BigDecimal pledgeQty;
     private BigDecimal mtfDpQty;
     private BigDecimal weightedAverageRate;
     private BigDecimal financeAvgRate;
     private BigDecimal multiplier;
     private BigDecimal mcxPool;
     private BigDecimal mcxUnAc;
     private BigDecimal mcxPend;
     private BigDecimal mcxFinalQty;
     private String mcxSymbol;
     private String mcxSeries;
     private String issueDate;
     private Date expiryDate;
     private int nseToken;
     private BigDecimal processedQty;

    public MmfRetPortfolioSplitup() {
    }

	
    public MmfRetPortfolioSplitup(int id, BigDecimal dpHolding, BigDecimal nsePool, BigDecimal bsePool, BigDecimal nseUnAc, BigDecimal bseUnAc, BigDecimal nsePend, BigDecimal bsePend, BigDecimal nseFinalQty, BigDecimal bseFinalQty, BigDecimal avgRate, int financeStock, BigDecimal financeAvgCost, BigDecimal pledgeQty, BigDecimal mtfDpQty, BigDecimal weightedAverageRate, BigDecimal financeAvgRate, BigDecimal multiplier, BigDecimal mcxPool, BigDecimal mcxUnAc, BigDecimal mcxPend, BigDecimal mcxFinalQty, int nseToken, BigDecimal processedQty) {
        this.id = id;
        this.dpHolding = dpHolding;
        this.nsePool = nsePool;
        this.bsePool = bsePool;
        this.nseUnAc = nseUnAc;
        this.bseUnAc = bseUnAc;
        this.nsePend = nsePend;
        this.bsePend = bsePend;
        this.nseFinalQty = nseFinalQty;
        this.bseFinalQty = bseFinalQty;
        this.avgRate = avgRate;
        this.financeStock = financeStock;
        this.financeAvgCost = financeAvgCost;
        this.pledgeQty = pledgeQty;
        this.mtfDpQty = mtfDpQty;
        this.weightedAverageRate = weightedAverageRate;
        this.financeAvgRate = financeAvgRate;
        this.multiplier = multiplier;
        this.mcxPool = mcxPool;
        this.mcxUnAc = mcxUnAc;
        this.mcxPend = mcxPend;
        this.mcxFinalQty = mcxFinalQty;
        this.nseToken = nseToken;
        this.processedQty = processedQty;
    }
    public MmfRetPortfolioSplitup(int id, Integer clientid, String isin, BigDecimal dpHolding, BigDecimal nsePool, BigDecimal bsePool, BigDecimal nseUnAc, BigDecimal bseUnAc, BigDecimal nsePend, BigDecimal bsePend, BigDecimal nseFinalQty, BigDecimal bseFinalQty, BigDecimal avgRate, String nseSymbol, String nseSeries, String bseSymbol, String bseSeries, String bsecode, String tradeCode, String itClient, String location, int financeStock, BigDecimal financeAvgCost, BigDecimal pledgeQty, BigDecimal mtfDpQty, BigDecimal weightedAverageRate, BigDecimal financeAvgRate, BigDecimal multiplier, BigDecimal mcxPool, BigDecimal mcxUnAc, BigDecimal mcxPend, BigDecimal mcxFinalQty, String mcxSymbol, String mcxSeries, String issueDate, Date expiryDate, int nseToken, BigDecimal processedQty) {
       this.id = id;
       this.clientid = clientid;
       this.isin = isin;
       this.dpHolding = dpHolding;
       this.nsePool = nsePool;
       this.bsePool = bsePool;
       this.nseUnAc = nseUnAc;
       this.bseUnAc = bseUnAc;
       this.nsePend = nsePend;
       this.bsePend = bsePend;
       this.nseFinalQty = nseFinalQty;
       this.bseFinalQty = bseFinalQty;
       this.avgRate = avgRate;
       this.nseSymbol = nseSymbol;
       this.nseSeries = nseSeries;
       this.bseSymbol = bseSymbol;
       this.bseSeries = bseSeries;
       this.bsecode = bsecode;
       this.tradeCode = tradeCode;
       this.itClient = itClient;
       this.location = location;
       this.financeStock = financeStock;
       this.financeAvgCost = financeAvgCost;
       this.pledgeQty = pledgeQty;
       this.mtfDpQty = mtfDpQty;
       this.weightedAverageRate = weightedAverageRate;
       this.financeAvgRate = financeAvgRate;
       this.multiplier = multiplier;
       this.mcxPool = mcxPool;
       this.mcxUnAc = mcxUnAc;
       this.mcxPend = mcxPend;
       this.mcxFinalQty = mcxFinalQty;
       this.mcxSymbol = mcxSymbol;
       this.mcxSeries = mcxSeries;
       this.issueDate = issueDate;
       this.expiryDate = expiryDate;
       this.nseToken = nseToken;
       this.processedQty = processedQty;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getClientid() {
        return this.clientid;
    }
    
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }
    public String getIsin() {
        return this.isin;
    }
    
    public void setIsin(String isin) {
        this.isin = isin;
    }
    public BigDecimal getDpHolding() {
        return this.dpHolding;
    }
    
    public void setDpHolding(BigDecimal dpHolding) {
        this.dpHolding = dpHolding;
    }
    public BigDecimal getNsePool() {
        return this.nsePool;
    }
    
    public void setNsePool(BigDecimal nsePool) {
        this.nsePool = nsePool;
    }
    public BigDecimal getBsePool() {
        return this.bsePool;
    }
    
    public void setBsePool(BigDecimal bsePool) {
        this.bsePool = bsePool;
    }
    public BigDecimal getNseUnAc() {
        return this.nseUnAc;
    }
    
    public void setNseUnAc(BigDecimal nseUnAc) {
        this.nseUnAc = nseUnAc;
    }
    public BigDecimal getBseUnAc() {
        return this.bseUnAc;
    }
    
    public void setBseUnAc(BigDecimal bseUnAc) {
        this.bseUnAc = bseUnAc;
    }
    public BigDecimal getNsePend() {
        return this.nsePend;
    }
    
    public void setNsePend(BigDecimal nsePend) {
        this.nsePend = nsePend;
    }
    public BigDecimal getBsePend() {
        return this.bsePend;
    }
    
    public void setBsePend(BigDecimal bsePend) {
        this.bsePend = bsePend;
    }
    public BigDecimal getNseFinalQty() {
        return this.nseFinalQty;
    }
    
    public void setNseFinalQty(BigDecimal nseFinalQty) {
        this.nseFinalQty = nseFinalQty;
    }
    public BigDecimal getBseFinalQty() {
        return this.bseFinalQty;
    }
    
    public void setBseFinalQty(BigDecimal bseFinalQty) {
        this.bseFinalQty = bseFinalQty;
    }
    public BigDecimal getAvgRate() {
        return this.avgRate;
    }
    
    public void setAvgRate(BigDecimal avgRate) {
        this.avgRate = avgRate;
    }
    public String getNseSymbol() {
        return this.nseSymbol;
    }
    
    public void setNseSymbol(String nseSymbol) {
        this.nseSymbol = nseSymbol;
    }
    public String getNseSeries() {
        return this.nseSeries;
    }
    
    public void setNseSeries(String nseSeries) {
        this.nseSeries = nseSeries;
    }
    public String getBseSymbol() {
        return this.bseSymbol;
    }
    
    public void setBseSymbol(String bseSymbol) {
        this.bseSymbol = bseSymbol;
    }
    public String getBseSeries() {
        return this.bseSeries;
    }
    
    public void setBseSeries(String bseSeries) {
        this.bseSeries = bseSeries;
    }
    public String getBsecode() {
        return this.bsecode;
    }
    
    public void setBsecode(String bsecode) {
        this.bsecode = bsecode;
    }
    public String getTradeCode() {
        return this.tradeCode;
    }
    
    public void setTradeCode(String tradeCode) {
        this.tradeCode = tradeCode;
    }
    public String getItClient() {
        return this.itClient;
    }
    
    public void setItClient(String itClient) {
        this.itClient = itClient;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public int getFinanceStock() {
        return this.financeStock;
    }
    
    public void setFinanceStock(int financeStock) {
        this.financeStock = financeStock;
    }
    public BigDecimal getFinanceAvgCost() {
        return this.financeAvgCost;
    }
    
    public void setFinanceAvgCost(BigDecimal financeAvgCost) {
        this.financeAvgCost = financeAvgCost;
    }
    public BigDecimal getPledgeQty() {
        return this.pledgeQty;
    }
    
    public void setPledgeQty(BigDecimal pledgeQty) {
        this.pledgeQty = pledgeQty;
    }
    public BigDecimal getMtfDpQty() {
        return this.mtfDpQty;
    }
    
    public void setMtfDpQty(BigDecimal mtfDpQty) {
        this.mtfDpQty = mtfDpQty;
    }
    public BigDecimal getWeightedAverageRate() {
        return this.weightedAverageRate;
    }
    
    public void setWeightedAverageRate(BigDecimal weightedAverageRate) {
        this.weightedAverageRate = weightedAverageRate;
    }
    public BigDecimal getFinanceAvgRate() {
        return this.financeAvgRate;
    }
    
    public void setFinanceAvgRate(BigDecimal financeAvgRate) {
        this.financeAvgRate = financeAvgRate;
    }
    public BigDecimal getMultiplier() {
        return this.multiplier;
    }
    
    public void setMultiplier(BigDecimal multiplier) {
        this.multiplier = multiplier;
    }
    public BigDecimal getMcxPool() {
        return this.mcxPool;
    }
    
    public void setMcxPool(BigDecimal mcxPool) {
        this.mcxPool = mcxPool;
    }
    public BigDecimal getMcxUnAc() {
        return this.mcxUnAc;
    }
    
    public void setMcxUnAc(BigDecimal mcxUnAc) {
        this.mcxUnAc = mcxUnAc;
    }
    public BigDecimal getMcxPend() {
        return this.mcxPend;
    }
    
    public void setMcxPend(BigDecimal mcxPend) {
        this.mcxPend = mcxPend;
    }
    public BigDecimal getMcxFinalQty() {
        return this.mcxFinalQty;
    }
    
    public void setMcxFinalQty(BigDecimal mcxFinalQty) {
        this.mcxFinalQty = mcxFinalQty;
    }
    public String getMcxSymbol() {
        return this.mcxSymbol;
    }
    
    public void setMcxSymbol(String mcxSymbol) {
        this.mcxSymbol = mcxSymbol;
    }
    public String getMcxSeries() {
        return this.mcxSeries;
    }
    
    public void setMcxSeries(String mcxSeries) {
        this.mcxSeries = mcxSeries;
    }
    public String getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }
    public int getNseToken() {
        return this.nseToken;
    }
    
    public void setNseToken(int nseToken) {
        this.nseToken = nseToken;
    }

    public BigDecimal getProcessedQty() {
        return this.processedQty;
    }
    
    public void setProcessedQty(BigDecimal processedQty) {
        this.processedQty = processedQty;
    }


}


