package com.gtl.mmf.entity;
// Generated 24 Feb, 2016 3:01:07 PM by Hibernate Tools 3.6.0



/**
 * MmfSettingsTb generated by hbm2java
 */
public class MmfSettingsTb  implements java.io.Serializable {


     private Integer id;
     private String fieldname;
     private String fieldvalue;

    public MmfSettingsTb() {
    }

    public MmfSettingsTb(String fieldname, String fieldvalue) {
       this.fieldname = fieldname;
       this.fieldvalue = fieldvalue;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFieldname() {
        return this.fieldname;
    }
    
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname;
    }
    public String getFieldvalue() {
        return this.fieldvalue;
    }
    
    public void setFieldvalue(String fieldvalue) {
        this.fieldvalue = fieldvalue;
    }




}


