package com.gtl.mmf.entity;
// Generated Dec 22, 2014 4:17:26 PM by Hibernate Tools 3.2.1.GA



/**
 * OccupationTb generated by hbm2java
 */
public class OccupationTb  implements java.io.Serializable {


     private int id;
     private Integer key;
     private String occupation;

    public OccupationTb() {
    }

	
    public OccupationTb(int id) {
        this.id = id;
    }
    public OccupationTb(int id, Integer key, String occupation) {
       this.id = id;
       this.key = key;
       this.occupation = occupation;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getKey() {
        return this.key;
    }
    
    public void setKey(Integer key) {
        this.key = key;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }




}


