package com.gtl.mmf.entity;
// Generated Jul 13, 2015 10:58:18 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Performancefeecalculation generated by hbm2java
 */
public class Performancefeecalculation  implements java.io.Serializable {


     private Integer id;
     private CustomerAdvisorMappingTb customerAdvisorMappingTb;
     private int customerId;
     private Integer advisorId;
     private Date feeCalculateDate;
     private BigDecimal cashFlow;
     private BigDecimal expectedReturn;
     private BigDecimal effectiveHwm;
     private BigDecimal marketValue;
     private BigDecimal billableAmount;
     private Boolean isBillDate;
     private BigDecimal billAmount;
     private BigDecimal sumPrevBillAmount;

    public Performancefeecalculation() {
    }

	
    public Performancefeecalculation(CustomerAdvisorMappingTb customerAdvisorMappingTb, int customerId) {
        this.customerAdvisorMappingTb = customerAdvisorMappingTb;
        this.customerId = customerId;
    }
    public Performancefeecalculation(CustomerAdvisorMappingTb customerAdvisorMappingTb, int customerId, Integer advisorId, Date feeCalculateDate, BigDecimal cashFlow, BigDecimal expectedReturn, BigDecimal effectiveHwm, BigDecimal marketValue, BigDecimal billableAmount, Boolean isBillDate, BigDecimal billAmount, BigDecimal sumPrevBillAmount) {
       this.customerAdvisorMappingTb = customerAdvisorMappingTb;
       this.customerId = customerId;
       this.advisorId = advisorId;
       this.feeCalculateDate = feeCalculateDate;
       this.cashFlow = cashFlow;
       this.expectedReturn = expectedReturn;
       this.effectiveHwm = effectiveHwm;
       this.marketValue = marketValue;
       this.billableAmount = billableAmount;
       this.isBillDate = isBillDate;
       this.billAmount = billAmount;
       this.sumPrevBillAmount = sumPrevBillAmount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CustomerAdvisorMappingTb getCustomerAdvisorMappingTb() {
        return this.customerAdvisorMappingTb;
    }
    
    public void setCustomerAdvisorMappingTb(CustomerAdvisorMappingTb customerAdvisorMappingTb) {
        this.customerAdvisorMappingTb = customerAdvisorMappingTb;
    }
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    public Integer getAdvisorId() {
        return this.advisorId;
    }
    
    public void setAdvisorId(Integer advisorId) {
        this.advisorId = advisorId;
    }
    public Date getFeeCalculateDate() {
        return this.feeCalculateDate;
    }
    
    public void setFeeCalculateDate(Date feeCalculateDate) {
        this.feeCalculateDate = feeCalculateDate;
    }
    public BigDecimal getCashFlow() {
        return this.cashFlow;
    }
    
    public void setCashFlow(BigDecimal cashFlow) {
        this.cashFlow = cashFlow;
    }
    public BigDecimal getExpectedReturn() {
        return this.expectedReturn;
    }
    
    public void setExpectedReturn(BigDecimal expectedReturn) {
        this.expectedReturn = expectedReturn;
    }
    public BigDecimal getEffectiveHwm() {
        return this.effectiveHwm;
    }
    
    public void setEffectiveHwm(BigDecimal effectiveHwm) {
        this.effectiveHwm = effectiveHwm;
    }
    public BigDecimal getMarketValue() {
        return this.marketValue;
    }
    
    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }
    public BigDecimal getBillableAmount() {
        return this.billableAmount;
    }
    
    public void setBillableAmount(BigDecimal billableAmount) {
        this.billableAmount = billableAmount;
    }
    public Boolean getIsBillDate() {
        return this.isBillDate;
    }
    
    public void setIsBillDate(Boolean isBillDate) {
        this.isBillDate = isBillDate;
    }
    public BigDecimal getBillAmount() {
        return this.billAmount;
    }
    
    public void setBillAmount(BigDecimal billAmount) {
        this.billAmount = billAmount;
    }
    public BigDecimal getSumPrevBillAmount() {
        return this.sumPrevBillAmount;
    }
    
    public void setSumPrevBillAmount(BigDecimal sumPrevBillAmount) {
        this.sumPrevBillAmount = sumPrevBillAmount;
    }




}


