package com.gtl.mmf.entity;
// Generated Jun 11, 2014 3:19:30 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * PortfolioPerformanceTb generated by hbm2java
 */
public class PortfolioPerformanceTb implements java.io.Serializable {

    private Integer portfolioPerformanceId;
    private PortfolioTb portfolioTb;
    private Date datetime;
    private BigDecimal closingValue;
    private BigDecimal marketValue;
    private BigDecimal marketValueAfterCashFlow;
    private BigDecimal subPeriodReturn;

    public PortfolioPerformanceTb() {
    }

    public PortfolioPerformanceTb(PortfolioTb portfolioTb) {
        this.portfolioTb = portfolioTb;
    }

    public PortfolioPerformanceTb(PortfolioTb portfolioTb, Date datetime, BigDecimal closingValue, BigDecimal marketValue, BigDecimal marketValueAfterCashFlow, BigDecimal subPeriodReturn) {
        this.portfolioTb = portfolioTb;
        this.datetime = datetime;
        this.closingValue = closingValue;
        this.marketValue = marketValue;
        this.marketValueAfterCashFlow = marketValueAfterCashFlow;
        this.subPeriodReturn = subPeriodReturn;
    }

    public Integer getPortfolioPerformanceId() {
        return this.portfolioPerformanceId;
    }

    public void setPortfolioPerformanceId(Integer portfolioPerformanceId) {
        this.portfolioPerformanceId = portfolioPerformanceId;
    }

    public PortfolioTb getPortfolioTb() {
        return this.portfolioTb;
    }

    public void setPortfolioTb(PortfolioTb portfolioTb) {
        this.portfolioTb = portfolioTb;
    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public BigDecimal getClosingValue() {
        return this.closingValue;
    }

    public void setClosingValue(BigDecimal closingValue) {
        this.closingValue = closingValue;
    }

    public BigDecimal getMarketValue() {
        return this.marketValue;
    }

    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }

    public BigDecimal getMarketValueAfterCashFlow() {
        return this.marketValueAfterCashFlow;
    }

    public void setMarketValueAfterCashFlow(BigDecimal marketValueAfterCashFlow) {
        this.marketValueAfterCashFlow = marketValueAfterCashFlow;
    }

    public BigDecimal getSubPeriodReturn() {
        return this.subPeriodReturn;
    }

    public void setSubPeriodReturn(BigDecimal subPeriodReturn) {
        this.subPeriodReturn = subPeriodReturn;
    }

}
