package com.gtl.mmf.entity;
// Generated Jun 11, 2014 3:19:30 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * PortfolioDetailsPerformanceTb generated by hbm2java
 */
public class PortfolioDetailsPerformanceTb implements java.io.Serializable {

    private Integer portfolioDetailsPerformanceId;
    private PortfolioDetailsTb portfolioDetailsTb;
    private MasterAssetTb masterAssetTb;
    private PortfolioTb portfolioTb;
    private Date datetime;
    private BigDecimal closingValue;
    private BigDecimal marketValue;
    private BigDecimal marketValueAfterCashFlow;
    private BigDecimal subPeriodReturn;

    public PortfolioDetailsPerformanceTb() {
    }

    public PortfolioDetailsPerformanceTb(PortfolioDetailsTb portfolioDetailsTb, MasterAssetTb masterAssetTb, PortfolioTb portfolioTb) {
        this.portfolioDetailsTb = portfolioDetailsTb;
        this.masterAssetTb = masterAssetTb;
        this.portfolioTb = portfolioTb;
    }

    public PortfolioDetailsPerformanceTb(PortfolioDetailsTb portfolioDetailsTb, MasterAssetTb masterAssetTb, PortfolioTb portfolioTb, Date datetime, BigDecimal closingValue, BigDecimal marketValue, BigDecimal marketValueAfterCashFlow, BigDecimal subPeriodReturn) {
        this.portfolioDetailsTb = portfolioDetailsTb;
        this.masterAssetTb = masterAssetTb;
        this.portfolioTb = portfolioTb;
        this.datetime = datetime;
        this.closingValue = closingValue;
        this.marketValue = marketValue;
        this.marketValueAfterCashFlow = marketValueAfterCashFlow;
        this.subPeriodReturn = subPeriodReturn;
    }

    public Integer getPortfolioDetailsPerformanceId() {
        return this.portfolioDetailsPerformanceId;
    }

    public void setPortfolioDetailsPerformanceId(Integer portfolioDetailsPerformanceId) {
        this.portfolioDetailsPerformanceId = portfolioDetailsPerformanceId;
    }

    public PortfolioDetailsTb getPortfolioDetailsTb() {
        return this.portfolioDetailsTb;
    }

    public void setPortfolioDetailsTb(PortfolioDetailsTb portfolioDetailsTb) {
        this.portfolioDetailsTb = portfolioDetailsTb;
    }

    public MasterAssetTb getMasterAssetTb() {
        return this.masterAssetTb;
    }

    public void setMasterAssetTb(MasterAssetTb masterAssetTb) {
        this.masterAssetTb = masterAssetTb;
    }

    public PortfolioTb getPortfolioTb() {
        return this.portfolioTb;
    }

    public void setPortfolioTb(PortfolioTb portfolioTb) {
        this.portfolioTb = portfolioTb;
    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public BigDecimal getClosingValue() {
        return this.closingValue;
    }

    public void setClosingValue(BigDecimal closingValue) {
        this.closingValue = closingValue;
    }

    public BigDecimal getMarketValue() {
        return this.marketValue;
    }

    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }

    public BigDecimal getMarketValueAfterCashFlow() {
        return this.marketValueAfterCashFlow;
    }

    public void setMarketValueAfterCashFlow(BigDecimal marketValueAfterCashFlow) {
        this.marketValueAfterCashFlow = marketValueAfterCashFlow;
    }

    public BigDecimal getSubPeriodReturn() {
        return this.subPeriodReturn;
    }

    public void setSubPeriodReturn(BigDecimal subPeriodReturn) {
        this.subPeriodReturn = subPeriodReturn;
    }

}
