package com.gtl.mmf.entity;
// Generated May 14, 2014 4:37:58 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PortfolioAuditTb generated by hbm2java
 */
public class PortfolioAuditTb implements java.io.Serializable {

    private Integer portfolioAuditId;
    private Integer portfolioId;
    private int advisorId;
    private String portfolioName;
    private Integer benchmark;
    private Integer portfolioStyle;
    private BigDecimal stdDev;
    private Integer sharpeRatio;
    private BigDecimal expReturns;
    private BigDecimal alpha;
    private BigDecimal beta;
    private BigDecimal infoRatio;
    private Byte RSquared;
    private BigDecimal vaR;
    private BigDecimal portfolio90DayReturns;
    private BigDecimal portfolio1YearReturns;
    private BigDecimal benchmark90DaysReturns;
    private BigDecimal benchmark1YearReturns;
    private Integer noOfCustomersAssigned;
    private Boolean rebalanceRequired;
    private Date rebalanceReqdDate;
    private Date lastUpdated;
    private Date dateCreated;
    private Date startCurrentPeriod;
    private Boolean status;
    private BigDecimal portfolioValue;
    private Date lastUpdateon;
    private String actvityType;
    private Set portfolioDetailsAuditTbs = new HashSet(0);

    public PortfolioAuditTb() {
    }

    public PortfolioAuditTb(int advisorId) {
        this.advisorId = advisorId;
    }

    public PortfolioAuditTb(Integer portfolioId, int advisorId, String portfolioName, Integer benchmark, Integer portfolioStyle, BigDecimal stdDev, Integer sharpeRatio, BigDecimal expReturns, BigDecimal alpha, BigDecimal beta, BigDecimal infoRatio, Byte RSquared, BigDecimal vaR, BigDecimal portfolio90DayReturns, BigDecimal portfolio1YearReturns, BigDecimal benchmark90DaysReturns, BigDecimal benchmark1YearReturns, Integer noOfCustomersAssigned, Boolean rebalanceRequired, Date rebalanceReqdDate, Date lastUpdated, Date dateCreated, Date startCurrentPeriod, Boolean status, BigDecimal portfolioValue, Date lastUpdateon, String actvityType, Set portfolioDetailsAuditTbs) {
        this.portfolioId = portfolioId;
        this.advisorId = advisorId;
        this.portfolioName = portfolioName;
        this.benchmark = benchmark;
        this.portfolioStyle = portfolioStyle;
        this.stdDev = stdDev;
        this.sharpeRatio = sharpeRatio;
        this.expReturns = expReturns;
        this.alpha = alpha;
        this.beta = beta;
        this.infoRatio = infoRatio;
        this.RSquared = RSquared;
        this.vaR = vaR;
        this.portfolio90DayReturns = portfolio90DayReturns;
        this.portfolio1YearReturns = portfolio1YearReturns;
        this.benchmark90DaysReturns = benchmark90DaysReturns;
        this.benchmark1YearReturns = benchmark1YearReturns;
        this.noOfCustomersAssigned = noOfCustomersAssigned;
        this.rebalanceRequired = rebalanceRequired;
        this.rebalanceReqdDate = rebalanceReqdDate;
        this.lastUpdated = lastUpdated;
        this.dateCreated = dateCreated;
        this.startCurrentPeriod = startCurrentPeriod;
        this.status = status;
        this.portfolioValue = portfolioValue;
        this.lastUpdateon = lastUpdateon;
        this.actvityType = actvityType;
        this.portfolioDetailsAuditTbs = portfolioDetailsAuditTbs;
    }

    public Integer getPortfolioAuditId() {
        return this.portfolioAuditId;
    }

    public void setPortfolioAuditId(Integer portfolioAuditId) {
        this.portfolioAuditId = portfolioAuditId;
    }

    public Integer getPortfolioId() {
        return this.portfolioId;
    }

    public void setPortfolioId(Integer portfolioId) {
        this.portfolioId = portfolioId;
    }

    public int getAdvisorId() {
        return this.advisorId;
    }

    public void setAdvisorId(int advisorId) {
        this.advisorId = advisorId;
    }

    public String getPortfolioName() {
        return this.portfolioName;
    }

    public void setPortfolioName(String portfolioName) {
        this.portfolioName = portfolioName;
    }

    public Integer getBenchmark() {
        return this.benchmark;
    }

    public void setBenchmark(Integer benchmark) {
        this.benchmark = benchmark;
    }

    public Integer getPortfolioStyle() {
        return this.portfolioStyle;
    }

    public void setPortfolioStyle(Integer portfolioStyle) {
        this.portfolioStyle = portfolioStyle;
    }

    public BigDecimal getStdDev() {
        return this.stdDev;
    }

    public void setStdDev(BigDecimal stdDev) {
        this.stdDev = stdDev;
    }

    public Integer getSharpeRatio() {
        return this.sharpeRatio;
    }

    public void setSharpeRatio(Integer sharpeRatio) {
        this.sharpeRatio = sharpeRatio;
    }

    public BigDecimal getExpReturns() {
        return this.expReturns;
    }

    public void setExpReturns(BigDecimal expReturns) {
        this.expReturns = expReturns;
    }

    public BigDecimal getAlpha() {
        return this.alpha;
    }

    public void setAlpha(BigDecimal alpha) {
        this.alpha = alpha;
    }

    public BigDecimal getBeta() {
        return this.beta;
    }

    public void setBeta(BigDecimal beta) {
        this.beta = beta;
    }

    public BigDecimal getInfoRatio() {
        return this.infoRatio;
    }

    public void setInfoRatio(BigDecimal infoRatio) {
        this.infoRatio = infoRatio;
    }

    public Byte getRSquared() {
        return this.RSquared;
    }

    public void setRSquared(Byte RSquared) {
        this.RSquared = RSquared;
    }

    public BigDecimal getVaR() {
        return this.vaR;
    }

    public void setVaR(BigDecimal vaR) {
        this.vaR = vaR;
    }

    public BigDecimal getPortfolio90DayReturns() {
        return this.portfolio90DayReturns;
    }

    public void setPortfolio90DayReturns(BigDecimal portfolio90DayReturns) {
        this.portfolio90DayReturns = portfolio90DayReturns;
    }

    public BigDecimal getPortfolio1YearReturns() {
        return this.portfolio1YearReturns;
    }

    public void setPortfolio1YearReturns(BigDecimal portfolio1YearReturns) {
        this.portfolio1YearReturns = portfolio1YearReturns;
    }

    public BigDecimal getBenchmark90DaysReturns() {
        return this.benchmark90DaysReturns;
    }

    public void setBenchmark90DaysReturns(BigDecimal benchmark90DaysReturns) {
        this.benchmark90DaysReturns = benchmark90DaysReturns;
    }

    public BigDecimal getBenchmark1YearReturns() {
        return this.benchmark1YearReturns;
    }

    public void setBenchmark1YearReturns(BigDecimal benchmark1YearReturns) {
        this.benchmark1YearReturns = benchmark1YearReturns;
    }

    public Integer getNoOfCustomersAssigned() {
        return this.noOfCustomersAssigned;
    }

    public void setNoOfCustomersAssigned(Integer noOfCustomersAssigned) {
        this.noOfCustomersAssigned = noOfCustomersAssigned;
    }

    public Boolean getRebalanceRequired() {
        return this.rebalanceRequired;
    }

    public void setRebalanceRequired(Boolean rebalanceRequired) {
        this.rebalanceRequired = rebalanceRequired;
    }

    public Date getRebalanceReqdDate() {
        return this.rebalanceReqdDate;
    }

    public void setRebalanceReqdDate(Date rebalanceReqdDate) {
        this.rebalanceReqdDate = rebalanceReqdDate;
    }

    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getStartCurrentPeriod() {
        return this.startCurrentPeriod;
    }

    public void setStartCurrentPeriod(Date startCurrentPeriod) {
        this.startCurrentPeriod = startCurrentPeriod;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public BigDecimal getPortfolioValue() {
        return this.portfolioValue;
    }

    public void setPortfolioValue(BigDecimal portfolioValue) {
        this.portfolioValue = portfolioValue;
    }

    public Date getLastUpdateon() {
        return this.lastUpdateon;
    }

    public void setLastUpdateon(Date lastUpdateon) {
        this.lastUpdateon = lastUpdateon;
    }

    public String getActvityType() {
        return this.actvityType;
    }

    public void setActvityType(String actvityType) {
        this.actvityType = actvityType;
    }

    public Set getPortfolioDetailsAuditTbs() {
        return this.portfolioDetailsAuditTbs;
    }

    public void setPortfolioDetailsAuditTbs(Set portfolioDetailsAuditTbs) {
        this.portfolioDetailsAuditTbs = portfolioDetailsAuditTbs;
    }

}
