package com.gtl.mmf.entity;
// Generated 5 Dec, 2015 1:20:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * PortfolioSecuritiesPerformanceTb generated by hbm2java
 */
public class PortfolioSecuritiesPerformanceTb  implements java.io.Serializable {


     private Integer portfolioSecuritiesPerformanceId;
     private PortfolioDetailsTb portfolioDetailsTb;
     private PortfolioSecuritiesTb portfolioSecuritiesTb;
     private MasterAssetTb masterAssetTb;
     private PortfolioTb portfolioTb;
     private String securityId;
     private String securityCode;
     private Date datetime;
     private BigDecimal closingValue;
     private BigDecimal existingUnits;
     private BigDecimal closingPrice;
     private BigDecimal marketValue;
     private BigDecimal marketValueAfterCashFlow;
     private BigDecimal subPeriodReturn;

    public PortfolioSecuritiesPerformanceTb() {
    }

	
    public PortfolioSecuritiesPerformanceTb(PortfolioDetailsTb portfolioDetailsTb, PortfolioSecuritiesTb portfolioSecuritiesTb, MasterAssetTb masterAssetTb, PortfolioTb portfolioTb, String securityId, String securityCode) {
        this.portfolioDetailsTb = portfolioDetailsTb;
        this.portfolioSecuritiesTb = portfolioSecuritiesTb;
        this.masterAssetTb = masterAssetTb;
        this.portfolioTb = portfolioTb;
        this.securityId = securityId;
        this.securityCode = securityCode;
    }
    public PortfolioSecuritiesPerformanceTb(PortfolioDetailsTb portfolioDetailsTb, PortfolioSecuritiesTb portfolioSecuritiesTb, MasterAssetTb masterAssetTb, PortfolioTb portfolioTb, String securityId, String securityCode, Date datetime, BigDecimal closingValue, BigDecimal existingUnits, BigDecimal closingPrice, BigDecimal marketValue, BigDecimal marketValueAfterCashFlow, BigDecimal subPeriodReturn) {
       this.portfolioDetailsTb = portfolioDetailsTb;
       this.portfolioSecuritiesTb = portfolioSecuritiesTb;
       this.masterAssetTb = masterAssetTb;
       this.portfolioTb = portfolioTb;
       this.securityId = securityId;
       this.securityCode = securityCode;
       this.datetime = datetime;
       this.closingValue = closingValue;
       this.existingUnits = existingUnits;
       this.closingPrice = closingPrice;
       this.marketValue = marketValue;
       this.marketValueAfterCashFlow = marketValueAfterCashFlow;
       this.subPeriodReturn = subPeriodReturn;
    }
   
    public Integer getPortfolioSecuritiesPerformanceId() {
        return this.portfolioSecuritiesPerformanceId;
    }
    
    public void setPortfolioSecuritiesPerformanceId(Integer portfolioSecuritiesPerformanceId) {
        this.portfolioSecuritiesPerformanceId = portfolioSecuritiesPerformanceId;
    }
    public PortfolioDetailsTb getPortfolioDetailsTb() {
        return this.portfolioDetailsTb;
    }
    
    public void setPortfolioDetailsTb(PortfolioDetailsTb portfolioDetailsTb) {
        this.portfolioDetailsTb = portfolioDetailsTb;
    }
    public PortfolioSecuritiesTb getPortfolioSecuritiesTb() {
        return this.portfolioSecuritiesTb;
    }
    
    public void setPortfolioSecuritiesTb(PortfolioSecuritiesTb portfolioSecuritiesTb) {
        this.portfolioSecuritiesTb = portfolioSecuritiesTb;
    }
    public MasterAssetTb getMasterAssetTb() {
        return this.masterAssetTb;
    }
    
    public void setMasterAssetTb(MasterAssetTb masterAssetTb) {
        this.masterAssetTb = masterAssetTb;
    }
    public PortfolioTb getPortfolioTb() {
        return this.portfolioTb;
    }
    
    public void setPortfolioTb(PortfolioTb portfolioTb) {
        this.portfolioTb = portfolioTb;
    }
    public String getSecurityId() {
        return this.securityId;
    }
    
    public void setSecurityId(String securityId) {
        this.securityId = securityId;
    }
    public String getSecurityCode() {
        return this.securityCode;
    }
    
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public BigDecimal getClosingValue() {
        return this.closingValue;
    }
    
    public void setClosingValue(BigDecimal closingValue) {
        this.closingValue = closingValue;
    }
    public BigDecimal getExistingUnits() {
        return this.existingUnits;
    }
    
    public void setExistingUnits(BigDecimal existingUnits) {
        this.existingUnits = existingUnits;
    }
    public BigDecimal getClosingPrice() {
        return this.closingPrice;
    }
    
    public void setClosingPrice(BigDecimal closingPrice) {
        this.closingPrice = closingPrice;
    }
    public BigDecimal getMarketValue() {
        return this.marketValue;
    }
    
    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }
    public BigDecimal getMarketValueAfterCashFlow() {
        return this.marketValueAfterCashFlow;
    }
    
    public void setMarketValueAfterCashFlow(BigDecimal marketValueAfterCashFlow) {
        this.marketValueAfterCashFlow = marketValueAfterCashFlow;
    }
    public BigDecimal getSubPeriodReturn() {
        return this.subPeriodReturn;
    }
    
    public void setSubPeriodReturn(BigDecimal subPeriodReturn) {
        this.subPeriodReturn = subPeriodReturn;
    }




}


