package com.gtl.mmf.entity;
// Generated May 14, 2014 4:37:58 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PortfolioDetailsAuditTb generated by hbm2java
 */
public class PortfolioDetailsAuditTb implements java.io.Serializable {

    private Integer portfolioDetailsAuditId;
    private PortfolioAuditTb portfolioAuditTb;
    private Integer portfolioDetailsId;
    private Integer portfolioId;
    private Short assetClassId;
    private BigDecimal rangeFrom;
    private BigDecimal rangeTo;
    private BigDecimal newWeight;
    private BigDecimal currentWeight;
    private BigDecimal initialWeight;
    private Boolean rebalanceRequired;
    private Date rebalanceReqdDate;
    private BigDecimal currentValue;
    private BigDecimal newAllocation;
    private Date lastUpdateon;
    private String activityType;
    private Set portfolioSecuritiesAuditTbs = new HashSet(0);

    public PortfolioDetailsAuditTb() {
    }

    public PortfolioDetailsAuditTb(PortfolioAuditTb portfolioAuditTb, Integer portfolioDetailsId, Integer portfolioId, Short assetClassId, BigDecimal rangeFrom, BigDecimal rangeTo, BigDecimal newWeight, BigDecimal currentWeight, BigDecimal initialWeight, Boolean rebalanceRequired, Date rebalanceReqdDate, BigDecimal currentValue, BigDecimal newAllocation, Date lastUpdateon, String activityType, Set portfolioSecuritiesAuditTbs) {
        this.portfolioAuditTb = portfolioAuditTb;
        this.portfolioDetailsId = portfolioDetailsId;
        this.portfolioId = portfolioId;
        this.assetClassId = assetClassId;
        this.rangeFrom = rangeFrom;
        this.rangeTo = rangeTo;
        this.newWeight = newWeight;
        this.currentWeight = currentWeight;
        this.initialWeight = initialWeight;
        this.rebalanceRequired = rebalanceRequired;
        this.rebalanceReqdDate = rebalanceReqdDate;
        this.currentValue = currentValue;
        this.newAllocation = newAllocation;
        this.lastUpdateon = lastUpdateon;
        this.activityType = activityType;
        this.portfolioSecuritiesAuditTbs = portfolioSecuritiesAuditTbs;
    }

    public Integer getPortfolioDetailsAuditId() {
        return this.portfolioDetailsAuditId;
    }

    public void setPortfolioDetailsAuditId(Integer portfolioDetailsAuditId) {
        this.portfolioDetailsAuditId = portfolioDetailsAuditId;
    }

    public PortfolioAuditTb getPortfolioAuditTb() {
        return this.portfolioAuditTb;
    }

    public void setPortfolioAuditTb(PortfolioAuditTb portfolioAuditTb) {
        this.portfolioAuditTb = portfolioAuditTb;
    }

    public Integer getPortfolioDetailsId() {
        return this.portfolioDetailsId;
    }

    public void setPortfolioDetailsId(Integer portfolioDetailsId) {
        this.portfolioDetailsId = portfolioDetailsId;
    }

    public Integer getPortfolioId() {
        return this.portfolioId;
    }

    public void setPortfolioId(Integer portfolioId) {
        this.portfolioId = portfolioId;
    }

    public Short getAssetClassId() {
        return this.assetClassId;
    }

    public void setAssetClassId(Short assetClassId) {
        this.assetClassId = assetClassId;
    }

    public BigDecimal getRangeFrom() {
        return this.rangeFrom;
    }

    public void setRangeFrom(BigDecimal rangeFrom) {
        this.rangeFrom = rangeFrom;
    }

    public BigDecimal getRangeTo() {
        return this.rangeTo;
    }

    public void setRangeTo(BigDecimal rangeTo) {
        this.rangeTo = rangeTo;
    }

    public BigDecimal getNewWeight() {
        return this.newWeight;
    }

    public void setNewWeight(BigDecimal newWeight) {
        this.newWeight = newWeight;
    }

    public BigDecimal getCurrentWeight() {
        return this.currentWeight;
    }

    public void setCurrentWeight(BigDecimal currentWeight) {
        this.currentWeight = currentWeight;
    }

    public BigDecimal getInitialWeight() {
        return this.initialWeight;
    }

    public void setInitialWeight(BigDecimal initialWeight) {
        this.initialWeight = initialWeight;
    }

    public Boolean getRebalanceRequired() {
        return this.rebalanceRequired;
    }

    public void setRebalanceRequired(Boolean rebalanceRequired) {
        this.rebalanceRequired = rebalanceRequired;
    }

    public Date getRebalanceReqdDate() {
        return this.rebalanceReqdDate;
    }

    public void setRebalanceReqdDate(Date rebalanceReqdDate) {
        this.rebalanceReqdDate = rebalanceReqdDate;
    }

    public BigDecimal getCurrentValue() {
        return this.currentValue;
    }

    public void setCurrentValue(BigDecimal currentValue) {
        this.currentValue = currentValue;
    }

    public BigDecimal getNewAllocation() {
        return this.newAllocation;
    }

    public void setNewAllocation(BigDecimal newAllocation) {
        this.newAllocation = newAllocation;
    }

    public Date getLastUpdateon() {
        return this.lastUpdateon;
    }

    public void setLastUpdateon(Date lastUpdateon) {
        this.lastUpdateon = lastUpdateon;
    }

    public String getActivityType() {
        return this.activityType;
    }

    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }

    public Set getPortfolioSecuritiesAuditTbs() {
        return this.portfolioSecuritiesAuditTbs;
    }

    public void setPortfolioSecuritiesAuditTbs(Set portfolioSecuritiesAuditTbs) {
        this.portfolioSecuritiesAuditTbs = portfolioSecuritiesAuditTbs;
    }

}
