package com.gtl.mmf.entity;
// Generated Jul 13, 2015 10:58:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Promodefinitions generated by hbm2java
 */
public class Promodefinitions  implements java.io.Serializable {


     private int promoId;
     private String promoName;
     private Set customerAdvisorMappingTbs = new HashSet(0);
     private Set customerAdvisorMappingTbs_1 = new HashSet(0);
     private Set tieredpromocommissionmatrixes = new HashSet(0);
     private Set advisorbucketwisepayoutses = new HashSet(0);
     private Set masterCustomerTbs = new HashSet(0);

    public Promodefinitions() {
    }

	
    public Promodefinitions(int promoId) {
        this.promoId = promoId;
    }
    public Promodefinitions(int promoId, String promoName, Set customerAdvisorMappingTbs, Set customerAdvisorMappingTbs_1, Set tieredpromocommissionmatrixes, Set advisorbucketwisepayoutses, Set masterCustomerTbs) {
       this.promoId = promoId;
       this.promoName = promoName;
       this.customerAdvisorMappingTbs = customerAdvisorMappingTbs;
       this.customerAdvisorMappingTbs_1 = customerAdvisorMappingTbs_1;
       this.tieredpromocommissionmatrixes = tieredpromocommissionmatrixes;
       this.advisorbucketwisepayoutses = advisorbucketwisepayoutses;
       this.masterCustomerTbs = masterCustomerTbs;
    }
   
    public int getPromoId() {
        return this.promoId;
    }
    
    public void setPromoId(int promoId) {
        this.promoId = promoId;
    }
    public String getPromoName() {
        return this.promoName;
    }
    
    public void setPromoName(String promoName) {
        this.promoName = promoName;
    }
    public Set getCustomerAdvisorMappingTbs() {
        return this.customerAdvisorMappingTbs;
    }
    
    public void setCustomerAdvisorMappingTbs(Set customerAdvisorMappingTbs) {
        this.customerAdvisorMappingTbs = customerAdvisorMappingTbs;
    }
    public Set getCustomerAdvisorMappingTbs_1() {
        return this.customerAdvisorMappingTbs_1;
    }
    
    public void setCustomerAdvisorMappingTbs_1(Set customerAdvisorMappingTbs_1) {
        this.customerAdvisorMappingTbs_1 = customerAdvisorMappingTbs_1;
    }
    public Set getTieredpromocommissionmatrixes() {
        return this.tieredpromocommissionmatrixes;
    }
    
    public void setTieredpromocommissionmatrixes(Set tieredpromocommissionmatrixes) {
        this.tieredpromocommissionmatrixes = tieredpromocommissionmatrixes;
    }
    public Set getAdvisorbucketwisepayoutses() {
        return this.advisorbucketwisepayoutses;
    }
    
    public void setAdvisorbucketwisepayoutses(Set advisorbucketwisepayoutses) {
        this.advisorbucketwisepayoutses = advisorbucketwisepayoutses;
    }
    public Set getMasterCustomerTbs() {
        return this.masterCustomerTbs;
    }
    
    public void setMasterCustomerTbs(Set masterCustomerTbs) {
        this.masterCustomerTbs = masterCustomerTbs;
    }




}


