package com.gtl.mmf.entity;
// Generated Dec 22, 2014 4:17:26 PM by Hibernate Tools 3.2.1.GA



/**
 * ProofofIdentityTb generated by hbm2java
 */
public class ProofofIdentityTb  implements java.io.Serializable {


     private int id;
     private Integer key;
     private String proofIdentity;

    public ProofofIdentityTb() {
    }

	
    public ProofofIdentityTb(int id) {
        this.id = id;
    }
    public ProofofIdentityTb(int id, Integer key, String proofIdentity) {
       this.id = id;
       this.key = key;
       this.proofIdentity = proofIdentity;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getKey() {
        return this.key;
    }
    
    public void setKey(Integer key) {
        this.key = key;
    }
    public String getProofIdentity() {
        return this.proofIdentity;
    }
    
    public void setProofIdentity(String proofIdentity) {
        this.proofIdentity = proofIdentity;
    }




}


