package com.gtl.mmf.entity;
// Generated Dec 22, 2014 4:17:26 PM by Hibernate Tools 3.2.1.GA



/**
 * ProofofAddressTb generated by hbm2java
 */
public class ProofofAddressTb  implements java.io.Serializable {


     private int id;
     private Integer key;
     private String proofofAddress;

    public ProofofAddressTb() {
    }

	
    public ProofofAddressTb(int id) {
        this.id = id;
    }
    public ProofofAddressTb(int id, Integer key, String proofofAddress) {
       this.id = id;
       this.key = key;
       this.proofofAddress = proofofAddress;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getKey() {
        return this.key;
    }
    
    public void setKey(Integer key) {
        this.key = key;
    }
    public String getProofofAddress() {
        return this.proofofAddress;
    }
    
    public void setProofofAddress(String proofofAddress) {
        this.proofofAddress = proofofAddress;
    }




}


