package com.gtl.mmf.entity;
// Generated Feb 21, 2014 12:41:25 PM by Hibernate Tools 3.2.1.GA

/**
 * QualificationTb generated by hbm2java
 */
public class QualificationTb implements java.io.Serializable {

    private Integer id;
    private String qualification;

    public QualificationTb() {
    }

    public QualificationTb(String qualification) {
        this.qualification = qualification;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getQualification() {
        return this.qualification;
    }

    public void setQualification(String qualification) {
        this.qualification = qualification;
    }

}
