package com.gtl.mmf.entity;
// Generated 3 Apr, 2014 10:04:18 AM by Hibernate Tools 3.6.0

/**
 * QuestionoptionsmasterTb generated by hbm2java
 */
public class QuestionoptionsmasterTb implements java.io.Serializable {

    private Integer id;
    private String QOption;
    private int QOptionvalue;

    public QuestionoptionsmasterTb() {
    }

    public QuestionoptionsmasterTb(String QOption, int QOptionvalue) {
        this.QOption = QOption;
        this.QOptionvalue = QOptionvalue;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getQOption() {
        return this.QOption;
    }

    public void setQOption(String QOption) {
        this.QOption = QOption;
    }

    public int getQOptionvalue() {
        return this.QOptionvalue;
    }

    public void setQOptionvalue(int QOptionvalue) {
        this.QOptionvalue = QOptionvalue;
    }

}
