package com.gtl.mmf.entity;
// Generated Dec 22, 2014 4:17:26 PM by Hibernate Tools 3.2.1.GA



/**
 * ResidentStatusTb generated by hbm2java
 */
public class ResidentStatusTb  implements java.io.Serializable {


     private int id;
     private Integer key;
     private String status;

    public ResidentStatusTb() {
    }

	
    public ResidentStatusTb(int id) {
        this.id = id;
    }
    public ResidentStatusTb(int id, Integer key, String status) {
       this.id = id;
       this.key = key;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getKey() {
        return this.key;
    }
    
    public void setKey(Integer key) {
        this.key = key;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


