package com.gtl.mmf.entity;
// Generated Jul 1, 2016 3:55:34 PM by Hibernate Tools 3.4.0.CR1

/**
 * RiskProfileGroupDescriptionMasterTb generated by hbm2java
 */
public class RiskProfileGroupDescriptionMasterTb implements
		java.io.Serializable {

	private Integer riskProfileGroupId;
	private String riskProfileGroupName;
	private Float groupScoreLowerLimit;
	private Float groupScoreUpperLimit;
	private Integer riskProfileRecommendedPortfolioId;
	private String riskProfileDescription;

	public RiskProfileGroupDescriptionMasterTb() {
	}

	public RiskProfileGroupDescriptionMasterTb(String riskProfileGroupName,
			Float groupScoreLowerLimit, Float groupScoreUpperLimit,
			Integer riskProfileRecommendedPortfolioId,
			String riskProfileDescription) {
		this.riskProfileGroupName = riskProfileGroupName;
		this.groupScoreLowerLimit = groupScoreLowerLimit;
		this.groupScoreUpperLimit = groupScoreUpperLimit;
		this.riskProfileRecommendedPortfolioId = riskProfileRecommendedPortfolioId;
		this.riskProfileDescription = riskProfileDescription;
	}

	public Integer getRiskProfileGroupId() {
		return this.riskProfileGroupId;
	}

	public void setRiskProfileGroupId(Integer riskProfileGroupId) {
		this.riskProfileGroupId = riskProfileGroupId;
	}

	public String getRiskProfileGroupName() {
		return this.riskProfileGroupName;
	}

	public void setRiskProfileGroupName(String riskProfileGroupName) {
		this.riskProfileGroupName = riskProfileGroupName;
	}

	public Float getGroupScoreLowerLimit() {
		return this.groupScoreLowerLimit;
	}

	public void setGroupScoreLowerLimit(Float groupScoreLowerLimit) {
		this.groupScoreLowerLimit = groupScoreLowerLimit;
	}

	public Float getGroupScoreUpperLimit() {
		return this.groupScoreUpperLimit;
	}

	public void setGroupScoreUpperLimit(Float groupScoreUpperLimit) {
		this.groupScoreUpperLimit = groupScoreUpperLimit;
	}

	public Integer getRiskProfileRecommendedPortfolioId() {
		return this.riskProfileRecommendedPortfolioId;
	}

	public void setRiskProfileRecommendedPortfolioId(
			Integer riskProfileRecommendedPortfolioId) {
		this.riskProfileRecommendedPortfolioId = riskProfileRecommendedPortfolioId;
	}

	public String getRiskProfileDescription() {
		return this.riskProfileDescription;
	}

	public void setRiskProfileDescription(String riskProfileDescription) {
		this.riskProfileDescription = riskProfileDescription;
	}

}
