package com.gtl.mmf.entity;
// Generated Jul 1, 2016 6:01:17 PM by Hibernate Tools 3.4.0.CR1

/**
 * RiskProfileRecommendedPortfolioMasterTb generated by hbm2java
 */
public class RiskProfileRecommendedPortfolioMasterTb implements
		java.io.Serializable {

	private Integer id;
	private Integer assetAllocationId;
	private Integer riskProfileRecommendedPortfolioId;
	private Integer assetClassId;
	private Float assetClassAllocation;
	private Float allocationMinLimit;
	private Float allocationMaxLimit;

	public RiskProfileRecommendedPortfolioMasterTb() {
	}

	public RiskProfileRecommendedPortfolioMasterTb(Integer assetAllocationId,
			Integer riskProfileRecommendedPortfolioId, Integer assetClassId,
			Float assetClassAllocation, Float allocationMinLimit,
			Float allocationMaxLimit) {
		this.assetAllocationId = assetAllocationId;
		this.riskProfileRecommendedPortfolioId = riskProfileRecommendedPortfolioId;
		this.assetClassId = assetClassId;
		this.assetClassAllocation = assetClassAllocation;
		this.allocationMinLimit = allocationMinLimit;
		this.allocationMaxLimit = allocationMaxLimit;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAssetAllocationId() {
		return this.assetAllocationId;
	}

	public void setAssetAllocationId(Integer assetAllocationId) {
		this.assetAllocationId = assetAllocationId;
	}

	public Integer getRiskProfileRecommendedPortfolioId() {
		return this.riskProfileRecommendedPortfolioId;
	}

	public void setRiskProfileRecommendedPortfolioId(
			Integer riskProfileRecommendedPortfolioId) {
		this.riskProfileRecommendedPortfolioId = riskProfileRecommendedPortfolioId;
	}

	public Integer getAssetClassId() {
		return this.assetClassId;
	}

	public void setAssetClassId(Integer assetClassId) {
		this.assetClassId = assetClassId;
	}

	public Float getAssetClassAllocation() {
		return this.assetClassAllocation;
	}

	public void setAssetClassAllocation(Float assetClassAllocation) {
		this.assetClassAllocation = assetClassAllocation;
	}

	public Float getAllocationMinLimit() {
		return this.allocationMinLimit;
	}

	public void setAllocationMinLimit(Float allocationMinLimit) {
		this.allocationMinLimit = allocationMinLimit;
	}

	public Float getAllocationMaxLimit() {
		return this.allocationMaxLimit;
	}

	public void setAllocationMaxLimit(Float allocationMaxLimit) {
		this.allocationMaxLimit = allocationMaxLimit;
	}

}
