package com.gtl.mmf.entity;
// Generated Feb 4, 2015 12:01:03 PM by Hibernate Tools 3.2.1.GA



/**
 * StateTb generated by hbm2java
 */
public class StateTb  implements java.io.Serializable {


     private Integer id;
     private String stateName;
     private String stateCode;

    public StateTb() {
    }

    public StateTb(String stateName, String stateCode) {
       this.stateName = stateName;
       this.stateCode = stateCode;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }




}


