package com.gtl.mmf.entity;
// Generated Mar 6, 2014 10:30:50 AM by Hibernate Tools 3.2.1.GA

/**
 * SysConfParamTb generated by hbm2java
 */
public class SysConfParamTb implements java.io.Serializable {

    private Integer id;
    private String name;
    private String value;
    private String description;

    public SysConfParamTb() {
    }

    public SysConfParamTb(String name, String value, String description) {
        this.name = name;
        this.value = value;
        this.description = description;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
