package com.gtl.mmf.entity;
// Generated 5 Aug, 2015 4:24:44 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * TempAdv generated by hbm2java
 */
public class TempAdv implements java.io.Serializable {

    private Integer id;
    private String registrationId;
    private String email;
    private String firstname;
    private String middlename;
    private String lastname;
    private String sebi;
    private Date validityReg;
    private String pan;
    private Date dob;
    private String address;
    private String pincode;
    private String country;
    private String state;
    private String city;
    private String mobile;
    private String residentialTel;
    private String organisation;
    private String jobtitle;
    private String offcAddress;
    private String offcPincode;
    private String offcCountry;
    private String offcState;
    private String offcCity;
    private String offcMob;
    private String offcEmail;
    private String offcTel;
    private String correspondenceAddrs;
    private String bankName;
//    private String branch;
    private String accountType;
    private String accountNmbr;
    private String reAccno;
    private String ifsc;
    private String micr;
    private String bankAddrs;
    private String bankPincode;
    private String bankCountry;
    private String bankState;
    private String bankCity;
    private String primaryQualificationDegree;
    private String primaryQualificationInstitute;
    private String primaryQualificationYear;
    private String primaryQualificationId;
    private String secondaryQualificationDegree;
    private String secondaryQualificationInstitute;
    private String secondaryQualificationYear;
    private String secondaryQualificationId;
    private String tertiaryQualificationDegree;
    private String tertiaryQualificationInstitute;
    private String tertiaryQualificationYear;
    private String tertiaryQualificationId;
    private String sebiPath;
    private String resCityOther;
    private String offCityOther;
    private String bnkCityOther;
    private Boolean indvOrCprt;
    private String advPicPath;
    private String oneLineDesc;
    private String aboutMe;
    private String myInvestmentStrategy;

    public TempAdv() {
    }

    public TempAdv(String registrationId, String email, String firstname, String middlename, String lastname, String sebi, Date validityReg, String pan, Date dob, String address, String pincode, String country, String state, String city, String mobile, String residentialTel, String organisation, String jobtitle, String offcAddress, String offcPincode, String offcCountry, String offcState, String offcCity, String offcMob, String offcEmail, String offcTel, String correspondenceAddrs, String bankName, /*String branch,*/ String accountType, String accountNmbr, String reAccno, String ifsc, String micr, String bankAddrs, String bankPincode, String bankCountry, String bankState, String bankCity, String primaryQualificationDegree, String primaryQualificationInstitute, String primaryQualificationYear, String primaryQualificationId, String secondaryQualificationDegree, String secondaryQualificationInstitute, String secondaryQualificationYear, String secondaryQualificationId, String tertiaryQualificationDegree, String tertiaryQualificationInstitute, String tertiaryQualificationYear, String tertiaryQualificationId, String sebiPath, String resCityOther, String offCityOther, String bnkCityOther, Boolean indvOrCprt ,String advPicPath,String oneLineDesc,String aboutMe,String myInvestmentStrategy) {
        this.registrationId = registrationId;
        this.email = email;
        this.firstname = firstname;
        this.middlename = middlename;
        this.lastname = lastname;
        this.sebi = sebi;
        this.validityReg = validityReg;
        this.pan = pan;
        this.dob = dob;
        this.address = address;
        this.pincode = pincode;
        this.country = country;
        this.state = state;
        this.city = city;
        this.mobile = mobile;
        this.residentialTel = residentialTel;
        this.organisation = organisation;
        this.jobtitle = jobtitle;
        this.offcAddress = offcAddress;
        this.offcPincode = offcPincode;
        this.offcCountry = offcCountry;
        this.offcState = offcState;
        this.offcCity = offcCity;
        this.offcMob = offcMob;
        this.offcEmail = offcEmail;
        this.offcTel = offcTel;
        this.correspondenceAddrs = correspondenceAddrs;
        this.bankName = bankName;
//        this.branch = branch;
        this.accountType = accountType;
        this.accountNmbr = accountNmbr;
        this.reAccno = reAccno;
        this.ifsc = ifsc;
        this.micr = micr;
        this.bankAddrs = bankAddrs;
        this.bankPincode = bankPincode;
        this.bankCountry = bankCountry;
        this.bankState = bankState;
        this.bankCity = bankCity;
        this.primaryQualificationDegree = primaryQualificationDegree;
        this.primaryQualificationInstitute = primaryQualificationInstitute;
        this.primaryQualificationYear = primaryQualificationYear;
        this.primaryQualificationId = primaryQualificationId;
        this.secondaryQualificationDegree = secondaryQualificationDegree;
        this.secondaryQualificationInstitute = secondaryQualificationInstitute;
        this.secondaryQualificationYear = secondaryQualificationYear;
        this.secondaryQualificationId = secondaryQualificationId;
        this.tertiaryQualificationDegree = tertiaryQualificationDegree;
        this.tertiaryQualificationInstitute = tertiaryQualificationInstitute;
        this.tertiaryQualificationYear = tertiaryQualificationYear;
        this.tertiaryQualificationId = tertiaryQualificationId;
        this.sebiPath = sebiPath;
        this.resCityOther = resCityOther;
        this.offCityOther = offCityOther;
        this.bnkCityOther = bnkCityOther;
        this.indvOrCprt = indvOrCprt;
        this.advPicPath = advPicPath;
        this.oneLineDesc = oneLineDesc;
        this.aboutMe = aboutMe;
        this.myInvestmentStrategy = myInvestmentStrategy;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRegistrationId() {
        return this.registrationId;
    }

    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getMiddlename() {
        return this.middlename;
    }

    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getSebi() {
        return this.sebi;
    }

    public void setSebi(String sebi) {
        this.sebi = sebi;
    }

    public Date getValidityReg() {
        return this.validityReg;
    }

    public void setValidityReg(Date validityReg) {
        this.validityReg = validityReg;
    }

    public String getPan() {
        return this.pan;
    }

    public void setPan(String pan) {
        this.pan = pan;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPincode() {
        return this.pincode;
    }

    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getResidentialTel() {
        return this.residentialTel;
    }

    public void setResidentialTel(String residentialTel) {
        this.residentialTel = residentialTel;
    }

    public String getOrganisation() {
        return this.organisation;
    }

    public void setOrganisation(String organisation) {
        this.organisation = organisation;
    }

    public String getJobtitle() {
        return this.jobtitle;
    }

    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

    public String getOffcAddress() {
        return this.offcAddress;
    }

    public void setOffcAddress(String offcAddress) {
        this.offcAddress = offcAddress;
    }

    public String getOffcPincode() {
        return this.offcPincode;
    }

    public void setOffcPincode(String offcPincode) {
        this.offcPincode = offcPincode;
    }

    public String getOffcCountry() {
        return this.offcCountry;
    }

    public void setOffcCountry(String offcCountry) {
        this.offcCountry = offcCountry;
    }

    public String getOffcState() {
        return this.offcState;
    }

    public void setOffcState(String offcState) {
        this.offcState = offcState;
    }

    public String getOffcCity() {
        return this.offcCity;
    }

    public void setOffcCity(String offcCity) {
        this.offcCity = offcCity;
    }

    public String getOffcMob() {
        return this.offcMob;
    }

    public void setOffcMob(String offcMob) {
        this.offcMob = offcMob;
    }

    public String getOffcEmail() {
        return this.offcEmail;
    }

    public void setOffcEmail(String offcEmail) {
        this.offcEmail = offcEmail;
    }

    public String getOffcTel() {
        return this.offcTel;
    }

    public void setOffcTel(String offcTel) {
        this.offcTel = offcTel;
    }

    public String getCorrespondenceAddrs() {
        return this.correspondenceAddrs;
    }

    public void setCorrespondenceAddrs(String correspondenceAddrs) {
        this.correspondenceAddrs = correspondenceAddrs;
    }

    public String getBankName() {
        return this.bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getAccountType() {
        return this.accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    public String getAccountNmbr() {
        return this.accountNmbr;
    }

    public void setAccountNmbr(String accountNmbr) {
        this.accountNmbr = accountNmbr;
    }

    public String getReAccno() {
        return this.reAccno;
    }

    public void setReAccno(String reAccno) {
        this.reAccno = reAccno;
    }

    public String getIfsc() {
        return this.ifsc;
    }

    public void setIfsc(String ifsc) {
        this.ifsc = ifsc;
    }

    public String getMicr() {
        return this.micr;
    }

    public void setMicr(String micr) {
        this.micr = micr;
    }

    public String getBankAddrs() {
        return this.bankAddrs;
    }

    public void setBankAddrs(String bankAddrs) {
        this.bankAddrs = bankAddrs;
    }

    public String getBankPincode() {
        return this.bankPincode;
    }

    public void setBankPincode(String bankPincode) {
        this.bankPincode = bankPincode;
    }

    public String getBankCountry() {
        return this.bankCountry;
    }

    public void setBankCountry(String bankCountry) {
        this.bankCountry = bankCountry;
    }

    public String getBankState() {
        return this.bankState;
    }

    public void setBankState(String bankState) {
        this.bankState = bankState;
    }

    public String getBankCity() {
        return this.bankCity;
    }

    public void setBankCity(String bankCity) {
        this.bankCity = bankCity;
    }

    public String getPrimaryQualificationDegree() {
        return this.primaryQualificationDegree;
    }

    public void setPrimaryQualificationDegree(String primaryQualificationDegree) {
        this.primaryQualificationDegree = primaryQualificationDegree;
    }

    public String getPrimaryQualificationInstitute() {
        return this.primaryQualificationInstitute;
    }

    public void setPrimaryQualificationInstitute(String primaryQualificationInstitute) {
        this.primaryQualificationInstitute = primaryQualificationInstitute;
    }

    public String getPrimaryQualificationYear() {
        return this.primaryQualificationYear;
    }

    public void setPrimaryQualificationYear(String primaryQualificationYear) {
        this.primaryQualificationYear = primaryQualificationYear;
    }

    public String getPrimaryQualificationId() {
        return this.primaryQualificationId;
    }

    public void setPrimaryQualificationId(String primaryQualificationId) {
        this.primaryQualificationId = primaryQualificationId;
    }

    public String getSecondaryQualificationDegree() {
        return this.secondaryQualificationDegree;
    }

    public void setSecondaryQualificationDegree(String secondaryQualificationDegree) {
        this.secondaryQualificationDegree = secondaryQualificationDegree;
    }

    public String getSecondaryQualificationInstitute() {
        return this.secondaryQualificationInstitute;
    }

    public void setSecondaryQualificationInstitute(String secondaryQualificationInstitute) {
        this.secondaryQualificationInstitute = secondaryQualificationInstitute;
    }

    public String getSecondaryQualificationYear() {
        return this.secondaryQualificationYear;
    }

    public void setSecondaryQualificationYear(String secondaryQualificationYear) {
        this.secondaryQualificationYear = secondaryQualificationYear;
    }

    public String getSecondaryQualificationId() {
        return this.secondaryQualificationId;
    }

    public void setSecondaryQualificationId(String secondaryQualificationId) {
        this.secondaryQualificationId = secondaryQualificationId;
    }

    public String getTertiaryQualificationDegree() {
        return this.tertiaryQualificationDegree;
    }

    public void setTertiaryQualificationDegree(String tertiaryQualificationDegree) {
        this.tertiaryQualificationDegree = tertiaryQualificationDegree;
    }

    public String getTertiaryQualificationInstitute() {
        return this.tertiaryQualificationInstitute;
    }

    public void setTertiaryQualificationInstitute(String tertiaryQualificationInstitute) {
        this.tertiaryQualificationInstitute = tertiaryQualificationInstitute;
    }

    public String getTertiaryQualificationYear() {
        return this.tertiaryQualificationYear;
    }

    public void setTertiaryQualificationYear(String tertiaryQualificationYear) {
        this.tertiaryQualificationYear = tertiaryQualificationYear;
    }

    public String getTertiaryQualificationId() {
        return this.tertiaryQualificationId;
    }

    public void setTertiaryQualificationId(String tertiaryQualificationId) {
        this.tertiaryQualificationId = tertiaryQualificationId;
    }

    public String getSebiPath() {
        return this.sebiPath;
    }

    public void setSebiPath(String sebiPath) {
        this.sebiPath = sebiPath;
    }

    public String getResCityOther() {
        return this.resCityOther;
    }

    public void setResCityOther(String resCityOther) {
        this.resCityOther = resCityOther;
    }

    public String getOffCityOther() {
        return this.offCityOther;
    }

    public void setOffCityOther(String offCityOther) {
        this.offCityOther = offCityOther;
    }

    public String getBnkCityOther() {
        return this.bnkCityOther;
    }

    public void setBnkCityOther(String bnkCityOther) {
        this.bnkCityOther = bnkCityOther;
    }
    
    public Boolean getIndvOrCprt() {
        return this.indvOrCprt;
    }
    
    public void setIndvOrCprt(Boolean indvOrCprt) {
        this.indvOrCprt = indvOrCprt;
    }

//    public String getBranch() {
//        return branch;
//    }
//
//    public void setBranch(String branch) {
//        this.branch = branch;
//    }
    
	public String getAdvPicPath() {
		return advPicPath;
	}

	public void setAdvPicPath(String advPicPath) {
		this.advPicPath = advPicPath;
	}

	public String getOneLineDesc() {
		return oneLineDesc;
	}

	public void setOneLineDesc(String oneLineDesc) {
		this.oneLineDesc = oneLineDesc;
	}

	public String getAboutMe() {
		return aboutMe;
	}

	public void setAboutMe(String aboutMe) {
		this.aboutMe = aboutMe;
	}

	public String getMyInvestmentStrategy() {
		return myInvestmentStrategy;
	}

	public void setMyInvestmentStrategy(String myInvestmentStrategy) {
		this.myInvestmentStrategy = myInvestmentStrategy;
	}
}
