package com.gtl.mmf.entity;
// Generated 11 Apr, 2016 11:16:03 AM by Hibernate Tools 3.6.0



/**
 * TempRegistrationTb generated by hbm2java
 */
public class TempRegistrationTb  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String password;
     private String userType;
     private Boolean mailVerified;
     private String verificationCode;
     private Boolean mailSendSuccess;
     private int initLogin;

    public TempRegistrationTb() {
    }

	
    public TempRegistrationTb(String email, String password, String userType, String verificationCode, int initLogin) {
        this.email = email;
        this.password = password;
        this.userType = userType;
        this.verificationCode = verificationCode;
        this.initLogin = initLogin;
    }
    public TempRegistrationTb(String email, String password, String userType, Boolean mailVerified, String verificationCode, Boolean mailSendSuccess, int initLogin) {
       this.email = email;
       this.password = password;
       this.userType = userType;
       this.mailVerified = mailVerified;
       this.verificationCode = verificationCode;
       this.mailSendSuccess = mailSendSuccess;
       this.initLogin = initLogin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Boolean getMailVerified() {
        return this.mailVerified;
    }
    
    public void setMailVerified(Boolean mailVerified) {
        this.mailVerified = mailVerified;
    }
    public String getVerificationCode() {
        return this.verificationCode;
    }
    
    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }
    public Boolean getMailSendSuccess() {
        return this.mailSendSuccess;
    }
    
    public void setMailSendSuccess(Boolean mailSendSuccess) {
        this.mailSendSuccess = mailSendSuccess;
    }
    public int getInitLogin() {
        return this.initLogin;
    }
    
    public void setInitLogin(int initLogin) {
        this.initLogin = initLogin;
    }




}


