package com.gtl.mmf.entity;
// Generated Jul 1, 2016 12:23:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * TempregRegistrationIdMappingTb generated by hbm2java
 */
public class TempregRegistrationIdMappingTb implements java.io.Serializable {

	private Integer id;
	private Integer customerTempRegId;
	private String email;
	private String registrationId;

	public TempregRegistrationIdMappingTb() {
	}

	public TempregRegistrationIdMappingTb(Integer customerTempRegId,
			String email, String registrationId) {
		this.customerTempRegId = customerTempRegId;
		this.email = email;
		this.registrationId = registrationId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCustomerTempRegId() {
		return this.customerTempRegId;
	}

	public void setCustomerTempRegId(Integer customerTempRegId) {
		this.customerTempRegId = customerTempRegId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRegistrationId() {
		return this.registrationId;
	}

	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId;
	}

}
