package com.gtl.mmf.entity;
// Generated Jul 13, 2015 10:58:18 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Tieredpromocommissionmatrix generated by hbm2java
 */
public class Tieredpromocommissionmatrix  implements java.io.Serializable {


     private Integer id;
     private Promodefinitions promodefinitions;
     private Tiers tiers;
     private BigDecimal mgnmntFeeCommission;
     private BigDecimal perfFeeCommission;

    public Tieredpromocommissionmatrix() {
    }

    public Tieredpromocommissionmatrix(Promodefinitions promodefinitions, Tiers tiers, BigDecimal mgnmntFeeCommission, BigDecimal perfFeeCommission) {
       this.promodefinitions = promodefinitions;
       this.tiers = tiers;
       this.mgnmntFeeCommission = mgnmntFeeCommission;
       this.perfFeeCommission = perfFeeCommission;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Promodefinitions getPromodefinitions() {
        return this.promodefinitions;
    }
    
    public void setPromodefinitions(Promodefinitions promodefinitions) {
        this.promodefinitions = promodefinitions;
    }
    public Tiers getTiers() {
        return this.tiers;
    }
    
    public void setTiers(Tiers tiers) {
        this.tiers = tiers;
    }
    public BigDecimal getMgnmntFeeCommission() {
        return this.mgnmntFeeCommission;
    }
    
    public void setMgnmntFeeCommission(BigDecimal mgnmntFeeCommission) {
        this.mgnmntFeeCommission = mgnmntFeeCommission;
    }
    public BigDecimal getPerfFeeCommission() {
        return this.perfFeeCommission;
    }
    
    public void setPerfFeeCommission(BigDecimal perfFeeCommission) {
        this.perfFeeCommission = perfFeeCommission;
    }




}


