DELETE FROM `client_buttons_tb`;
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('1','ADVISOR','0','Invite Client','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('2','ADVISOR','0','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('3','ADVISOR','1','Withdraw Invite','btn-flat inverse','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('4','ADVISOR','1','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('5','ADVISOR','2','Reject','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('6','ADVISOR','2','Accept','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('7','ADVISOR','2','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('8','ADVISOR','3','Submit','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('9','ADVISOR','3','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('11','ADVISOR','4','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('12','ADVISOR','4','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('13','ADVISOR','10','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('14','ADVISOR','10','Submit','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('15','ADVISOR','10','Decline','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('21','ADVISOR','7','Submit','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('22','ADVISOR','7','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('23','ADVISOR','7','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('24','ADVISOR','11','Submit','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('25','ADVISOR','11','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('26','ADVISOR','11','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('29','ADVISOR','100','Suspend','btn-flat inverse','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('30','ADVISOR','100','Terminate','btn-flat inverse','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('31','ADVISOR','100','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('32','ADVISOR','9','Resume','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('33','ADVISOR','9','Terminate','btn-flat inverse','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('34','ADVISOR','9','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('35','ADVISOR','15','Renew','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('36','ADVISOR','15','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('37','INVESTOR','0','Invite Advisor','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('38','INVESTOR','0','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('39','INVESTOR','1','Reject','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('40','INVESTOR','1','Accept','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('41','INVESTOR','1','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('42','INVESTOR','2','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('43','INVESTOR','2','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('45','INVESTOR','3','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('46','INVESTOR','3','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('47','INVESTOR','4','Accept','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('48','INVESTOR','4','Review','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('49','INVESTOR','4','Decline','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('50','INVESTOR','10','Withdraw','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('51','INVESTOR','10','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('55','INVESTOR','6','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('56','INVESTOR','6','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('57','INVESTOR','7','Submit','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('58','INVESTOR','7','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('59','INVESTOR','7','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('60','INVESTOR','11','Submit','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('61','INVESTOR','11','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('64','INVESTOR','100','Suspend Advisor','btn-flat inverse','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('65','INVESTOR','100','Terminate Contract','btn-flat inverse','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('66','INVESTOR','100','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('67','INVESTOR','9','Pay Fees','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('68','INVESTOR','9','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('69','INVESTOR','15','Renew Contract','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('70','INVESTOR','15','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('71','INVESTOR','8','Accept','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('72','INVESTOR','8','Review','btn-flat success','0','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('73','INVESTOR','8','Cancel','btn-flat inverse','0','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('74','ADVISOR','125','Submit','btn-flat success','0','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('75','ADVISOR','125','Cancel','btn-flat inverse','0','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('76','ADVISOR','150','Cancel','btn-flat inverse','0','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('77','ADVISOR','150','Submit','btn-flat success','0','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('78','ADVISOR','5','Submit Questionnaire','btn-flat success btn-flat-long ','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('79','ADVISOR','5','Withdraw','btn-flat inverse btn-flat-long','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('80','ADVISOR','5','Cancel','btn-flat inverse btn-flat-long','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('81','INVESTOR','5','Submit','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('82','INVESTOR','5','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('83','INVESTOR','5','Cancel','btn-flat inverse','1','0');
INSERT INTO `client_buttons_tb` (`id`, `user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('84','ADVISOR','150','View IPS Created','btn-flat inverse','0','0');