DELETE FROM customer_portfolio_tb;
DELETE FROM customer_question_response_set_tb;
DELETE FROM customer_risk_profile_tb;
DELETE FROM customer_advisor_mapping_tb;
DELETE FROM `portfolio_details_tb`;
DELETE FROM portfolio_tb;
DELETE FROM master_advisor_tb;
DELETE FROM master_customer_tb;
DELETE FROM master_applicant_tb;
