DELETE FROM proofof_address_tb;
INSERT INTO proofof_address_tb VALUES(1,0,"Passport");
INSERT INTO proofof_address_tb VALUES(2,1,"Driving Licence");
INSERT INTO proofof_address_tb VALUES(3,2,"Aadhar");
INSERT INTO proofof_address_tb VALUES(4,3,"Voter Identity Card");
INSERT INTO proofof_address_tb VALUES(5,4,"NREGA Job Card ");
INSERT INTO proofof_address_tb VALUES(6,5,"Ration Card");
INSERT INTO proofof_address_tb VALUES(7,6,"Registered Lease/Sale Agreement of Residence");
INSERT INTO proofof_address_tb VALUES(8,7,"Latest Bank A/c Statement/Passbook (Not older than 3 months)");
INSERT INTO proofof_address_tb VALUES(9,8,"Latest Telephone Bill (only Land Line - Not older than 3 months)");
INSERT INTO proofof_address_tb VALUES(10,9,"Latest Electricity Bill(Not older than 3 months)");
INSERT INTO proofof_address_tb VALUES(11,10,"Latest Gas Bill(Not older than 3 months)");