ALTER TABLE `master_applicant_tb` ADD (
father_spouse_name VARCHAR(100) NULL,
nationality VARCHAR(50) NULL,
residential_status VARCHAR(50) NULL,
gender VARCHAR(10) NULL,
marital_status VARCHAR(20) NULL,
pan VARCHAR(20) NULL,
uid_aadhar VARCHAR(20) NULL,
proof_of_identity VARCHAR(50) NULL,
address_state VARCHAR(50) NULL,
address2_country VARCHAR(50) NULL,
address2_state VARCHAR(50) NULL,
address2_city VARCHAR(50) NULL,
address2_pincode VARCHAR(10) NULL,
telephone2 VARCHAR(15) NULL,
fax VARCHAR(15) NULL,
proof_of_address VARCHAR(50) NULL,
expiry_date DATE,
bank_name VARCHAR(200) NULL,
bank_building VARCHAR(200) NULL,
bank_street VARCHAR(50) NULL,
bank_area VARCHAR(50) NULL,
bank_city VARCHAR(50) NULL,
bank_pincode VARCHAR(10) NULL,
bank_subtype VARCHAR(50) NULL,
account_number VARCHAR(20) NULL,
ifcs_number VARCHAR(20) NULL,
micr_number VARCHAR(15) NULL,
account_type_open VARCHAR(100) NULL,
client_id VARCHAR(10) NULL,
dp_id VARCHAR(50) NULL,
trading_account_type VARCHAR(50) NULL,
demat_account_type VARCHAR(50) NULL,
sms_facility BOOLEAN DEFAULT false,
occupation VARCHAR(100) NULL,
income_range VARCHAR(50) NULL,
net_worth_date DATE,
amount VARCHAR(10) NULL,
politicaly_exposed BOOLEAN DEFAULT false,
politicaly_related BOOLEAN DEFAULT false,
instruction1 BOOLEAN,instruction2 BOOLEAN,
instruction3 BOOLEAN,
instruction4 BOOLEAN,
address_for_communication VARCHAR(100) NULL,
permanent_address BOOLEAN,
telephone_isd VARCHAR(5) NULL,
telephone_std VARCHAR(5) NULL,
telephone2_isd VARCHAR(5) NULL,
telephone2_std VARCHAR(5) NULL,
fax_isd VARCHAR(5) NULL,
fax_std VARCHAR(5) NULL);