CREATE TABLE `investor_nominee_details_tb`
(
nominee_details_id INT(11) NOT NULL AUTO_INCREMENT,
registration_id VARCHAR(15) NOT NULL,
name_nominee  VARCHAR(100) NOT NULL,
relationship_applicant VARCHAR(50)NULL,
dob_nominee DATE,
address_nominee VARCHAR(100)NULL,
place_nominee VARCHAR(100)NULL,
pincode_nominee VARCHAR(10) NULL,
state_nominee VARCHAR(50) NULL,
country_nominee VARCHAR(50) NULL,
tel_office_nominee VARCHAR(15) NULL,
tel_residence_nominee VARCHAR(15) NULL,
fax_nominee VARCHAR(15) NULL,
mobile_nominee VARCHAR(15) NULL,
email_nominee VARCHAR(50) NULL,
pan_nomine VARCHAR(12) NULL,
nominee_minor BOOLEAN,
dob_nominee_minor DATE,
name_guardian_nominee VARCHAR(50) NULL,
address_nominee_minor VARCHAR(100)NULL,
place_nominee_minor VARCHAR(100)NULL,
pincode_nominee_minor VARCHAR(10) NULL,
state_nominee_minor VARCHAR(50) NULL,
country_nominee_minor VARCHAR(50) NULL,
tel_office_nominee_minor VARCHAR(15) NULL,
tel_residence_nominee_minor VARCHAR(15) NULL,
fax_nominee_minor VARCHAR(15) NULL,
mobile_nominee_minor VARCHAR(15) NULL,
email_nominee_minor VARCHAR(50) NULL,
relationship_guardian_minor VARCHAR(50) NULL,
PRIMARY KEY (nominee_details_id),
UNIQUE KEY investor_nominee_details_tb_uk_1 (registration_id)
);
 
