CREATE TABLE mandate_form_tb(
`id` INT NOT NULL AUTO_INCREMENT,
`registration_id` VARCHAR(50) NOT NULL,
 umrn VARCHAR(20) NULL,
 action_type VARCHAR(20) NULL,
 sponser_bank_code VARCHAR(20) NULL,
 utility_code VARCHAR(20) NULL,
 name_of_biller VARCHAR(100) NOT NULL,
 debt_account_type VARCHAR(20) NULL,
 account_no VARCHAR(30) NOT NULL,
 bank_name  VARCHAR(100) NULL,
 ifsc_or_micr BOOLEAN,
 ifsc_or_micr_number VARCHAR(30) NULL,
 amount_words VARCHAR(100)  NULL,
 amount DECIMAL(10,2) NULL,
 frequency VARCHAR(20) NULL,
 debt_type VARCHAR(20) NULL,
 reference1  VARCHAR(100) NULL,
 customer_phone VARCHAR(12) NULL,
 reference2 VARCHAR(100) NULL,
 customer_email VARCHAR(50) NULL,
 mandate_created_date DATETIME,
 from_date DATETIME NULL,
 to_date DATETIME NULL,
 to_or_untill BOOLEAN,
 PRIMARY KEY (`id`)
);