CREATE TABLE `recomended_customer_portfolio_securities_tb` (
`recomended_customer_portfolio_securities_id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_portfolio_id` int(11) NOT NULL,
  `customer_portfolio_details_id` int(11) NOT NULL,
  `portfolio_id` int(11) unsigned NOT NULL,
  `portfolio_details_id` int(11) unsigned NOT NULL,
  `portfolio_securities_id` int(11) unsigned NOT NULL,
  `asset_class_id` smallint(11) NOT NULL,
  `security_id` text NOT NULL,
  `current_units` int(11) DEFAULT '0',
  `current_price` float(10,2) DEFAULT '0.00',
  `current_value` float(10,2) DEFAULT '0.00',
  `current_weight` float(5,2) DEFAULT '0.00',
  `exe_units` int(11) DEFAULT '0',
  `recommented_price` float(10,2) DEFAULT NULL,
  `avg_acquisition_price` float(10,2) DEFAULT '0.00',
  `initial_value` float(10,2) DEFAULT '0.00',
  `initial_weight` float(5,2) DEFAULT '0.00',
  `required_value` float(10,2) DEFAULT '0.00',
  `required_units` int(11) DEFAULT '0',
  `rebalance_required` tinyint(1) DEFAULT NULL,
  `rebalance_reqd_date` datetime DEFAULT NULL,
  `new_allocation` float(5,2) DEFAULT NULL,
  `security_description` varchar(100) DEFAULT NULL,
  `new_tolerance_negative_range` int(11) DEFAULT '0',
  `new_tolerance_positive_range` int(11) DEFAULT '0',
  `venueCode` varchar(100) DEFAULT NULL,
  `venueScriptCode` varchar(100) DEFAULT NULL,
  `security_code` varchar(50) DEFAULT NULL,
  `status` tinyint(1) DEFAULT NULL,
  `instrument_type` varchar(50) DEFAULT NULL,
  `expiration_date` datetime DEFAULT NULL,
  `strike_price` decimal(12,2) DEFAULT NULL,
PRIMARY KEY (`recomended_customer_portfolio_securities_id`),
KEY `recomended_customer_portfolio_securities_tb_fk_2` (`customer_portfolio_details_id`),
KEY `recomended_customer_portfolio_securities_tb_fk_3` (`portfolio_id`),
KEY `recomended_customer_portfolio_securities_tb_fk_4` (`portfolio_details_id`),
KEY `recomended_customer_portfolio_securities_tb_fk_5` (`portfolio_securities_id`),
KEY `recomended_customer_portfolio_securities_tb_fk_6` (`asset_class_id`),
KEY `recomended_customer_portfolio_securities_tb_uk_1` (`customer_portfolio_id`,`portfolio_id`,`venueCode`,`venueScriptCode`),
CONSTRAINT `recomended_customer_portfolio_securities_tb_fk_1` FOREIGN KEY (`customer_portfolio_id`) REFERENCES `customer_portfolio_tb` (`customer_portfolio_id`),
CONSTRAINT `recomended_customer_portfolio_securities_tb_fk_2` FOREIGN KEY (`customer_portfolio_details_id`) REFERENCES `customer_portfolio_details_tb` (`customer_portfolio_details_id`),
CONSTRAINT `recomended_customer_portfolio_securities_tb_fk_3` FOREIGN KEY (`portfolio_id`) REFERENCES `portfolio_tb` (`portfolio_id`),
CONSTRAINT `recomended_customer_portfolio_securities_tb_fk_4` FOREIGN KEY (`portfolio_details_id`) REFERENCES `portfolio_details_tb` (`portfolio_details_id`),
CONSTRAINT `recomended_customer_portfolio_securities_tb_fk_5` FOREIGN KEY (`portfolio_securities_id`) REFERENCES `portfolio_securities_tb` (`portfolio_securities_id`),
CONSTRAINT `recomended_customer_portfolio_securities_tb_fk_6` FOREIGN KEY (`asset_class_id`) REFERENCES `master_asset_tb` (`id`)
);