CREATE TABLE `mmfdb`.`master_advisor_tb`(  
  `advisor_id` INT NOT NULL AUTO_INCREMENT,
  `master_appl_id` INT NOT NULL,
  `registration_id` VARCHAR(50) not null ,
  `email` VARCHAR(50),
  `status` SMALLINT,
  `status_date` DATETIME,
  `first_name` VARCHAR(50),
  `middle_name` VARCHAR(50),
  `last_name` VARCHAR(50),
  `pan_no` VARCHAR(50),
  `home_address1` VARCHAR(100),
  `home_address2` VARCHAR(100),
  `home_address_city` VARCHAR(50),
  `home_address_pincode` VARCHAR(10),
  `home_address_country` VARCHAR(50),
  `home_telephone` VARCHAR(15),
  `mobile` VARCHAR(15),
  `work_organization` VARCHAR(50),
  `job_title` VARCHAR(50),
  `work_address1` VARCHAR(100),
  `work_address2` VARCHAR(100),
  `work_address_city` VARCHAR(50),
  `work_address_pincode` VARCHAR(10),
  `work_address_country` VARCHAR(50),
  `work_telephone` VARCHAR(15),
  `ifsc_code` VARCHAR(15),
  `bank_account_no` VARCHAR(20),
  `bank_balance` VARCHAR(20),
  `password` VARCHAR(50),
  `linkedin_user` VARCHAR(50),
  `linkedin_password` VARCHAR(50),
  `linkedin_member_id` VARCHAR(50),
  `SEBI_certification_no` VARCHAR(50),
  `primary_qualification_degree` VARCHAR(20),
  `primary_qualification_institute` VARCHAR(20),
  `primary_qualification_year` VARCHAR(5),
  `primary_qualification_id` VARCHAR(20),
  `secondary_qualification_degree` VARCHAR(20),
  `secondary_qualification_institute` VARCHAR(20),
  `secondary_qualification_year` VARCHAR(5),
  `secondary_qualification_id` VARCHAR(20),
  `tertiary_qualification_degree` VARCHAR(20),
  `tertiary_qualification_institute` VARCHAR(20),
  `tertiary_qualification_year` VARCHAR(5),
  `tertiary _qualification_id` VARCHAR(20),
  PRIMARY KEY (`advisor_id`),
  UNIQUE INDEX `UK_email` (`email`),
  UNIQUE INDEX `UK_pan_no` (`pan_no`),
  CONSTRAINT `FK_adv_reg_id` FOREIGN KEY (`master_appl_id`) REFERENCES `mmfdb`.`master_applicant_tb`(`id`)
);



