CREATE TABLE `mmfdb`.`master_customer_tb`(  
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `master_appl_id` INTEGER NOT NULL,
  `registration_id` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50),
  `status` SMALLINT,
  `status_date` DATETIME,
  `first_name` VARCHAR(50),
  `middle_name` VARCHAR(50),
  `last_name` VARCHAR(50),
  `pan_no` VARCHAR(50),
  `age` VARCHAR(5),
  `gender` VARCHAR(5),
  `home_address1` VARCHAR(100),
  `home_address2` VARCHAR(100),
  `home_address_city` VARCHAR(50),
  `home_address_pincode` VARCHAR(10),
  `home_address_country` VARCHAR(50),
  `home_telephone` VARCHAR(15),
  `mobile` VARCHAR(15),
  `work_organization` VARCHAR(50),
  `job_title` VARCHAR(50),
  `work_address1` VARCHAR(100),
  `work_address2` VARCHAR(100),
  `work_address_city` VARCHAR(50),
  `work_address_pincode` VARCHAR(10),
  `work_address_country` VARCHAR(50),
  `work_telephone` VARCHAR(15),
  `ifsc_code` VARCHAR(15),
  `bank_account_no` VARCHAR(20),
  `bank_balance` VARCHAR(20),
  `linkedin_user` VARCHAR(50),
  `linkedin_password` VARCHAR(50),
  `linkedin_member_id` VARCHAR(50),
  `broker_name` VARCHAR(50),
  `broker_account_no` VARCHAR(20),
  `bank_name` VARCHAR(50),
  `total_funds` DOUBLE,
  `total_allocated_funds` DOUBLE,
  `total_available_funds` DOUBLE,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `UK_email` (`email`),
  UNIQUE INDEX `UK_pan_no` (`pan_no`),
  CONSTRAINT `FK_customer_id` FOREIGN KEY (`master_appl_id`) REFERENCES `mmfdb`.`master_applicant_tb`(`id`)
);

