\. rl_10.0/procedure/EOD_UPDATE_ADVISOR_DETAILS_SP.sql
SELECT "rl_10.0/procedure/EOD_UPDATE_ADVISOR_DETAILS_SP.sql completed" AS "";
\. rl_10.0/procedure/EOD_CLIENT_PORTFOLIO_RETURNS_SP.sql
SELECT "rl_10.0/procedure/EOD_CLIENT_PORTFOLIO_RETURNS_SP.sql completed" AS "";
\. rl_10.0/procedure/EOD_MASTER_PORTFOLIO_RETURNS_SP.sql
SELECT "rl_10.0/procedure/EOD_MASTER_PORTFOLIO_RETURNS_SP.sql completed" AS "";
\. rl_10.0/procedure/BENCHMARK_PERFORMANCE_SP.sql
SELECT "rl_10.0/procedure/BENCHMARK_PERFORMANCE_SP.sql completed" AS "";
\. rl_10.0/procedure/SP_MANAGEMENTFEECALCULATION.sql
SELECT "rl_10.0/procedure/SP_MANAGEMENTFEECALCULATION.sql completed" AS "";
\. rl_10.0/procedure/CLIENT_TWR_PORTFOLIO_RETURNS_SP.sql
SELECT "rl_10.0/procedure/CLIENT_TWR_PORTFOLIO_RETURNS_SP.sql completed" AS "";
\. rl_10.0/procedure/CLIENT_TWR_PORTFOLIO_TOTAL_RETURNS_SP.sql
SELECT "rl_10.0/procedure/CLIENT_TWR_PORTFOLIO_TOTAL_RETURNS_SP.sql completed" AS "";
\. rl_10.0/procedure/RECOMMENDED_TWR_PORTFOLIO_RETURNS_SP.sql
SELECT "rl_10.0/procedure/RECOMMENDED_TWR_PORTFOLIO_RETURNS_SP.sql completed" AS "";
\. rl_10.0/procedure/RECOMMENDED_TWR_TOTAL_PORTFOLIO_RETURNS_SP.sql
SELECT "rl_10.0/procedure/RECOMMENDED_TWR_TOTAL_PORTFOLIO_RETURNS_SP.sql completed" AS "";
\. rl_10.0/procedure/UPDATECASHBALNCEOMSDISABLEDCASE.sql
SELECT "rl_10.0/procedure/UPDATECASHBALNCEOMSDISABLEDCASE.sql completed" AS "";
\. rl_10.0/procedure/UPDATECASHFLOWDETAILS.sql
SELECT "rl_10.0/procedure/UPDATECASHFLOWDETAILS.sql completed" AS "";
\. rl_10.0/procedure/UPDATEECSDEBTPAYMENTDETAILS.sql
SELECT "rl_10.0/procedure/UPDATEECSDEBTPAYMENTDETAILS.sql completed" AS "";