DELETE FROM `client_buttons_tb` WHERE status_code =8;
DELETE FROM `client_buttons_tb` WHERE status_code =125;
DELETE FROM `client_buttons_tb` WHERE status_code =150;
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('INVESTOR','8','Accept','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('INVESTOR','8','Review','btn-flat success','0','0');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('INVESTOR','8','Cancel','btn-flat inverse','0','0');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('ADVISOR','125','Submit','btn-flat success','0','0');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('ADVISOR','125','Cancel','btn-flat inverse','0','0');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('ADVISOR','150','Cancel','btn-flat inverse','0','0');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('ADVISOR','150','Submit','btn-flat success','0','0');
DELETE FROM `client_buttons_tb` WHERE status_code =5;
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('ADVISOR','5','Submit Questionnaire','btn-flat success btn-flat-long ','0','1');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('ADVISOR','5','Withdraw','btn-flat inverse btn-flat-long','1','1');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('ADVISOR','5','Cancel','btn-flat inverse btn-flat-long','1','0');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('INVESTOR','5','Submit','btn-flat success','0','1');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('INVESTOR','5','Withdraw','btn-flat inverse','1','1');
INSERT INTO `client_buttons_tb` (`user_type`, `status_code`, `button_text`, `style_class`, `immediate`, `confirm`) VALUES('INVESTOR','5','Cancel','btn-flat inverse','1','0');
DELETE FROM `client_buttons_tb` WHERE  `status_code` = 3 AND `user_type` = 'INVESTOR' AND `button_text` = 'Submit';
DELETE  FROM `client_buttons_tb` WHERE status_code = 3 AND user_type = 'ADVISOR' AND button_text = 'Decline';
DELETE FROM `client_buttons_tb` WHERE status_code = 6 AND user_type = 'ADVISOR';
