DELETE FROM `master_asset_tb`;
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('1','Equity','#069c00','9');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('2','Equity Diversified','#069c00','3');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('3','Large Caps','#09e900','1');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('4','Mid & Small Caps','#034800','2');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('5','International','#79d1cf','8');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('6','Gold','#f9cd45','7');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('7','Mutual Fund','#3c0909','10');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('8','Debt-Medium/Long','#3c0909','5');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('9','Derivatives','#C5E26D ','11');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('10','Cash','#818181','12');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('11','Balanced','#9EB557','4');
INSERT INTO `master_asset_tb` (`id`, `asset_name`, `asset_color`, `asset_order`) VALUES('12','Debt-Liquid/Short','#801313','6');