INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',0,'Invite Client','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',0,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',1,'Withdraw Invite','btn-flat inverse',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',1,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',2,'Reject','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',2,'Accept','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',2,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',3,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',3,'Submit','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',3,'Decline','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',4,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',4,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',10,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',10,'Submit','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',10,'Decline','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',5,'Submit','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',5,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',5,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',6,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',6,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',7,'Submit','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',7,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',7,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',11,'Submit','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',11,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',11,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',8,'Withdraw','btn-flat inverse',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',8,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',100,'Suspend','btn-flat inverse',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',100,'Terminate','btn-flat inverse',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',100,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',9,'Resume','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',9,'Terminate','btn-flat inverse',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',9,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',15,'Renew','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'ADVISOR',15,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',0,'Invite Advisor','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',0,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',1,'Reject','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',1,'Accept','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',1,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',2,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',2,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',3,'Submit','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',3,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',3,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',4,'Accept','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',4,'Review','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',4,'Decline','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',10,'Withdraw','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',10,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',5,'Submit','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',5,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',5,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',6,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',6,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',7,'Submit','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',7,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',7,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',11,'Submit','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',11,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',8,'Withdraw','btn-flat inverse',1,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',8,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',100,'Suspend Advisor','btn-flat inverse',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',100,'Terminate Contract','btn-flat inverse',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',100,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',9,'Pay Fees','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',9,'Cancel','btn-flat inverse',1,0);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',15,'Renew Contract','btn-flat success',0,1);
INSERT INTO `client_buttons_tb`(`id`,`user_type`,`status_code`,`button_text`,`style_class`,`immediate`,`confirm`) VALUES ( NULL,'INVESTOR',15,'Cancel','btn-flat inverse',1,0);