INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'AUM_PAYABLE','Monthly','1');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'AUM_PAYABLE','Quarterly','2');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'AUM_PAYABLE','Bi-annually','3');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'AUM_PAYABLE','Yearly','4');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'PERFORMANCE_FEE','Quarter','3');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'PERFORMANCE_FEE','Half Year','6');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'PERFORMANCE_FEE','Year','12');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'PERFORMANCE_FEE','Three Years','36');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'DURATION_FREQ','Quarter','3');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'DURATION_FREQ','Half Year','6');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'DURATION_FREQ','Year','12');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'FIXED_AMOUNT','&#8377; 2000','2000');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'FIXED_AMOUNT','&#8377; 3000','3000');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'FIXED_AMOUNT','&#8377; 5000','5000');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'FIXED_AMOUNT','&#8377; 7500','7500');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'FIXED_AMOUNT','&#8377; 10000','10000');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'FIXED_AMOUNT','&#8377; 12500','12500');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'FIXED_AMOUNT','&#8377; 15000','15000');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'DURATION','1','1');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'DURATION','2','2');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'DURATION','3','3');
INSERT INTO `mmfdb`.`contract_freq_lookup_tb`(`id`,`field_type`,`field_label`,`field_value`) VALUES ( NULL,'DURATION','5','5');

