
INSERT INTO country_tb(country_code,country_name)VALUES('IN','India');
INSERT INTO country_tb(country_code,country_name)VALUES('AF','Afghanistan');
INSERT INTO country_tb(country_code,country_name)VALUES('AL','Albania');
INSERT INTO country_tb(country_code,country_name)VALUES('DZ','Algeria');
INSERT INTO country_tb(country_code,country_name)VALUES('AS','American Samoa');
INSERT INTO country_tb(country_code,country_name)VALUES('AD','Andorra');
INSERT INTO country_tb(country_code,country_name)VALUES('AO','Angola');
INSERT INTO country_tb(country_code,country_name)VALUES('AI','Anguilla');
INSERT INTO country_tb(country_code,country_name)VALUES('AQ','Antarctica');
INSERT INTO country_tb(country_code,country_name)VALUES('AG','Antigua and Barbuda');
INSERT INTO country_tb(country_code,country_name)VALUES('AR','Argentina');
INSERT INTO country_tb(country_code,country_name)VALUES('AM','Armenia');
INSERT INTO country_tb(country_code,country_name)VALUES('AW','Aruba');
INSERT INTO country_tb(country_code,country_name)VALUES('AU','Australia');
INSERT INTO country_tb(country_code,country_name)VALUES('AT','Austria');
INSERT INTO country_tb(country_code,country_name)VALUES('AZ','Azerbaijan');
INSERT INTO country_tb(country_code,country_name)VALUES('BS','Bahamas');
INSERT INTO country_tb(country_code,country_name)VALUES('BH','Bahrain');
INSERT INTO country_tb(country_code,country_name)VALUES('BD','Bangladesh');
INSERT INTO country_tb(country_code,country_name)VALUES('BB','Barbados');
INSERT INTO country_tb(country_code,country_name)VALUES('BY','Belarus');
INSERT INTO country_tb(country_code,country_name)VALUES('BE','Belgium');
INSERT INTO country_tb(country_code,country_name)VALUES('BZ','Belize');
INSERT INTO country_tb(country_code,country_name)VALUES('BJ','Benin');
INSERT INTO country_tb(country_code,country_name)VALUES('BM','Bermuda');
INSERT INTO country_tb(country_code,country_name)VALUES('BT','Bhutan');
INSERT INTO country_tb(country_code,country_name)VALUES('BO','Bolivia');
INSERT INTO country_tb(country_code,country_name)VALUES('BA','Bosnia and Herzegowina');
INSERT INTO country_tb(country_code,country_name)VALUES('BW','Botswana');
INSERT INTO country_tb(country_code,country_name)VALUES('BV','Bouvet Island');
INSERT INTO country_tb(country_code,country_name)VALUES('BR','Brazil');
INSERT INTO country_tb(country_code,country_name)VALUES('IO','British Indian Ocean Territory');
INSERT INTO country_tb(country_code,country_name)VALUES('BN','Brunei Darussalam');
INSERT INTO country_tb(country_code,country_name)VALUES('BG','Bulgaria');
INSERT INTO country_tb(country_code,country_name)VALUES('BF','Burkina Faso');
INSERT INTO country_tb(country_code,country_name)VALUES('BI','Burundi');
INSERT INTO country_tb(country_code,country_name)VALUES('KH','Cambodia');
INSERT INTO country_tb(country_code,country_name)VALUES('CM','Cameroon');
INSERT INTO country_tb(country_code,country_name)VALUES('CA','Canada');
INSERT INTO country_tb(country_code,country_name)VALUES('CV','Cape Verde');
INSERT INTO country_tb(country_code,country_name)VALUES('KY','Cayman Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('CF','Central African Republic');
INSERT INTO country_tb(country_code,country_name)VALUES('TD','Chad');
INSERT INTO country_tb(country_code,country_name)VALUES('CL','Chile');
INSERT INTO country_tb(country_code,country_name)VALUES('CN','China');
INSERT INTO country_tb(country_code,country_name)VALUES('CX','Christmas Island');
INSERT INTO country_tb(country_code,country_name)VALUES('CC','Cocos (Keeling) Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('CO','Colombia');
INSERT INTO country_tb(country_code,country_name)VALUES('KM','Comoros');
INSERT INTO country_tb(country_code,country_name)VALUES('CG','Congo');
INSERT INTO country_tb(country_code,country_name)VALUES('CD','Congo, the Democratic Republic of the');
INSERT INTO country_tb(country_code,country_name)VALUES('CK','Cook Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('CR','Costa Rica');
INSERT INTO country_tb(country_code,country_name)VALUES('CI','Cote d\'Ivoire');
INSERT INTO country_tb(country_code,country_name)VALUES('HR','Croatia (Hrvatska)');
INSERT INTO country_tb(country_code,country_name)VALUES('CU','Cuba');
INSERT INTO country_tb(country_code,country_name)VALUES('CY','Cyprus');
INSERT INTO country_tb(country_code,country_name)VALUES('CZ','Czech Republic');
INSERT INTO country_tb(country_code,country_name)VALUES('DK','Denmark');
INSERT INTO country_tb(country_code,country_name)VALUES('DJ','Djibouti');
INSERT INTO country_tb(country_code,country_name)VALUES('DM','Dominica');
INSERT INTO country_tb(country_code,country_name)VALUES('DO','Dominican Republic');
INSERT INTO country_tb(country_code,country_name)VALUES('TP','East Timor');
INSERT INTO country_tb(country_code,country_name)VALUES('EC','Ecuador');
INSERT INTO country_tb(country_code,country_name)VALUES('EG','Egypt');
INSERT INTO country_tb(country_code,country_name)VALUES('SV','El Salvador');
INSERT INTO country_tb(country_code,country_name)VALUES('GQ','Equatorial Guinea');
INSERT INTO country_tb(country_code,country_name)VALUES('ER','Eritrea');
INSERT INTO country_tb(country_code,country_name)VALUES('EE','Estonia');
INSERT INTO country_tb(country_code,country_name)VALUES('ET','Ethiopia');
INSERT INTO country_tb(country_code,country_name)VALUES('FK','Falkland Islands (Malvinas)');
INSERT INTO country_tb(country_code,country_name)VALUES('FO','Faroe Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('FJ','Fiji');
INSERT INTO country_tb(country_code,country_name)VALUES('FI','Finland');
INSERT INTO country_tb(country_code,country_name)VALUES('FR','France');
INSERT INTO country_tb(country_code,country_name)VALUES('FX','France, Metropolitan');
INSERT INTO country_tb(country_code,country_name)VALUES('GF','French Guiana');
INSERT INTO country_tb(country_code,country_name)VALUES('PF','French Polynesia');
INSERT INTO country_tb(country_code,country_name)VALUES('TF','French Southern Territories');
INSERT INTO country_tb(country_code,country_name)VALUES('GA','Gabon');
INSERT INTO country_tb(country_code,country_name)VALUES('GM','Gambia');
INSERT INTO country_tb(country_code,country_name)VALUES('GE','Georgia');
INSERT INTO country_tb(country_code,country_name)VALUES('DE','Germany');
INSERT INTO country_tb(country_code,country_name)VALUES('GH','Ghana');
INSERT INTO country_tb(country_code,country_name)VALUES('GI','Gibraltar');
INSERT INTO country_tb(country_code,country_name)VALUES('GR','Greece');
INSERT INTO country_tb(country_code,country_name)VALUES('GL','Greenland');
INSERT INTO country_tb(country_code,country_name)VALUES('GD','Grenada');
INSERT INTO country_tb(country_code,country_name)VALUES('GP','Guadeloupe');
INSERT INTO country_tb(country_code,country_name)VALUES('GU','Guam');
INSERT INTO country_tb(country_code,country_name)VALUES('GT','Guatemala');
INSERT INTO country_tb(country_code,country_name)VALUES('GN','Guinea');
INSERT INTO country_tb(country_code,country_name)VALUES('GW','Guinea-Bissau');
INSERT INTO country_tb(country_code,country_name)VALUES('GY','Guyana');
INSERT INTO country_tb(country_code,country_name)VALUES('HT','Haiti');
INSERT INTO country_tb(country_code,country_name)VALUES('HM','Heard and Mc Donald Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('VA','Holy See (Vatican City State)');
INSERT INTO country_tb(country_code,country_name)VALUES('HN','Honduras');
INSERT INTO country_tb(country_code,country_name)VALUES('HK','Hong Kong');
INSERT INTO country_tb(country_code,country_name)VALUES('HU','Hungary');
INSERT INTO country_tb(country_code,country_name)VALUES('IS','Iceland');
INSERT INTO country_tb(country_code,country_name)VALUES('IN','India');
INSERT INTO country_tb(country_code,country_name)VALUES('ID','Indonesia');
INSERT INTO country_tb(country_code,country_name)VALUES('IR','Iran (Islamic Republic of)');
INSERT INTO country_tb(country_code,country_name)VALUES('IQ','Iraq');
INSERT INTO country_tb(country_code,country_name)VALUES('IE','Ireland');
INSERT INTO country_tb(country_code,country_name)VALUES('IL','Israel');
INSERT INTO country_tb(country_code,country_name)VALUES('IT','Italy');
INSERT INTO country_tb(country_code,country_name)VALUES('JM','Jamaica');
INSERT INTO country_tb(country_code,country_name)VALUES('JP','Japan');
INSERT INTO country_tb(country_code,country_name)VALUES('JO','Jordan');
INSERT INTO country_tb(country_code,country_name)VALUES('KZ','Kazakhstan');
INSERT INTO country_tb(country_code,country_name)VALUES('KE','Kenya');
INSERT INTO country_tb(country_code,country_name)VALUES('KI','Kiribati');
INSERT INTO country_tb(country_code,country_name)VALUES('KP','Korea, Democratic People\'s Republic of');
INSERT INTO country_tb(country_code,country_name)VALUES('KR','Korea, Republic of');
INSERT INTO country_tb(country_code,country_name)VALUES('KW','Kuwait');
INSERT INTO country_tb(country_code,country_name)VALUES('KG','Kyrgyzstan');
INSERT INTO country_tb(country_code,country_name)VALUES('LA','Lao People\'s Democratic Republic');
INSERT INTO country_tb(country_code,country_name)VALUES('LV','Latvia');
INSERT INTO country_tb(country_code,country_name)VALUES('LB','Lebanon');
INSERT INTO country_tb(country_code,country_name)VALUES('LS','Lesotho');
INSERT INTO country_tb(country_code,country_name)VALUES('LR','Liberia');
INSERT INTO country_tb(country_code,country_name)VALUES('LY','Libyan Arab Jamahiriya');
INSERT INTO country_tb(country_code,country_name)VALUES('LI','Liechtenstein');
INSERT INTO country_tb(country_code,country_name)VALUES('LT','Lithuania');
INSERT INTO country_tb(country_code,country_name)VALUES('LU','Luxembourg');
INSERT INTO country_tb(country_code,country_name)VALUES('MO','Macau');
INSERT INTO country_tb(country_code,country_name)VALUES('MK','Macedonia, The Former Yugoslav Republic of');
INSERT INTO country_tb(country_code,country_name)VALUES('MG','Madagascar');
INSERT INTO country_tb(country_code,country_name)VALUES('MW','Malawi');
INSERT INTO country_tb(country_code,country_name)VALUES('MY','Malaysia');
INSERT INTO country_tb(country_code,country_name)VALUES('MV','Maldives');
INSERT INTO country_tb(country_code,country_name)VALUES('ML','Mali');
INSERT INTO country_tb(country_code,country_name)VALUES('MT','Malta');
INSERT INTO country_tb(country_code,country_name)VALUES('MH','Marshall Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('MQ','Martinique');
INSERT INTO country_tb(country_code,country_name)VALUES('MR','Mauritania');
INSERT INTO country_tb(country_code,country_name)VALUES('MU','Mauritius');
INSERT INTO country_tb(country_code,country_name)VALUES('YT','Mayotte');
INSERT INTO country_tb(country_code,country_name)VALUES('MX','Mexico');
INSERT INTO country_tb(country_code,country_name)VALUES('FM','Micronesia, Federated States of');
INSERT INTO country_tb(country_code,country_name)VALUES('MD','Moldova, Republic of');
INSERT INTO country_tb(country_code,country_name)VALUES('MC','Monaco');
INSERT INTO country_tb(country_code,country_name)VALUES('MN','Mongolia');
INSERT INTO country_tb(country_code,country_name)VALUES('MS','Montserrat');
INSERT INTO country_tb(country_code,country_name)VALUES('MA','Morocco');
INSERT INTO country_tb(country_code,country_name)VALUES('MZ','Mozambique');
INSERT INTO country_tb(country_code,country_name)VALUES('MM','Myanmar');
INSERT INTO country_tb(country_code,country_name)VALUES('NA','Namibia');
INSERT INTO country_tb(country_code,country_name)VALUES('NR','Nauru');
INSERT INTO country_tb(country_code,country_name)VALUES('NP','Nepal');
INSERT INTO country_tb(country_code,country_name)VALUES('NL','Netherlands');
INSERT INTO country_tb(country_code,country_name)VALUES('AN','Netherlands Antilles');
INSERT INTO country_tb(country_code,country_name)VALUES('NC','New Caledonia');
INSERT INTO country_tb(country_code,country_name)VALUES('NZ','New Zealand');
INSERT INTO country_tb(country_code,country_name)VALUES('NI','Nicaragua');
INSERT INTO country_tb(country_code,country_name)VALUES('NE','Niger');
INSERT INTO country_tb(country_code,country_name)VALUES('NG','Nigeria');
INSERT INTO country_tb(country_code,country_name)VALUES('NU','Niue');
INSERT INTO country_tb(country_code,country_name)VALUES('NF','Norfolk Island');
INSERT INTO country_tb(country_code,country_name)VALUES('MP','Northern Mariana Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('NO','Norway');
INSERT INTO country_tb(country_code,country_name)VALUES('OM','Oman');
INSERT INTO country_tb(country_code,country_name)VALUES('PK','Pakistan');
INSERT INTO country_tb(country_code,country_name)VALUES('PW','Palau');
INSERT INTO country_tb(country_code,country_name)VALUES('PA','Panama');
INSERT INTO country_tb(country_code,country_name)VALUES('PG','Papua New Guinea');
INSERT INTO country_tb(country_code,country_name)VALUES('PY','Paraguay');
INSERT INTO country_tb(country_code,country_name)VALUES('PE','Peru');
INSERT INTO country_tb(country_code,country_name)VALUES('PH','Philippines');
INSERT INTO country_tb(country_code,country_name)VALUES('PN','Pitcairn');
INSERT INTO country_tb(country_code,country_name)VALUES('PL','Poland');
INSERT INTO country_tb(country_code,country_name)VALUES('PT','Portugal');
INSERT INTO country_tb(country_code,country_name)VALUES('PR','Puerto Rico');
INSERT INTO country_tb(country_code,country_name)VALUES('QA','Qatar');
INSERT INTO country_tb(country_code,country_name)VALUES('RE','Reunion');
INSERT INTO country_tb(country_code,country_name)VALUES('RO','Romania');
INSERT INTO country_tb(country_code,country_name)VALUES('RU','Russian Federation');
INSERT INTO country_tb(country_code,country_name)VALUES('RW','Rwanda');
INSERT INTO country_tb(country_code,country_name)VALUES('KN','Saint Kitts and Nevis');
INSERT INTO country_tb(country_code,country_name)VALUES('LC','Saint LUCIA');
INSERT INTO country_tb(country_code,country_name)VALUES('VC','Saint Vincent and the Grenadines');
INSERT INTO country_tb(country_code,country_name)VALUES('WS','Samoa');
INSERT INTO country_tb(country_code,country_name)VALUES('SM','San Marino');
INSERT INTO country_tb(country_code,country_name)VALUES('ST','Sao Tome and Principe');
INSERT INTO country_tb(country_code,country_name)VALUES('SA','Saudi Arabia');
INSERT INTO country_tb(country_code,country_name)VALUES('SN','Senegal');
INSERT INTO country_tb(country_code,country_name)VALUES('SC','Seychelles');
INSERT INTO country_tb(country_code,country_name)VALUES('SL','Sierra Leone');
INSERT INTO country_tb(country_code,country_name)VALUES('SG','Singapore');
INSERT INTO country_tb(country_code,country_name)VALUES('SK','Slovakia (Slovak Republic)');
INSERT INTO country_tb(country_code,country_name)VALUES('SI','Slovenia');
INSERT INTO country_tb(country_code,country_name)VALUES('SB','Solomon Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('SO','Somalia');
INSERT INTO country_tb(country_code,country_name)VALUES('ZA','South Africa');
INSERT INTO country_tb(country_code,country_name)VALUES('GS','South Georgia and the South Sandwich Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('ES','Spain');
INSERT INTO country_tb(country_code,country_name)VALUES('LK','Sri Lanka');
INSERT INTO country_tb(country_code,country_name)VALUES('SH','St. Helena');
INSERT INTO country_tb(country_code,country_name)VALUES('PM','St. Pierre and Miquelon');
INSERT INTO country_tb(country_code,country_name)VALUES('SD','Sudan');
INSERT INTO country_tb(country_code,country_name)VALUES('SR','Suriname');
INSERT INTO country_tb(country_code,country_name)VALUES('SJ','Svalbard and Jan Mayen Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('SZ','Swaziland');
INSERT INTO country_tb(country_code,country_name)VALUES('SE','Sweden');
INSERT INTO country_tb(country_code,country_name)VALUES('CH','Switzerland');
INSERT INTO country_tb(country_code,country_name)VALUES('SY','Syrian Arab Republic');
INSERT INTO country_tb(country_code,country_name)VALUES('TW','Taiwan, Province of China');
INSERT INTO country_tb(country_code,country_name)VALUES('TJ','Tajikistan');
INSERT INTO country_tb(country_code,country_name)VALUES('TZ','Tanzania, United Republic of');
INSERT INTO country_tb(country_code,country_name)VALUES('TH','Thailand');
INSERT INTO country_tb(country_code,country_name)VALUES('TG','Togo');
INSERT INTO country_tb(country_code,country_name)VALUES('TK','Tokelau');
INSERT INTO country_tb(country_code,country_name)VALUES('TO','Tonga');
INSERT INTO country_tb(country_code,country_name)VALUES('TT','Trinidad and Tobago');
INSERT INTO country_tb(country_code,country_name)VALUES('TN','Tunisia');
INSERT INTO country_tb(country_code,country_name)VALUES('TR','Turkey');
INSERT INTO country_tb(country_code,country_name)VALUES('TM','Turkmenistan');
INSERT INTO country_tb(country_code,country_name)VALUES('TC','Turks and Caicos Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('TV','Tuvalu');
INSERT INTO country_tb(country_code,country_name)VALUES('UG','Uganda');
INSERT INTO country_tb(country_code,country_name)VALUES('UA','Ukraine');
INSERT INTO country_tb(country_code,country_name)VALUES('AE','United Arab Emirates');
INSERT INTO country_tb(country_code,country_name)VALUES('GB','United Kingdom');
INSERT INTO country_tb(country_code,country_name)VALUES('US','United States');
INSERT INTO country_tb(country_code,country_name)VALUES('UM','United States Minor Outlying Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('UY','Uruguay');
INSERT INTO country_tb(country_code,country_name)VALUES('UZ','Uzbekistan');
INSERT INTO country_tb(country_code,country_name)VALUES('VU','Vanuatu');
INSERT INTO country_tb(country_code,country_name)VALUES('VE','Venezuela');
INSERT INTO country_tb(country_code,country_name)VALUES('VN','Viet Nam');
INSERT INTO country_tb(country_code,country_name)VALUES('VG','Virgin Islands (British)');
INSERT INTO country_tb(country_code,country_name)VALUES('VI','Virgin Islands (U.S.)');
INSERT INTO country_tb(country_code,country_name)VALUES('WF','Wallis and Futuna Islands');
INSERT INTO country_tb(country_code,country_name)VALUES('EH','Western Sahara');
INSERT INTO country_tb(country_code,country_name)VALUES('YE','Yemen');
INSERT INTO country_tb(country_code,country_name)VALUES('YU','Yugoslavia');
INSERT INTO country_tb(country_code,country_name)VALUES('ZM','Zambia');
INSERT INTO country_tb(country_code,country_name)VALUES('ZW','Zimbabwe');
