INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('1','Strongly Disagree','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('2','Disagree','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('3','No strong opinion','2');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('4','Agree','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('5','Strongly Agree','4');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('6','Retired','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('7','Less than 10','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('8','11 to 20 years','2');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('9','21 to 30 years','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('10','more than 30 years','4');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('11','Less than 20%','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('12','21% to 40%','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('13','41% to 60%','2');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('14','61% to 80%','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('15','81% to 100%','4');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('16','Almost zero','4');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('17','Low','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('18','Moderate','2');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('19','High','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('20','Very High','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('21','Strongly Disagree','4');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('22','Disagree','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('24','Agree','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('25','Strongly Agree','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('26','Less than 10%','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('27','10% to 19%','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('28','20% to 29%','2');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('29','30% to 49%','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('30','More than 50%','4');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('31','Less than 1%','4');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('32','2%','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('33','3%','2');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('34','4%','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('35','More than 5%','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('36','End of one year','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('37','In 2 to 5 years','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('38','In 6 to 10 years','2');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('39','In 11 to 20 years','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('40','Beyond 20 years','4');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('41','Less than 10 times','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('42','11 to 20 times','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('43','21 to 30 times','2');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('44','31 to 40 times','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('45','More than 40 times','4');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('46','Zero','0');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('47','Low','1');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('48','High','3');
INSERT INTO `questionoptionsmaster_tb` (`id`, `q_option`, `q_optionvalue`) VALUES('49','Very High','4');
