INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('1','I have adequate knowledge of investing in the stock market');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('2','I find it hard to pick the right investments to generate adequate returns.');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('3','When the market declines, I shift to safer investments such as fixed deposits/Gold');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('4','When the share price of a company with bright prospects falls to its lowest levels I buy more of that companys stock');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('5','Are you comfortable borrowing money to invest in the stock markets?');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('6','I am comfortable investing in Fixed Deposit/Gold rather than invest in Equities or Mutual Funds');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('7','I prefer investing in Equities to generate long term superior returns than invest in fixed deposits for moderate returns in the short term');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('8','What percentage of loss in portfolio value within single year can you tolerate given the chance of generating greater than 20% annually over a five year period');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('9','I would be disappointed if my portfolio generated returns lower than fixed deposits for a few years even if the annual growth over five years would average above 15%');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('10','My current job/business and related income is more or less stable');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('11','What percentage of your assets are you planning to invest?');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('12','I have accrued savings/assets which will support my current lifestyle into the future');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('13','I have the financial support of my family members/spouse in reaching my financial goals.');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('14','What is the extent of your liabilities (home loan or credit card bill outstanding)?');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('15','What is the extent of insurance cover due you have for lifes uncertainities such as theft, accident, disease, physical disability, death, etc.');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('16','Number of years before I retire');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('17','I need to annually withdraw x% cash from my portfolio to meet my ongoing needs, where x% is ');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('18','I have a significantly large financial obligation due ');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('19','The proportion of the future financial obligation as compared to my current savings is');
INSERT INTO `questionmaster_tb` (`id`, `question`) VALUES('20','I anticipate a significant increase in my spending over the coming years to meet my aspirations.');
