CREATE TABLE `temp_adv` (
	`id` INT (11) NOT NULL AUTO_INCREMENT,
	`registration_id` VARCHAR (150),
	`email` VARCHAR (150),
	`firstname` VARCHAR (300),
	`middlename` VARCHAR (300),
	`lastname` VARCHAR (300),
	`sebi` VARCHAR (60),
	`validity_reg` DATETIME ,
	`pan` VARCHAR (60),
	`dob` DATE ,
	`address` VARCHAR (300),
	`pincode` VARCHAR (30),
	`country` VARCHAR (150),
	`state` VARCHAR (150),
	`city` VARCHAR (150),
	`mobile` VARCHAR (45),
	`residential_tel` VARCHAR (45),
	`organisation` VARCHAR (300),
	`jobtitle` VARCHAR (300),
	`offc_address` VARCHAR (300),
	`offc_pincode` VARCHAR (30),
	`offc_country` VARCHAR (150),
	`offc_state` VARCHAR (150),
	`offc_city` VARCHAR (150),
	`offc_mob` VARCHAR (45),
	`offc_email` VARCHAR (300),
	`offc_tel` VARCHAR (60),
	`correspondence_addrs` VARCHAR (300),
	`bank_name` VARCHAR (300),
	`account_type` VARCHAR (300),
	`account_nmbr` VARCHAR (120),
	`re_accno` VARCHAR (120),
	`ifsc` VARCHAR (60),
	`micr` VARCHAR (60),
	`bank_addrs` VARCHAR (300),
	`bank_pincode` VARCHAR (30),
	`bank_country` VARCHAR (150),
	`bank_state` VARCHAR (150),
	`bank_city` VARCHAR (150),
	`primary_qualification_degree` VARCHAR (60),
	`primary_qualification_institute` VARCHAR (150),
	`primary_qualification_year` VARCHAR (15),
	`primary_qualification_id` VARCHAR (60),
	`secondary_qualification_degree` VARCHAR (60),
	`secondary_qualification_institute` VARCHAR (150),
	`secondary_qualification_year` VARCHAR (15),
	`secondary_qualification_id` VARCHAR (60),
	`tertiary_qualification_degree` VARCHAR (60),
	`tertiary_qualification_institute` VARCHAR (150),
	`tertiary_qualification_year` VARCHAR (15),
	`tertiary_qualification_id` VARCHAR (60),
	`sebi_path` VARCHAR (300),
	PRIMARY KEY (`id`),
    UNIQUE INDEX `UK_EMAIL` (`email`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC; 

