/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gtl.mmf.quartz.job;

import com.gtl.mmf.bao.IECSTransactionProcessingBAO;
import java.util.logging.Logger;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author trainee8
 */
public class ECSTransactionsTask {

    @Autowired
    private IECSTransactionProcessingBAO iECSTransactionProcessingBAO;
    private static final Logger LOGGER = Logger.getLogger("com.gtl.mmf.quartz.job.ECSTransactionsTask");

    //Generating TS File(Transmittal Sheet) for Billdesk 
    public void createECSTransmittalSheetForBillDesk() {
        LOGGER.info("Calling Creating Transmittal Sheet for Bill Desk verification");
        iECSTransactionProcessingBAO.createECSTransmittalSheet();
        LOGGER.info("Completed Creating Transmittal Sheet for Bill Desk.");
    }

    // Reading Response file for TS file sent by BillDesk to MMF
    void processApprovedMandates() {
        LOGGER.info("Starting reading approved mandates from ECS.");
        iECSTransactionProcessingBAO.processApprovedMandates();
    }

    /**
     * Reading P3 file generated by BillDesk as a response for P2 files This
     * method is called from ReadDebtCsvFileForUpdateTransactionJob.
     */
    public void readingDebtFileFromEcs() {
        LOGGER.info("Starting readingg Debt excel file for ECS.");
//        iECSTransactionProcessingBAO.readExcelFileForDebtFromECS();
        iECSTransactionProcessingBAO.readCsvFileForDebitPaymentResponseFromECS();
    }

    // Reading P1 text files generated by BillDesk (Response for TS File)
//     public void readingRegistrationTextFileFromECS() {
//     LOGGER.info("Starting reading Registration text file for ECS.");
//     iECSTransactionProcessingBAO.readRegistrationTextFileFromECS();
//     }
    
    /**
     * This method is used to calculate PF & MF for clients. This Method is
     * calling from TxnAndCashBalDataProcessingJob. Task
     * Name:feeCalculationTask.calculateMMFFee();
     */
//     public void createDebtCsvFileForECS() {
//     LOGGER.info("Calling Creating Debt text file for ECS.");
//     iECSTransactionProcessingBAO.createFileForECSDebtFile();
//     LOGGER.info("Completed Creating Debt text file for ECS.");
//     }
    
    
//     public void deleteDataFromEcsRegistrationDataTable() {
//     LOGGER.info("Deleting hostorical data from ecs registration text file content tb.");
//     iECSTransactionProcessingBAO.deleteDataFromEcsRegistrationDataTable();
//     LOGGER.info("Completed deleting hostorical data from ecs text file content tb.");
//     }
}
