/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gtl.mmf.quartz.job;

import java.util.logging.Logger;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;
import org.springframework.scheduling.quartz.QuartzJobBean;

/**
 *
 * @author trainee8
 */
public class ECSTransactionDataProcessingJob extends QuartzJobBean {

    private static final Logger LOGGER = Logger.getLogger("com.gtl.mmf.quartz.job.ECSTransactionDataProcessingJob");
    ECSTransactionsTask eCSTransactionsTask;

    @Override
    protected void executeInternal(JobExecutionContext jec) throws JobExecutionException {
        
        //Generating TS File(Transmittal Sheet) for Billdesk 
        LOGGER.info("Calling Creating TS Sheet");
        eCSTransactionsTask.createECSTransmittalSheetForBillDesk();
        LOGGER.info("completed calling Creating TS Sheet");
        
        // Reading P1 files generated by BillDesk (Response for TS File)
//        LOGGER.info("Reading ECS registration file fro FTP");
//        eCSTransactionsTask.readingRegistrationTextFileFromECS();
//        LOGGER.info("completed reading ECS registration file.");

        // Reading Response file for TS file sent by BillDesk to MMF
        LOGGER.info("Reading TS file for Mandates approved from billdesk and updating client status ");
        eCSTransactionsTask.processApprovedMandates();
        LOGGER.info("Completed reading TS file for Mandates approved");
        
        /**
         * We keep backup for P1 Text file in EcsRegistrationFiledataTb table
         * This method is to clear the table.
         */
//        LOGGER.info("Deleteing data from ecs_registration_filedata_tb");
//        eCSTransactionsTask.deleteDataFromEcsRegistrationDataTable();
//        LOGGER.info("completed Deleteing data from ecs_registration_filedata_tb");
    }

    public ECSTransactionsTask geteCSTransactionsTask() {
        return eCSTransactionsTask;
    }

    public void seteCSTransactionsTask(ECSTransactionsTask eCSTransactionsTask) {
        this.eCSTransactionsTask = eCSTransactionsTask;
    }

}
