CREATE TABLE `customer_twr_portfolio_return_tb`(
  `customer_twr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_portfolio_id` INT(11) NOT NULL,
  `customer_portfolio_details_id` INT (11) NOT NULL,
  `relation_id` INT(11) NOT NULL,
  `customer_id` INT(11) NOT NULL,
  `asset_id` SMALLINT(11) NOT NULL,
  `market_value_5d` DECIMAL(11,2) DEFAULT 0.00,
  `asset_return_5d` DECIMAL(7,2) DEFAULT 0.00,
  `rcm_return_5d` DECIMAL(7,2) DEFAULT 0.00,
  `market_value_1m` DECIMAL(11,2) DEFAULT 0.00,
  `asset_return_1m` DECIMAL(7,2) DEFAULT 0.00,
  `rcm_return_1m` DECIMAL(7,2) DEFAULT 0.00,
  `market_value_3m` DECIMAL(11,2) DEFAULT 0.00,
  `asset_return_3m` DECIMAL(7,2) DEFAULT 0.00,
  `rcm_return_3m` DECIMAL(7,2) DEFAULT 0.00,
  `market_value_6m` DECIMAL(11,2) DEFAULT 0.00,
  `asset_return_6m` DECIMAL(7,2) DEFAULT 0.00,
  `rcm_return_6m` DECIMAL(7,2) DEFAULT 0.00,
  `market_value_ytd` DECIMAL(11,2) DEFAULT 0.00,
  `asset_return_ytd` DECIMAL(7,2) DEFAULT 0.00,
  `rcm_return_ytd` DECIMAL(7,2) DEFAULT 0.00,
  `market_value_1y` DECIMAL(11,2) DEFAULT 0.00,
  `asset_return_1y` DECIMAL(7,2) DEFAULT 0.00,
  `rcm_return_1y` DECIMAL(7,2) DEFAULT 0.00,
  `market_value_5y` DECIMAL(11,2) DEFAULT 0.00,
  `asset_return_5y` DECIMAL(7,2) DEFAULT 0.00,
  `rcm_return_5y` DECIMAL(7,2) DEFAULT 0.00,
  `market_value_10y` DECIMAL(11,2) DEFAULT 0.00,
  `asset_return_10y` DECIMAL(7,2) DEFAULT 0.00,
  `rcm_return_10y` DECIMAL(7,2) DEFAULT 0.00,
  `market_value_all` DECIMAL(11,2) DEFAULT 0.00,
  `asset_return_all` DECIMAL(7,2) DEFAULT 0.00,
  `rcm_return_all` DECIMAL(7,2) DEFAULT 0.00,
  PRIMARY KEY (`customer_twr_id`),
  CONSTRAINT `customer_twr_portfolio_return_tb_fk_1` FOREIGN KEY (`customer_portfolio_id`) REFERENCES `customer_portfolio_tb`(`customer_portfolio_id`),
  CONSTRAINT `customer_twr_portfolio_return_tb_fk_2` FOREIGN KEY (`customer_id`) REFERENCES `master_customer_tb`(`customer_id`),
  CONSTRAINT `customer_twr_portfolio_return_tb_fk_3` FOREIGN KEY (`relation_id`) REFERENCES `customer_advisor_mapping_tb`(`relation_id`),
  CONSTRAINT `customer_twr_portfolio_return_tb_fk_4` FOREIGN KEY (`customer_portfolio_details_id`) REFERENCES `customer_portfolio_details_tb`(`customer_portfolio_details_id`)
);


