\. rl_9.0/procedure/EOD_CLIENT_PORTFOLIO_RETURNS_SP.sql
SELECT "rl_9.0/procedure/EOD_CLIENT_PORTFOLIO_RETURNS_SP.sql completed" AS "";
\. rl_9.0/procedure/EOD_MASTER_PORTFOLIO_RETURNS_SP.sql
SELECT "rl_9.0/procedure/EOD_MASTER_PORTFOLIO_RETURNS_SP.sql completed" AS "";
\. rl_9.0/procedure/RENAMETABLE_AND_CLEAR5DAY_OLDER_DATA_FROMBO_PROC.sql
SELECT "rl_9.0/procedure/RENAMETABLE_AND_CLEAR5DAY_OLDER_DATA_FROMBO_PROC.sql completed" AS "";
\. rl_9.0/procedure/UPDATE_CUSTOMER_POSITION_DETAILS.sql
SELECT "rl_9.0/procedure/UPDATE_CUSTOMER_POSITION_DETAILS.sql completed" AS "";
\. rl_9.0/procedure/UPDATECASHBALNCEOMSDISABLEDCASE.sql
SELECT "rl_9.0/procedure/UPDATECASHBALNCEOMSDISABLEDCASE.sql completed" AS "";
\. rl_9.0/procedure/EOD_RATE_ADVISOR_CHECK_SP.sql
SELECT "rl_9.0/procedure/EOD_RATE_ADVISOR_CHECK_SP.sql completed" AS "";

